// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

#pragma warning disable CS1591,CS1573,CS0465,CS0649,CS8019,CS1570,CS1584,CS1658,CS0436,CS8981
using global::System;
using global::System.Diagnostics;
using global::System.Diagnostics.CodeAnalysis;
using global::System.Runtime.CompilerServices;
using global::System.Runtime.InteropServices;
using global::System.Runtime.Versioning;
using winmdroot = global::Windows.Win32;
namespace Windows.Win32
{
	namespace UI.Shell
	{
		[Guid("C43DC798-95D1-4BEA-9030-BB99E2983A1A"),InterfaceType(ComInterfaceType.InterfaceIsIUnknown),ComImport()]
		[SupportedOSPlatform("windows6.1")]
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.164-beta+187018bf44")]
		internal interface ITaskbarList4
			:winmdroot.UI.Shell.ITaskbarList,winmdroot.UI.Shell.ITaskbarList2,winmdroot.UI.Shell.ITaskbarList3		{
			new void HrInit();

			new void AddTab(winmdroot.Foundation.HWND hwnd);

			new void DeleteTab(winmdroot.Foundation.HWND hwnd);

			new void ActivateTab(winmdroot.Foundation.HWND hwnd);

			new void SetActiveAlt(winmdroot.Foundation.HWND hwnd);

			new void MarkFullscreenWindow(winmdroot.Foundation.HWND hwnd, winmdroot.Foundation.BOOL fFullscreen);

			new void SetProgressValue(winmdroot.Foundation.HWND hwnd, ulong ullCompleted, ulong ullTotal);

			new void SetProgressState(winmdroot.Foundation.HWND hwnd, winmdroot.UI.Shell.TBPFLAG tbpFlags);

			new void RegisterTab(winmdroot.Foundation.HWND hwndTab, winmdroot.Foundation.HWND hwndMDI);

			new void UnregisterTab(winmdroot.Foundation.HWND hwndTab);

			new void SetTabOrder(winmdroot.Foundation.HWND hwndTab, winmdroot.Foundation.HWND hwndInsertBefore);

			new void SetTabActive(winmdroot.Foundation.HWND hwndTab, winmdroot.Foundation.HWND hwndMDI, uint dwReserved);

			unsafe new void ThumbBarAddButtons(winmdroot.Foundation.HWND hwnd, uint cButtons, winmdroot.UI.Shell.THUMBBUTTON* pButton);

			unsafe new void ThumbBarUpdateButtons(winmdroot.Foundation.HWND hwnd, uint cButtons, winmdroot.UI.Shell.THUMBBUTTON* pButton);

			new void ThumbBarSetImageList(winmdroot.Foundation.HWND hwnd, winmdroot.UI.Controls.HIMAGELIST himl);

			new void SetOverlayIcon(winmdroot.Foundation.HWND hwnd, winmdroot.UI.WindowsAndMessaging.HICON hIcon, winmdroot.Foundation.PCWSTR pszDescription);

			new void SetThumbnailTooltip(winmdroot.Foundation.HWND hwnd, winmdroot.Foundation.PCWSTR pszTip);

			unsafe new void SetThumbnailClip(winmdroot.Foundation.HWND hwnd, winmdroot.Foundation.RECT* prcClip);

			/// <summary>Allows a tab to specify whether the main application frame window or the tab window should be used as a thumbnail or in the peek feature under certain circumstances.</summary>
			/// <param name="hwndTab">
			/// <para>Type: <b>HWND</b> The handle of the tab window that is to have properties set. This handle must already be registered through <a href="https://docs.microsoft.com/windows/desktop/api/shobjidl_core/nf-shobjidl_core-itaskbarlist3-registertab">RegisterTab</a>.</para>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//shobjidl_core/nf-shobjidl_core-itaskbarlist4-settabproperties#parameters">Read more on docs.microsoft.com</see>.</para>
			/// </param>
			/// <param name="stpFlags">
			/// <para>Type: <b><a href="https://docs.microsoft.com/windows/desktop/api/shobjidl_core/ne-shobjidl_core-stpflag">STPFLAG</a></b> One or more members of the <a href="https://docs.microsoft.com/windows/desktop/api/shobjidl_core/ne-shobjidl_core-stpflag">STPFLAG</a> enumeration that specify the displayed thumbnail and peek image source of the tab thumbnail.</para>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//shobjidl_core/nf-shobjidl_core-itaskbarlist4-settabproperties#parameters">Read more on docs.microsoft.com</see>.</para>
			/// </param>
			/// <returns>
			/// <para>Type: <b>HRESULT</b> If this method succeeds, it returns <b xmlns:loc="http://microsoft.com/wdcml/l10n">S_OK</b>. Otherwise, it returns an <b xmlns:loc="http://microsoft.com/wdcml/l10n">HRESULT</b> error code.</para>
			/// </returns>
			/// <remarks>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//shobjidl_core/nf-shobjidl_core-itaskbarlist4-settabproperties">Learn more about this API from docs.microsoft.com</see>.</para>
			/// </remarks>
			void SetTabProperties(winmdroot.Foundation.HWND hwndTab, winmdroot.UI.Shell.STPFLAG stpFlags);
		}
	}
}
