// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

#pragma warning disable CS1591,CS1573,CS0465,CS0649,CS8019,CS1570,CS1584,CS1658,CS0436,CS8981
using global::System;
using global::System.Diagnostics;
using global::System.Diagnostics.CodeAnalysis;
using global::System.Runtime.CompilerServices;
using global::System.Runtime.InteropServices;
using global::System.Runtime.Versioning;
using winmdroot = global::Windows.Win32;
namespace Windows.Win32
{
	namespace System.Com
	{
		[Guid("00020401-0000-0000-C000-000000000046"),InterfaceType(ComInterfaceType.InterfaceIsIUnknown),ComImport()]
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.164-beta+187018bf44")]
		internal interface ITypeInfo
		{
			/// <summary>Retrieves a TYPEATTR structure that contains the attributes of the type description.</summary>
			/// <param name="ppTypeAttr">The attributes of this type description.</param>
			/// <returns>
			/// <para>This method can return one of these values. </para>
			/// <para>This doc was truncated.</para>
			/// </returns>
			/// <remarks>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//oaidl/nf-oaidl-itypeinfo-gettypeattr">Learn more about this API from docs.microsoft.com</see>.</para>
			/// </remarks>
			unsafe void GetTypeAttr(winmdroot.System.Com.TYPEATTR** ppTypeAttr);

			/// <summary>Retrieves the ITypeComp interface for the type description, which enables a client compiler to bind to the type description's members.</summary>
			/// <param name="ppTComp">The <a href="https://docs.microsoft.com/previous-versions/windows/desktop/api/oaidl/nn-oaidl-itypecomp">ITypeComp</a> of the containing type library.</param>
			/// <returns>
			/// <para>This method can return one of these values. </para>
			/// <para>This doc was truncated.</para>
			/// </returns>
			/// <remarks>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//oaidl/nf-oaidl-itypeinfo-gettypecomp">Learn more about this API from docs.microsoft.com</see>.</para>
			/// </remarks>
			void GetTypeComp(out winmdroot.System.Com.ITypeComp ppTComp);

			/// <summary>Retrieves the FUNCDESC structure that contains information about a specified function.</summary>
			/// <param name="index">The index of the function whose description is to be returned. The <i>index</i> should be in the range of 0 to 1 less than the number of functions in this type.</param>
			/// <param name="ppFuncDesc">A FUNCDESC structure that describes the specified function.</param>
			/// <returns>
			/// <para>This method can return one of these values. </para>
			/// <para>This doc was truncated.</para>
			/// </returns>
			/// <remarks>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//oaidl/nf-oaidl-itypeinfo-getfuncdesc">Learn more about this API from docs.microsoft.com</see>.</para>
			/// </remarks>
			void GetFuncDesc(uint index, out winmdroot.System.Com.FUNCDESC[] ppFuncDesc);

			/// <summary>Retrieves a VARDESC structure that describes the specified variable.</summary>
			/// <param name="index">The index of the variable whose description is to be returned. The index should be in the range of 0 to 1 less than the number of variables in this type.</param>
			/// <param name="ppVarDesc">A VARDESC that describes the specified variable.</param>
			/// <returns>
			/// <para>This method can return one of these values. </para>
			/// <para>This doc was truncated.</para>
			/// </returns>
			/// <remarks>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//oaidl/nf-oaidl-itypeinfo-getvardesc">Learn more about this API from docs.microsoft.com</see>.</para>
			/// </remarks>
			void GetVarDesc(uint index, out winmdroot.System.Com.VARDESC[] ppVarDesc);

			/// <summary>Retrieves the variable with the specified member ID or the name of the property or method and the parameters that correspond to the specified function ID.</summary>
			/// <param name="memid">The ID of the member whose name (or names) is to be returned.</param>
			/// <param name="rgBstrNames">The caller-allocated array. On return, each of the elements contains the name (or names) associated with the member.</param>
			/// <param name="cMaxNames">The length of the passed-in <i>rgBstrNames</i> array.</param>
			/// <param name="pcNames">The number of names in the <i>rgBstrNames</i> array.</param>
			/// <returns>
			/// <para>This method can return one of these values. </para>
			/// <para>This doc was truncated.</para>
			/// </returns>
			/// <remarks>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//oaidl/nf-oaidl-itypeinfo-getnames">Learn more about this API from docs.microsoft.com</see>.</para>
			/// </remarks>
			unsafe void GetNames(int memid, winmdroot.Foundation.BSTR* rgBstrNames, uint cMaxNames, uint* pcNames);

			/// <summary>If a type description describes a COM class, it retrieves the type description of the implemented interface types.</summary>
			/// <param name="index">The index of the implemented type whose handle is returned. The valid range is 0 to the <b>cImplTypes</b> field in the TYPEATTR structure.</param>
			/// <param name="pRefType">A handle for the implemented interface (if any). This handle can be passed to <a href="https://docs.microsoft.com/previous-versions/windows/desktop/api/oaidl/nf-oaidl-itypeinfo-getreftypeinfo">ITypeInfo::GetRefTypeInfo</a> to get the type description.</param>
			/// <returns>
			/// <para>This method can return one of these values. </para>
			/// <para>This doc was truncated.</para>
			/// </returns>
			/// <remarks>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//oaidl/nf-oaidl-itypeinfo-getreftypeofimpltype">Learn more about this API from docs.microsoft.com</see>.</para>
			/// </remarks>
			unsafe void GetRefTypeOfImplType(uint index, uint* pRefType);

			/// <summary>Retrieves the IMPLTYPEFLAGS enumeration for one implemented interface or base interface in a type description.</summary>
			/// <param name="index">The index of the implemented interface or base interface for which to get the flags.</param>
			/// <param name="pImplTypeFlags">The IMPLTYPEFLAGS enumeration value.</param>
			/// <returns>
			/// <para>This method can return one of these values. </para>
			/// <para>This doc was truncated.</para>
			/// </returns>
			/// <remarks>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//oaidl/nf-oaidl-itypeinfo-getimpltypeflags">Learn more about this API from docs.microsoft.com</see>.</para>
			/// </remarks>
			unsafe void GetImplTypeFlags(uint index, int* pImplTypeFlags);

			/// <summary>Maps between member names and member IDs, and parameter names and parameter IDs.</summary>
			/// <param name="rgszNames">An array of names to be mapped.</param>
			/// <param name="cNames">The count of the names to be mapped.</param>
			/// <param name="pMemId">Caller-allocated array in which name mappings are placed.</param>
			/// <returns>
			/// <para>This method can return one of these values. </para>
			/// <para>This doc was truncated.</para>
			/// </returns>
			/// <remarks>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//oaidl/nf-oaidl-itypeinfo-getidsofnames">Learn more about this API from docs.microsoft.com</see>.</para>
			/// </remarks>
			unsafe void GetIDsOfNames(winmdroot.Foundation.PWSTR* rgszNames, uint cNames, int* pMemId);

			/// <summary>Invokes a method, or accesses a property of an object, that implements the interface described by the type description.</summary>
			/// <param name="pvInstance">An instance of the interface described by this type description.</param>
			/// <param name="memid">The interface member.</param>
			/// <param name="wFlags">
			/// <para>Flags describing the context of the invoke call. </para>
			/// <para>This doc was truncated.</para>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//oaidl/nf-oaidl-itypeinfo-invoke#parameters">Read more on docs.microsoft.com</see>.</para>
			/// </param>
			/// <param name="pDispParams">An array of arguments, an array of DISPIDs for named arguments, and counts of the number of elements in each array.</param>
			/// <param name="pVarResult">The result. Should be null if the caller does not expect any result. If <i>wFlags</i> specifies DISPATCH_PROPERTYPUT or DISPATCH_PROPERTYPUTREF, <i>pVarResultis</i> is ignored.</param>
			/// <param name="pExcepInfo">An exception information structure, which is filled in only if DISP_E_EXCEPTION is returned. If <i>pExcepInfo</i> is null on input, only an HRESULT error will be returned.</param>
			/// <param name="puArgErr">If Invoke returns DISP_E_TYPEMISMATCH, <i>puArgErr</i> indicates the index (within <i>rgvarg</i>) of the argument with incorrect type. If more than one argument returns an error, <i>puArgErr</i> indicates only the first argument with an error. Arguments in pDispParams-&gt;rgvarg appear in reverse order, so the first argument is the one having the highest index in the array. This parameter cannot be null.</param>
			/// <returns>
			/// <para></para>
			/// <para>This doc was truncated.</para>
			/// </returns>
			/// <remarks>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//oaidl/nf-oaidl-itypeinfo-invoke">Learn more about this API from docs.microsoft.com</see>.</para>
			/// </remarks>
			unsafe void Invoke(void* pvInstance, int memid, winmdroot.System.Com.DISPATCH_FLAGS wFlags, ref winmdroot.System.Com.DISPPARAMS pDispParams, [MarshalAs(UnmanagedType.Struct)] out object pVarResult, out winmdroot.System.Com.EXCEPINFO pExcepInfo, uint* puArgErr);

			/// <summary>Retrieves the documentation string, the complete Help file name and path, and the context ID for the Help topic for a specified type description.</summary>
			/// <param name="memid">The ID of the member whose documentation is to be returned.</param>
			/// <param name="pBstrName">The name of the specified item. If the caller does not need the item name, <i>pBstrName</i> can be null.</param>
			/// <param name="pBstrDocString">The documentation string for the specified item. If the caller does not need the documentation string, <i>pBstrDocString</i> can be null.</param>
			/// <param name="pdwHelpContext">The Help localization context. If the caller does not need the Help context, it can be null.</param>
			/// <param name="pBstrHelpFile">The fully qualified name of the file containing the DLL used for Help file. If the caller does not need the file name, it can be null.</param>
			/// <returns>
			/// <para>This method can return one of these values. </para>
			/// <para>This doc was truncated.</para>
			/// </returns>
			/// <remarks>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//oaidl/nf-oaidl-itypeinfo-getdocumentation">Learn more about this API from docs.microsoft.com</see>.</para>
			/// </remarks>
			unsafe void GetDocumentation(int memid, [Optional] winmdroot.Foundation.BSTR* pBstrName, [Optional] winmdroot.Foundation.BSTR* pBstrDocString, uint* pdwHelpContext, [Optional] winmdroot.Foundation.BSTR* pBstrHelpFile);

			/// <summary>Retrieves a description or specification of an entry point for a function in a DLL.</summary>
			/// <param name="memid">The ID of the member function whose DLL entry description is to be returned.</param>
			/// <param name="invKind">The kind of member identified by <i>memid</i>. This is important for properties, because one <i>memid</i> can identify up to three separate functions.</param>
			/// <param name="pBstrDllName">If not null, the function sets <i>pBstrDllName</i> to the name of the DLL.</param>
			/// <param name="pBstrName">If not null, the function sets <i>pBstrName</i> to the name of the entry point. If the entry point is specified by an ordinal, this argument is null.</param>
			/// <param name="pwOrdinal">If not null, and if the function is defined by an ordinal, the function sets <i>pwOrdinal</i> to the ordinal.</param>
			/// <returns>
			/// <para>This method can return one of these values. </para>
			/// <para>This doc was truncated.</para>
			/// </returns>
			/// <remarks>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//oaidl/nf-oaidl-itypeinfo-getdllentry">Learn more about this API from docs.microsoft.com</see>.</para>
			/// </remarks>
			unsafe void GetDllEntry(int memid, winmdroot.System.Com.INVOKEKIND invKind, [Optional] winmdroot.Foundation.BSTR* pBstrDllName, [Optional] winmdroot.Foundation.BSTR* pBstrName, ushort* pwOrdinal);

			/// <summary>If a type description references other type descriptions, it retrieves the referenced type descriptions.</summary>
			/// <param name="hRefType">A handle to the referenced type description to return.</param>
			/// <param name="ppTInfo">The referenced type description.</param>
			/// <returns>
			/// <para>This method can return one of these values. </para>
			/// <para>This doc was truncated.</para>
			/// </returns>
			/// <remarks>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//oaidl/nf-oaidl-itypeinfo-getreftypeinfo">Learn more about this API from docs.microsoft.com</see>.</para>
			/// </remarks>
			void GetRefTypeInfo(uint hRefType, out winmdroot.System.Com.ITypeInfo ppTInfo);

			/// <summary>Retrieves the addresses of static functions or variables, such as those defined in a DLL.</summary>
			/// <param name="memid">The member ID of the static member whose address is to be retrieved. The member ID is defined by the DISPID.</param>
			/// <param name="invKind">Indicates whether the member is a property, and if so, what kind.</param>
			/// <param name="ppv">The static member.</param>
			/// <returns>
			/// <para>This method can return one of these values. </para>
			/// <para>This doc was truncated.</para>
			/// </returns>
			/// <remarks>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//oaidl/nf-oaidl-itypeinfo-addressofmember">Learn more about this API from docs.microsoft.com</see>.</para>
			/// </remarks>
			unsafe void AddressOfMember(int memid, winmdroot.System.Com.INVOKEKIND invKind, void** ppv);

			/// <summary>Creates a new instance of a type that describes a component object class (coclass).</summary>
			/// <param name="pUnkOuter">The controlling <b>IUnknown</b>. If Null, then a stand-alone instance is created. If valid, then an aggregate object is created.</param>
			/// <param name="riid">An ID for the interface that the caller will use to communicate with the resulting object.</param>
			/// <param name="ppvObj">An instance of the created object.</param>
			/// <returns>
			/// <para></para>
			/// <para>This doc was truncated.</para>
			/// </returns>
			/// <remarks>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//oaidl/nf-oaidl-itypeinfo-createinstance">Learn more about this API from docs.microsoft.com</see>.</para>
			/// </remarks>
			unsafe void CreateInstance([MarshalAs(UnmanagedType.IUnknown)] object pUnkOuter, global::System.Guid* riid, [MarshalAs(UnmanagedType.IUnknown)] out object ppvObj);

			/// <summary>Retrieves marshaling information.</summary>
			/// <param name="memid">The member ID that indicates which marshaling information is needed.</param>
			/// <param name="pBstrMops">The opcode string used in marshaling the fields of the structure described by the referenced type description, or null if there is no information to return.</param>
			/// <returns>
			/// <para>This method can return one of these values. </para>
			/// <para>This doc was truncated.</para>
			/// </returns>
			/// <remarks>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//oaidl/nf-oaidl-itypeinfo-getmops">Learn more about this API from docs.microsoft.com</see>.</para>
			/// </remarks>
			unsafe void GetMops(int memid, winmdroot.Foundation.BSTR* pBstrMops);

			/// <summary>Retrieves the containing type library and the index of the type description within that type library.</summary>
			/// <param name="ppTLib">The containing type library.</param>
			/// <param name="pIndex">The index of the type description within the containing type library.</param>
			/// <returns>
			/// <para>This method can return one of these values. </para>
			/// <para>This doc was truncated.</para>
			/// </returns>
			/// <remarks>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//oaidl/nf-oaidl-itypeinfo-getcontainingtypelib">Learn more about this API from docs.microsoft.com</see>.</para>
			/// </remarks>
			unsafe void GetContainingTypeLib(out winmdroot.System.Com.ITypeLib ppTLib, uint* pIndex);

			/// <summary>Releases a TYPEATTR previously returned by ITypeInfo::GetTypeAttr.</summary>
			/// <param name="pTypeAttr">The TYPEATTR to be freed.</param>
			/// <remarks>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//oaidl/nf-oaidl-itypeinfo-releasetypeattr">Learn more about this API from docs.microsoft.com</see>.</para>
			/// </remarks>
			[PreserveSig()]
			unsafe void ReleaseTypeAttr(winmdroot.System.Com.TYPEATTR* pTypeAttr);

			/// <summary>Releases a FUNCDESC previously returned by ITypeInfo::GetFuncDesc.</summary>
			/// <param name="pFuncDesc">The FUNCDESC to be freed.</param>
			/// <remarks>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//oaidl/nf-oaidl-itypeinfo-releasefuncdesc">Learn more about this API from docs.microsoft.com</see>.</para>
			/// </remarks>
						[PreserveSig()]
void ReleaseFuncDesc(in winmdroot.System.Com.FUNCDESC pFuncDesc);

			/// <summary>Releases a VARDESC previously returned by ITypeInfo::GetVarDesc.</summary>
			/// <param name="pVarDesc">The VARDESC to be freed.</param>
			/// <remarks>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//oaidl/nf-oaidl-itypeinfo-releasevardesc">Learn more about this API from docs.microsoft.com</see>.</para>
			/// </remarks>
						[PreserveSig()]
void ReleaseVarDesc(in winmdroot.System.Com.VARDESC pVarDesc);
		}
	}
}
