// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

#pragma warning disable CS1591,CS1573,CS0465,CS0649,CS8019,CS1570,CS1584,CS1658,CS0436,CS8981
using global::System;
using global::System.Diagnostics;
using global::System.Diagnostics.CodeAnalysis;
using global::System.Runtime.CompilerServices;
using global::System.Runtime.InteropServices;
using global::System.Runtime.Versioning;
using winmdroot = global::Windows.Win32;
namespace Windows.Win32
{
	namespace System.Com
	{
		/// <summary>Describes the type of a variable, the return type of a function, or the type of a function parameter.</summary>
		/// <remarks>
		/// <para>If the variable is VT_SAFEARRAY or VT_PTR, the union portion of the TYPEDESC contains a pointer to a TYPEDESC that specifies the element type.</para>
		/// <para><see href="https://docs.microsoft.com/windows/win32/api//oaidl/ns-oaidl-typedesc#">Read more on docs.microsoft.com</see>.</para>
		/// </remarks>
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.164-beta+187018bf44")]
		internal partial struct TYPEDESC
		{
			internal winmdroot.System.Com.TYPEDESC._Anonymous_e__Union Anonymous;
			/// <summary>The variant type.</summary>
			internal winmdroot.System.Com.VARENUM vt;

			[StructLayout(LayoutKind.Explicit)]
			[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.164-beta+187018bf44")]
			internal partial struct _Anonymous_e__Union
			{
				[FieldOffset(0)]
				internal unsafe winmdroot.System.Com.TYPEDESC* lptdesc;
				[FieldOffset(0)]
				internal unsafe winmdroot.System.Ole.ARRAYDESC* lpadesc;
				[FieldOffset(0)]
				internal uint hreftype;
			}
		}
	}
}
