// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

#pragma warning disable CS1591,CS1573,CS0465,CS0649,CS8019,CS1570,CS1584,CS1658,CS0436,CS8981
using global::System;
using global::System.Diagnostics;
using global::System.Diagnostics.CodeAnalysis;
using global::System.Runtime.CompilerServices;
using global::System.Runtime.InteropServices;
using global::System.Runtime.Versioning;
using winmdroot = global::Windows.Win32;
namespace Windows.Win32
{
	namespace UI.Shell
	{
		/// <summary>Used by THUMBBUTTON to control specific states and behaviors of the button.</summary>
		/// <remarks>
		/// <para><see href="https://docs.microsoft.com/windows/win32/api//shobjidl_core/ne-shobjidl_core-thumbbuttonflags">Learn more about this API from docs.microsoft.com</see>.</para>
		/// </remarks>
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.164-beta+187018bf44")]
		internal enum THUMBBUTTONFLAGS
		{
			/// <summary>The button is active and available to the user.</summary>
			THBF_ENABLED = 0,
			/// <summary>The button is disabled. It is present, but has a visual state that indicates that it will not respond to user action.</summary>
			THBF_DISABLED = 1,
			/// <summary>When the button is clicked, the taskbar button's flyout closes immediately.</summary>
			THBF_DISMISSONCLICK = 2,
			/// <summary>Do not draw a button border, use only the image.</summary>
			THBF_NOBACKGROUND = 4,
			/// <summary>The button is not shown to the user.</summary>
			THBF_HIDDEN = 8,
			/// <summary>The button is enabled but not interactive; no pressed button state is drawn. This value is intended for instances where the button is used in a notification.</summary>
			THBF_NONINTERACTIVE = 16,
		}
	}
}
