// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

#pragma warning disable CS1591,CS1573,CS0465,CS0649,CS8019,CS1570,CS1584,CS1658,CS0436,CS8981
using global::System;
using global::System.Diagnostics;
using global::System.Diagnostics.CodeAnalysis;
using global::System.Runtime.CompilerServices;
using global::System.Runtime.InteropServices;
using global::System.Runtime.Versioning;
using winmdroot = global::Windows.Win32;
namespace Windows.Win32
{
	namespace System.Com
	{
		[Guid("0000000C-0000-0000-C000-000000000046")]
		[SupportedOSPlatform("windows5.0")]
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.164-beta+187018bf44")]
		internal unsafe partial struct IStream_unmanaged
			:IComIID		{
			/// <inheritdoc cref="QueryInterface(global::System.Guid*, out object)"/>
			internal unsafe winmdroot.Foundation.HRESULT QueryInterface(in global::System.Guid riid, out object ppvObject)
			{
				fixed (global::System.Guid* riidLocal = &riid)
				{
					winmdroot.Foundation.HRESULT __result = this.QueryInterface(riidLocal, out ppvObject);
					return __result;
				}
			}

			public unsafe winmdroot.Foundation.HRESULT QueryInterface(global::System.Guid* riid, [MarshalAs(UnmanagedType.IUnknown)] out object ppvObject)
			{
				fixed (IStream_unmanaged* pThis = &this)
					return ((delegate *unmanaged [Stdcall]<IStream_unmanaged*,global::System.Guid* ,out object ,winmdroot.Foundation.HRESULT>)lpVtbl[0])(pThis, riid, out ppvObject);
			}

			public uint AddRef()
			{
				fixed (IStream_unmanaged* pThis = &this)
					return ((delegate *unmanaged [Stdcall]<IStream_unmanaged*,uint>)lpVtbl[1])(pThis);
			}

			public uint Release()
			{
				fixed (IStream_unmanaged* pThis = &this)
					return ((delegate *unmanaged [Stdcall]<IStream_unmanaged*,uint>)lpVtbl[2])(pThis);
			}

			public unsafe winmdroot.Foundation.HRESULT Read(void* pv, uint cb, [Optional] uint* pcbRead)
			{
				fixed (IStream_unmanaged* pThis = &this)
					return ((delegate *unmanaged [Stdcall]<IStream_unmanaged*,void* ,uint ,uint* ,winmdroot.Foundation.HRESULT>)lpVtbl[3])(pThis, pv, cb, pcbRead);
			}

			public unsafe winmdroot.Foundation.HRESULT Write(void* pv, uint cb, [Optional] uint* pcbWritten)
			{
				fixed (IStream_unmanaged* pThis = &this)
					return ((delegate *unmanaged [Stdcall]<IStream_unmanaged*,void* ,uint ,uint* ,winmdroot.Foundation.HRESULT>)lpVtbl[4])(pThis, pv, cb, pcbWritten);
			}

			public unsafe void Seek(long dlibMove, global::System.IO.SeekOrigin dwOrigin, [Optional] ulong* plibNewPosition)
			{
				fixed (IStream_unmanaged* pThis = &this)
					((delegate *unmanaged [Stdcall]<IStream_unmanaged*,long ,global::System.IO.SeekOrigin ,ulong* ,winmdroot.Foundation.HRESULT>)lpVtbl[5])(pThis, dlibMove, dwOrigin, plibNewPosition).ThrowOnFailure();
			}

			public void SetSize(ulong libNewSize)
			{
				fixed (IStream_unmanaged* pThis = &this)
					((delegate *unmanaged [Stdcall]<IStream_unmanaged*,ulong ,winmdroot.Foundation.HRESULT>)lpVtbl[6])(pThis, libNewSize).ThrowOnFailure();
			}

			public unsafe void CopyTo(winmdroot.System.Com.IStream pstm, ulong cb, [Optional] ulong* pcbRead, [Optional] ulong* pcbWritten)
			{
				fixed (IStream_unmanaged* pThis = &this)
					((delegate *unmanaged [Stdcall]<IStream_unmanaged*,winmdroot.System.Com.IStream ,ulong ,ulong* ,ulong* ,winmdroot.Foundation.HRESULT>)lpVtbl[7])(pThis, pstm, cb, pcbRead, pcbWritten).ThrowOnFailure();
			}

			public void Commit(winmdroot.System.Com.STGC grfCommitFlags)
			{
				fixed (IStream_unmanaged* pThis = &this)
					((delegate *unmanaged [Stdcall]<IStream_unmanaged*,winmdroot.System.Com.STGC ,winmdroot.Foundation.HRESULT>)lpVtbl[8])(pThis, grfCommitFlags).ThrowOnFailure();
			}

			public void Revert()
			{
				fixed (IStream_unmanaged* pThis = &this)
					((delegate *unmanaged [Stdcall]<IStream_unmanaged*,winmdroot.Foundation.HRESULT>)lpVtbl[9])(pThis).ThrowOnFailure();
			}

			public void LockRegion(ulong libOffset, ulong cb, winmdroot.System.Com.LOCKTYPE dwLockType)
			{
				fixed (IStream_unmanaged* pThis = &this)
					((delegate *unmanaged [Stdcall]<IStream_unmanaged*,ulong ,ulong ,winmdroot.System.Com.LOCKTYPE ,winmdroot.Foundation.HRESULT>)lpVtbl[10])(pThis, libOffset, cb, dwLockType).ThrowOnFailure();
			}

			public void UnlockRegion(ulong libOffset, ulong cb, uint dwLockType)
			{
				fixed (IStream_unmanaged* pThis = &this)
					((delegate *unmanaged [Stdcall]<IStream_unmanaged*,ulong ,ulong ,uint ,winmdroot.Foundation.HRESULT>)lpVtbl[11])(pThis, libOffset, cb, dwLockType).ThrowOnFailure();
			}

			/// <inheritdoc cref="Stat(winmdroot.System.Com.STATSTG*, winmdroot.System.Com.STATFLAG)"/>
			internal unsafe void Stat(out winmdroot.System.Com.STATSTG pstatstg, winmdroot.System.Com.STATFLAG grfStatFlag)
			{
				fixed (winmdroot.System.Com.STATSTG* pstatstgLocal = &pstatstg)
				{
					this.Stat(pstatstgLocal, grfStatFlag);
				}
			}

			public unsafe void Stat(winmdroot.System.Com.STATSTG* pstatstg, winmdroot.System.Com.STATFLAG grfStatFlag)
			{
				fixed (IStream_unmanaged* pThis = &this)
					((delegate *unmanaged [Stdcall]<IStream_unmanaged*,winmdroot.System.Com.STATSTG* ,winmdroot.System.Com.STATFLAG ,winmdroot.Foundation.HRESULT>)lpVtbl[12])(pThis, pstatstg, grfStatFlag).ThrowOnFailure();
			}

			public void Clone(out winmdroot.System.Com.IStream ppstm)
			{
				fixed (IStream_unmanaged* pThis = &this)
					((delegate *unmanaged [Stdcall]<IStream_unmanaged*,out winmdroot.System.Com.IStream ,winmdroot.Foundation.HRESULT>)lpVtbl[13])(pThis, out ppstm).ThrowOnFailure();
			}
			private void** lpVtbl;
			/// <summary>The IID guid for this interface.</summary>
			/// <value>{0000000c-0000-0000-c000-000000000046}</value>
			internal static readonly Guid IID_Guid = new Guid(0x0000000C, 0x0000, 0x0000, 0xC0, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x46);

			static ref readonly Guid IComIID.Guid			{
								[MethodImpl(MethodImplOptions.AggressiveInlining)]
get
				{
					ReadOnlySpan<byte> data = new byte[]					{
0x0C,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0xC0,0x00,0x00,0x00,0x00,0x00,0x00,0x46					};
					return ref Unsafe.As<byte,Guid>(ref MemoryMarshal.GetReference(data));
				}
			}
		}
	}
}
