// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

#pragma warning disable CS1591,CS1573,CS0465,CS0649,CS8019,CS1570,CS1584,CS1658,CS0436,CS8981
using global::System;
using global::System.Diagnostics;
using global::System.Diagnostics.CodeAnalysis;
using global::System.Runtime.CompilerServices;
using global::System.Runtime.InteropServices;
using global::System.Runtime.Versioning;
using winmdroot = global::Windows.Win32;
namespace Windows.Win32
{
	[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.164-beta+187018bf44")]
	internal static partial class System_Com_ITypeInfo_Extensions
	{
		/// <inheritdoc cref="winmdroot.System.Com.ITypeInfo.GetTypeAttr(winmdroot.System.Com.TYPEATTR**)"/>
		internal static unsafe void GetTypeAttr(this winmdroot.System.Com.ITypeInfo @this, out winmdroot.System.Com.TYPEATTR* ppTypeAttr)
		{
			fixed (winmdroot.System.Com.TYPEATTR** ppTypeAttrLocal = &ppTypeAttr)
			{
				@this.GetTypeAttr(ppTypeAttrLocal);
			}
		}

		/// <inheritdoc cref="winmdroot.System.Com.ITypeInfo.GetNames(int, winmdroot.Foundation.BSTR*, uint, uint*)"/>
		internal static unsafe void GetNames(this winmdroot.System.Com.ITypeInfo @this, int memid, out SysFreeStringSafeHandle rgBstrNames, uint cMaxNames, out uint pcNames)
		{
			fixed (uint* pcNamesLocal = &pcNames)
			{
				winmdroot.Foundation.BSTR rgBstrNamesLocal;
				@this.GetNames(memid, &rgBstrNamesLocal, cMaxNames, pcNamesLocal);
				rgBstrNames = new SysFreeStringSafeHandle(rgBstrNamesLocal, ownsHandle: true);
			}
		}

		/// <inheritdoc cref="winmdroot.System.Com.ITypeInfo.GetRefTypeOfImplType(uint, uint*)"/>
		internal static unsafe void GetRefTypeOfImplType(this winmdroot.System.Com.ITypeInfo @this, uint index, out uint pRefType)
		{
			fixed (uint* pRefTypeLocal = &pRefType)
			{
				@this.GetRefTypeOfImplType(index, pRefTypeLocal);
			}
		}

		/// <inheritdoc cref="winmdroot.System.Com.ITypeInfo.GetImplTypeFlags(uint, int*)"/>
		internal static unsafe void GetImplTypeFlags(this winmdroot.System.Com.ITypeInfo @this, uint index, out int pImplTypeFlags)
		{
			fixed (int* pImplTypeFlagsLocal = &pImplTypeFlags)
			{
				@this.GetImplTypeFlags(index, pImplTypeFlagsLocal);
			}
		}

		/// <inheritdoc cref="winmdroot.System.Com.ITypeInfo.GetIDsOfNames(winmdroot.Foundation.PWSTR*, uint, int*)"/>
		internal static unsafe void GetIDsOfNames(this winmdroot.System.Com.ITypeInfo @this, Span<winmdroot.Foundation.PWSTR> rgszNames, Span<int> pMemId)
		{
			fixed (int* pMemIdLocal = pMemId)
			{
				fixed (winmdroot.Foundation.PWSTR* rgszNamesLocal = rgszNames)
				{
					if (rgszNames.Length != pMemId.Length)throw new ArgumentException();
					@this.GetIDsOfNames(rgszNamesLocal, (uint )pMemId.Length, pMemIdLocal);
				}
			}
		}

		/// <inheritdoc cref="winmdroot.System.Com.ITypeInfo.Invoke(void*, int, winmdroot.System.Com.DISPATCH_FLAGS, ref winmdroot.System.Com.DISPPARAMS, out object, out winmdroot.System.Com.EXCEPINFO, uint*)"/>
		internal static unsafe void Invoke(this winmdroot.System.Com.ITypeInfo @this, void* pvInstance, int memid, winmdroot.System.Com.DISPATCH_FLAGS wFlags, ref winmdroot.System.Com.DISPPARAMS pDispParams, out object pVarResult, out winmdroot.System.Com.EXCEPINFO pExcepInfo, out uint puArgErr)
		{
			fixed (uint* puArgErrLocal = &puArgErr)
			{
				@this.Invoke(pvInstance, memid, wFlags, ref pDispParams, out pVarResult, out pExcepInfo, puArgErrLocal);
			}
		}

		/// <inheritdoc cref="winmdroot.System.Com.ITypeInfo.GetDocumentation(int, winmdroot.Foundation.BSTR*, winmdroot.Foundation.BSTR*, uint*, winmdroot.Foundation.BSTR*)"/>
		internal static unsafe void GetDocumentation(this winmdroot.System.Com.ITypeInfo @this, int memid, out SysFreeStringSafeHandle pBstrName, out SysFreeStringSafeHandle pBstrDocString, out uint pdwHelpContext, out SysFreeStringSafeHandle pBstrHelpFile)
		{
			fixed (uint* pdwHelpContextLocal = &pdwHelpContext)
			{
				winmdroot.Foundation.BSTR pBstrNameLocal;
				winmdroot.Foundation.BSTR pBstrDocStringLocal;
				winmdroot.Foundation.BSTR pBstrHelpFileLocal;
				@this.GetDocumentation(memid, &pBstrNameLocal, &pBstrDocStringLocal, pdwHelpContextLocal, &pBstrHelpFileLocal);
				pBstrName = new SysFreeStringSafeHandle(pBstrNameLocal, ownsHandle: true);
				pBstrDocString = new SysFreeStringSafeHandle(pBstrDocStringLocal, ownsHandle: true);
				pBstrHelpFile = new SysFreeStringSafeHandle(pBstrHelpFileLocal, ownsHandle: true);
			}
		}

		/// <inheritdoc cref="winmdroot.System.Com.ITypeInfo.GetDllEntry(int, winmdroot.System.Com.INVOKEKIND, winmdroot.Foundation.BSTR*, winmdroot.Foundation.BSTR*, ushort*)"/>
		internal static unsafe void GetDllEntry(this winmdroot.System.Com.ITypeInfo @this, int memid, winmdroot.System.Com.INVOKEKIND invKind, out SysFreeStringSafeHandle pBstrDllName, out SysFreeStringSafeHandle pBstrName, out ushort pwOrdinal)
		{
			fixed (ushort* pwOrdinalLocal = &pwOrdinal)
			{
				winmdroot.Foundation.BSTR pBstrDllNameLocal;
				winmdroot.Foundation.BSTR pBstrNameLocal;
				@this.GetDllEntry(memid, invKind, &pBstrDllNameLocal, &pBstrNameLocal, pwOrdinalLocal);
				pBstrDllName = new SysFreeStringSafeHandle(pBstrDllNameLocal, ownsHandle: true);
				pBstrName = new SysFreeStringSafeHandle(pBstrNameLocal, ownsHandle: true);
			}
		}

		/// <inheritdoc cref="winmdroot.System.Com.ITypeInfo.AddressOfMember(int, winmdroot.System.Com.INVOKEKIND, void**)"/>
		internal static unsafe void AddressOfMember(this winmdroot.System.Com.ITypeInfo @this, int memid, winmdroot.System.Com.INVOKEKIND invKind, out void* ppv)
		{
			fixed (void** ppvLocal = &ppv)
			{
				@this.AddressOfMember(memid, invKind, ppvLocal);
			}
		}

		/// <inheritdoc cref="winmdroot.System.Com.ITypeInfo.CreateInstance(object, global::System.Guid*, out object)"/>
		internal static unsafe void CreateInstance(this winmdroot.System.Com.ITypeInfo @this, object pUnkOuter, in global::System.Guid riid, out object ppvObj)
		{
			fixed (global::System.Guid* riidLocal = &riid)
			{
				@this.CreateInstance(pUnkOuter, riidLocal, out ppvObj);
			}
		}

		/// <inheritdoc cref="winmdroot.System.Com.ITypeInfo.GetMops(int, winmdroot.Foundation.BSTR*)"/>
		internal static unsafe void GetMops(this winmdroot.System.Com.ITypeInfo @this, int memid, out SysFreeStringSafeHandle pBstrMops)
		{
			winmdroot.Foundation.BSTR pBstrMopsLocal;
			@this.GetMops(memid, &pBstrMopsLocal);
			pBstrMops = new SysFreeStringSafeHandle(pBstrMopsLocal, ownsHandle: true);
		}

		/// <inheritdoc cref="winmdroot.System.Com.ITypeInfo.GetContainingTypeLib(out winmdroot.System.Com.ITypeLib, uint*)"/>
		internal static unsafe void GetContainingTypeLib(this winmdroot.System.Com.ITypeInfo @this, out winmdroot.System.Com.ITypeLib ppTLib, out uint pIndex)
		{
			fixed (uint* pIndexLocal = &pIndex)
			{
				@this.GetContainingTypeLib(out ppTLib, pIndexLocal);
			}
		}

		/// <inheritdoc cref="winmdroot.System.Com.ITypeInfo.ReleaseTypeAttr(winmdroot.System.Com.TYPEATTR*)"/>
		internal static unsafe void ReleaseTypeAttr(this winmdroot.System.Com.ITypeInfo @this, in winmdroot.System.Com.TYPEATTR pTypeAttr)
		{
			fixed (winmdroot.System.Com.TYPEATTR* pTypeAttrLocal = &pTypeAttr)
			{
				@this.ReleaseTypeAttr(pTypeAttrLocal);
			}
		}
	}
}
