// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

#pragma warning disable CS1591,CS1573,CS0465,CS0649,CS8019,CS1570,CS1584,CS1658,CS0436,CS8981
using global::System;
using global::System.Diagnostics;
using global::System.Diagnostics.CodeAnalysis;
using global::System.Runtime.CompilerServices;
using global::System.Runtime.InteropServices;
using global::System.Runtime.Versioning;
using winmdroot = global::Windows.Win32;
namespace Windows.Win32
{
	[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.164-beta+187018bf44")]
	internal static partial class System_Com_ITypeLib_Extensions
	{
		/// <inheritdoc cref="winmdroot.System.Com.ITypeLib.GetTypeInfoType(uint, winmdroot.System.Com.TYPEKIND*)"/>
		internal static unsafe void GetTypeInfoType(this winmdroot.System.Com.ITypeLib @this, uint index, out winmdroot.System.Com.TYPEKIND pTKind)
		{
			fixed (winmdroot.System.Com.TYPEKIND* pTKindLocal = &pTKind)
			{
				@this.GetTypeInfoType(index, pTKindLocal);
			}
		}

		/// <inheritdoc cref="winmdroot.System.Com.ITypeLib.GetTypeInfoOfGuid(global::System.Guid*, out winmdroot.System.Com.ITypeInfo)"/>
		internal static unsafe void GetTypeInfoOfGuid(this winmdroot.System.Com.ITypeLib @this, in global::System.Guid guid, out winmdroot.System.Com.ITypeInfo ppTinfo)
		{
			fixed (global::System.Guid* guidLocal = &guid)
			{
				@this.GetTypeInfoOfGuid(guidLocal, out ppTinfo);
			}
		}

		/// <inheritdoc cref="winmdroot.System.Com.ITypeLib.GetLibAttr(winmdroot.System.Com.TLIBATTR**)"/>
		internal static unsafe void GetLibAttr(this winmdroot.System.Com.ITypeLib @this, out winmdroot.System.Com.TLIBATTR* ppTLibAttr)
		{
			fixed (winmdroot.System.Com.TLIBATTR** ppTLibAttrLocal = &ppTLibAttr)
			{
				@this.GetLibAttr(ppTLibAttrLocal);
			}
		}

		/// <inheritdoc cref="winmdroot.System.Com.ITypeLib.GetDocumentation(int, winmdroot.Foundation.BSTR*, winmdroot.Foundation.BSTR*, uint*, winmdroot.Foundation.BSTR*)"/>
		internal static unsafe void GetDocumentation(this winmdroot.System.Com.ITypeLib @this, int index, out SysFreeStringSafeHandle pBstrName, out SysFreeStringSafeHandle pBstrDocString, out uint pdwHelpContext, out SysFreeStringSafeHandle pBstrHelpFile)
		{
			fixed (uint* pdwHelpContextLocal = &pdwHelpContext)
			{
				winmdroot.Foundation.BSTR pBstrNameLocal;
				winmdroot.Foundation.BSTR pBstrDocStringLocal;
				winmdroot.Foundation.BSTR pBstrHelpFileLocal;
				@this.GetDocumentation(index, &pBstrNameLocal, &pBstrDocStringLocal, pdwHelpContextLocal, &pBstrHelpFileLocal);
				pBstrName = new SysFreeStringSafeHandle(pBstrNameLocal, ownsHandle: true);
				pBstrDocString = new SysFreeStringSafeHandle(pBstrDocStringLocal, ownsHandle: true);
				pBstrHelpFile = new SysFreeStringSafeHandle(pBstrHelpFileLocal, ownsHandle: true);
			}
		}

		/// <inheritdoc cref="winmdroot.System.Com.ITypeLib.IsName(winmdroot.Foundation.PWSTR, uint, winmdroot.Foundation.BOOL*)"/>
		internal static unsafe void IsName(this winmdroot.System.Com.ITypeLib @this, ref Span<char>szNameBuf, uint lHashVal, out winmdroot.Foundation.BOOL pfName)
		{
			if (szNameBuf.LastIndexOf('\0') == -1)throw new ArgumentException("Required null terminator missing.", "szNameBuf");
			fixed (winmdroot.Foundation.BOOL* pfNameLocal = &pfName)
			{
				fixed (char* pszNameBuf = szNameBuf)
				{
					winmdroot.Foundation.PWSTR wstrszNameBuf = pszNameBuf;
					@this.IsName(wstrszNameBuf, lHashVal, pfNameLocal);
					szNameBuf = szNameBuf.Slice(0, wstrszNameBuf.Length);
				}
			}
		}

		/// <inheritdoc cref="winmdroot.System.Com.ITypeLib.FindName(winmdroot.Foundation.PWSTR, uint, winmdroot.System.Com.ITypeInfo[], int*, ushort*)"/>
		internal static unsafe void FindName(this winmdroot.System.Com.ITypeLib @this, ref Span<char>szNameBuf, uint lHashVal, winmdroot.System.Com.ITypeInfo[] ppTInfo, int* rgMemId, ref ushort pcFound)
		{
			if (szNameBuf.LastIndexOf('\0') == -1)throw new ArgumentException("Required null terminator missing.", "szNameBuf");
			fixed (ushort* pcFoundLocal = &pcFound)
			{
				fixed (char* pszNameBuf = szNameBuf)
				{
					winmdroot.Foundation.PWSTR wstrszNameBuf = pszNameBuf;
					@this.FindName(wstrszNameBuf, lHashVal, ppTInfo, rgMemId, pcFoundLocal);
					szNameBuf = szNameBuf.Slice(0, wstrszNameBuf.Length);
				}
			}
		}

		/// <inheritdoc cref="winmdroot.System.Com.ITypeLib.ReleaseTLibAttr(winmdroot.System.Com.TLIBATTR*)"/>
		internal static unsafe void ReleaseTLibAttr(this winmdroot.System.Com.ITypeLib @this, in winmdroot.System.Com.TLIBATTR pTLibAttr)
		{
			fixed (winmdroot.System.Com.TLIBATTR* pTLibAttrLocal = &pTLibAttr)
			{
				@this.ReleaseTLibAttr(pTLibAttrLocal);
			}
		}
	}
}
