// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

#pragma warning disable CS1591,CS1573,CS0465,CS0649,CS8019,CS1570,CS1584,CS1658,CS0436,CS8981
using global::System;
using global::System.Diagnostics;
using global::System.Diagnostics.CodeAnalysis;
using global::System.Runtime.CompilerServices;
using global::System.Runtime.InteropServices;
using global::System.Runtime.Versioning;
using winmdroot = global::Windows.Win32;
namespace Windows.Win32
{
	[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.164-beta+187018bf44")]
	internal static partial class UI_Shell_IShellLinkW_Extensions
	{
		/// <inheritdoc cref="winmdroot.UI.Shell.IShellLinkW.GetPath(winmdroot.Foundation.PWSTR, int, winmdroot.Storage.FileSystem.WIN32_FIND_DATAW*, uint)"/>
		internal static unsafe void GetPath(this winmdroot.UI.Shell.IShellLinkW @this, winmdroot.Foundation.PWSTR pszFile, int cch, ref winmdroot.Storage.FileSystem.WIN32_FIND_DATAW pfd, uint fFlags)
		{
			fixed (winmdroot.Storage.FileSystem.WIN32_FIND_DATAW* pfdLocal = &pfd)
			{
				@this.GetPath(pszFile, cch, pfdLocal, fFlags);
			}
		}

		/// <inheritdoc cref="winmdroot.UI.Shell.IShellLinkW.GetIDList(winmdroot.UI.Shell.Common.ITEMIDLIST**)"/>
		internal static unsafe void GetIDList(this winmdroot.UI.Shell.IShellLinkW @this, out winmdroot.UI.Shell.Common.ITEMIDLIST* ppidl)
		{
			fixed (winmdroot.UI.Shell.Common.ITEMIDLIST** ppidlLocal = &ppidl)
			{
				@this.GetIDList(ppidlLocal);
			}
		}

		/// <inheritdoc cref="winmdroot.UI.Shell.IShellLinkW.SetIDList(winmdroot.UI.Shell.Common.ITEMIDLIST*)"/>
		internal static unsafe void SetIDList(this winmdroot.UI.Shell.IShellLinkW @this, in winmdroot.UI.Shell.Common.ITEMIDLIST pidl)
		{
			fixed (winmdroot.UI.Shell.Common.ITEMIDLIST* pidlLocal = &pidl)
			{
				@this.SetIDList(pidlLocal);
			}
		}

		/// <inheritdoc cref="winmdroot.UI.Shell.IShellLinkW.SetDescription(winmdroot.Foundation.PCWSTR)"/>
		internal static unsafe void SetDescription(this winmdroot.UI.Shell.IShellLinkW @this, string pszName)
		{
			fixed (char* pszNameLocal = pszName)
			{
				@this.SetDescription(pszNameLocal);
			}
		}

		/// <inheritdoc cref="winmdroot.UI.Shell.IShellLinkW.SetWorkingDirectory(winmdroot.Foundation.PCWSTR)"/>
		internal static unsafe void SetWorkingDirectory(this winmdroot.UI.Shell.IShellLinkW @this, string pszDir)
		{
			fixed (char* pszDirLocal = pszDir)
			{
				@this.SetWorkingDirectory(pszDirLocal);
			}
		}

		/// <inheritdoc cref="winmdroot.UI.Shell.IShellLinkW.SetArguments(winmdroot.Foundation.PCWSTR)"/>
		internal static unsafe void SetArguments(this winmdroot.UI.Shell.IShellLinkW @this, string pszArgs)
		{
			fixed (char* pszArgsLocal = pszArgs)
			{
				@this.SetArguments(pszArgsLocal);
			}
		}

		/// <inheritdoc cref="winmdroot.UI.Shell.IShellLinkW.GetHotkey(ushort*)"/>
		internal static unsafe void GetHotkey(this winmdroot.UI.Shell.IShellLinkW @this, out ushort pwHotkey)
		{
			fixed (ushort* pwHotkeyLocal = &pwHotkey)
			{
				@this.GetHotkey(pwHotkeyLocal);
			}
		}

		/// <inheritdoc cref="winmdroot.UI.Shell.IShellLinkW.GetShowCmd(int*)"/>
		internal static unsafe void GetShowCmd(this winmdroot.UI.Shell.IShellLinkW @this, out int piShowCmd)
		{
			fixed (int* piShowCmdLocal = &piShowCmd)
			{
				@this.GetShowCmd(piShowCmdLocal);
			}
		}

		/// <inheritdoc cref="winmdroot.UI.Shell.IShellLinkW.GetIconLocation(winmdroot.Foundation.PWSTR, int, int*)"/>
		internal static unsafe void GetIconLocation(this winmdroot.UI.Shell.IShellLinkW @this, winmdroot.Foundation.PWSTR pszIconPath, int cch, out int piIcon)
		{
			fixed (int* piIconLocal = &piIcon)
			{
				@this.GetIconLocation(pszIconPath, cch, piIconLocal);
			}
		}

		/// <inheritdoc cref="winmdroot.UI.Shell.IShellLinkW.SetIconLocation(winmdroot.Foundation.PCWSTR, int)"/>
		internal static unsafe void SetIconLocation(this winmdroot.UI.Shell.IShellLinkW @this, string pszIconPath, int iIcon)
		{
			fixed (char* pszIconPathLocal = pszIconPath)
			{
				@this.SetIconLocation(pszIconPathLocal, iIcon);
			}
		}

		/// <inheritdoc cref="winmdroot.UI.Shell.IShellLinkW.SetRelativePath(winmdroot.Foundation.PCWSTR, uint)"/>
		internal static unsafe void SetRelativePath(this winmdroot.UI.Shell.IShellLinkW @this, string pszPathRel, uint dwReserved)
		{
			fixed (char* pszPathRelLocal = pszPathRel)
			{
				@this.SetRelativePath(pszPathRelLocal, dwReserved);
			}
		}

		/// <inheritdoc cref="winmdroot.UI.Shell.IShellLinkW.SetPath(winmdroot.Foundation.PCWSTR)"/>
		internal static unsafe void SetPath(this winmdroot.UI.Shell.IShellLinkW @this, string pszFile)
		{
			fixed (char* pszFileLocal = pszFile)
			{
				@this.SetPath(pszFileLocal);
			}
		}
	}
}
