// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

#pragma warning disable CS1591,CS1573,CS0465,CS0649,CS8019,CS1570,CS1584,CS1658,CS0436,CS8981
using global::System;
using global::System.Diagnostics;
using global::System.Diagnostics.CodeAnalysis;
using global::System.Runtime.CompilerServices;
using global::System.Runtime.InteropServices;
using global::System.Runtime.Versioning;
using winmdroot = global::Windows.Win32;
namespace Windows.Win32
{
	namespace System.Com
	{
		/// <summary>Specifies a type.</summary>
		/// <remarks>
		/// <para><see href="https://docs.microsoft.com/windows/win32/api//oaidl/ne-oaidl-typekind">Learn more about this API from docs.microsoft.com</see>.</para>
		/// </remarks>
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.164-beta+187018bf44")]
		internal enum TYPEKIND
		{
			/// <summary>A set of enumerators.</summary>
			TKIND_ENUM = 0,
			/// <summary>A structure with no methods.</summary>
			TKIND_RECORD = 1,
			/// <summary>A module that can only have static functions and data (for example, a DLL).</summary>
			TKIND_MODULE = 2,
			/// <summary>A type that has virtual and pure functions.</summary>
			TKIND_INTERFACE = 3,
			/// <summary>A set of methods and properties that are accessible through <a href="https://docs.microsoft.com/previous-versions/windows/desktop/api/oaidl/nf-oaidl-idispatch-invoke">IDispatch::Invoke</a>. By default, dual interfaces return TKIND_DISPATCH.</summary>
			TKIND_DISPATCH = 4,
			/// <summary>A set of implemented component object interfaces.</summary>
			TKIND_COCLASS = 5,
			/// <summary>A type that is an alias for another type.</summary>
			TKIND_ALIAS = 6,
			/// <summary>A union, all of whose members have an offset of zero.</summary>
			TKIND_UNION = 7,
			/// <summary>End of enum marker.</summary>
			TKIND_MAX = 8,
		}
	}
}
