// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

#pragma warning disable CS1591,CS1573,CS0465,CS0649,CS8019,CS1570,CS1584,CS1658,CS0436,CS8981
using global::System;
using global::System.Diagnostics;
using global::System.Diagnostics.CodeAnalysis;
using global::System.Runtime.CompilerServices;
using global::System.Runtime.InteropServices;
using global::System.Runtime.Versioning;
using winmdroot = global::Windows.Win32;
namespace Windows.Win32
{
	namespace System.Com.StructuredStorage
	{
		[Guid("0000000B-0000-0000-C000-000000000046")]
		[SupportedOSPlatform("windows5.0")]
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.164-beta+187018bf44")]
		internal unsafe partial struct IStorage_unmanaged
			:IComIID		{
			/// <inheritdoc cref="QueryInterface(global::System.Guid*, out object)"/>
			internal unsafe winmdroot.Foundation.HRESULT QueryInterface(in global::System.Guid riid, out object ppvObject)
			{
				fixed (global::System.Guid* riidLocal = &riid)
				{
					winmdroot.Foundation.HRESULT __result = this.QueryInterface(riidLocal, out ppvObject);
					return __result;
				}
			}

			public unsafe winmdroot.Foundation.HRESULT QueryInterface(global::System.Guid* riid, [MarshalAs(UnmanagedType.IUnknown)] out object ppvObject)
			{
				fixed (IStorage_unmanaged* pThis = &this)
					return ((delegate *unmanaged [Stdcall]<IStorage_unmanaged*,global::System.Guid* ,out object ,winmdroot.Foundation.HRESULT>)lpVtbl[0])(pThis, riid, out ppvObject);
			}

			public uint AddRef()
			{
				fixed (IStorage_unmanaged* pThis = &this)
					return ((delegate *unmanaged [Stdcall]<IStorage_unmanaged*,uint>)lpVtbl[1])(pThis);
			}

			public uint Release()
			{
				fixed (IStorage_unmanaged* pThis = &this)
					return ((delegate *unmanaged [Stdcall]<IStorage_unmanaged*,uint>)lpVtbl[2])(pThis);
			}

			/// <inheritdoc cref="CreateStream(winmdroot.Foundation.PCWSTR, winmdroot.System.Com.STGM, uint, uint, out winmdroot.System.Com.IStream)"/>
			internal unsafe void CreateStream(string pwcsName, winmdroot.System.Com.STGM grfMode, uint reserved1, uint reserved2, out winmdroot.System.Com.IStream ppstm)
			{
				fixed (char* pwcsNameLocal = pwcsName)
				{
					this.CreateStream(pwcsNameLocal, grfMode, reserved1, reserved2, out ppstm);
				}
			}

			public void CreateStream(winmdroot.Foundation.PCWSTR pwcsName, winmdroot.System.Com.STGM grfMode, uint reserved1, uint reserved2, out winmdroot.System.Com.IStream ppstm)
			{
				fixed (IStorage_unmanaged* pThis = &this)
					((delegate *unmanaged [Stdcall]<IStorage_unmanaged*,winmdroot.Foundation.PCWSTR ,winmdroot.System.Com.STGM ,uint ,uint ,out winmdroot.System.Com.IStream ,winmdroot.Foundation.HRESULT>)lpVtbl[3])(pThis, pwcsName, grfMode, reserved1, reserved2, out ppstm).ThrowOnFailure();
			}

			/// <inheritdoc cref="OpenStream(winmdroot.Foundation.PCWSTR, void*, winmdroot.System.Com.STGM, uint, out winmdroot.System.Com.IStream)"/>
			internal unsafe void OpenStream(string pwcsName, void* reserved1, winmdroot.System.Com.STGM grfMode, uint reserved2, out winmdroot.System.Com.IStream ppstm)
			{
				fixed (char* pwcsNameLocal = pwcsName)
				{
					this.OpenStream(pwcsNameLocal, reserved1, grfMode, reserved2, out ppstm);
				}
			}

			public unsafe void OpenStream(winmdroot.Foundation.PCWSTR pwcsName, void* reserved1, winmdroot.System.Com.STGM grfMode, uint reserved2, out winmdroot.System.Com.IStream ppstm)
			{
				fixed (IStorage_unmanaged* pThis = &this)
					((delegate *unmanaged [Stdcall]<IStorage_unmanaged*,winmdroot.Foundation.PCWSTR ,void* ,winmdroot.System.Com.STGM ,uint ,out winmdroot.System.Com.IStream ,winmdroot.Foundation.HRESULT>)lpVtbl[4])(pThis, pwcsName, reserved1, grfMode, reserved2, out ppstm).ThrowOnFailure();
			}

			/// <inheritdoc cref="CreateStorage(winmdroot.Foundation.PCWSTR, winmdroot.System.Com.STGM, uint, uint, out winmdroot.System.Com.StructuredStorage.IStorage)"/>
			internal unsafe void CreateStorage(string pwcsName, winmdroot.System.Com.STGM grfMode, uint reserved1, uint reserved2, out winmdroot.System.Com.StructuredStorage.IStorage ppstg)
			{
				fixed (char* pwcsNameLocal = pwcsName)
				{
					this.CreateStorage(pwcsNameLocal, grfMode, reserved1, reserved2, out ppstg);
				}
			}

			public void CreateStorage(winmdroot.Foundation.PCWSTR pwcsName, winmdroot.System.Com.STGM grfMode, uint reserved1, uint reserved2, out winmdroot.System.Com.StructuredStorage.IStorage ppstg)
			{
				fixed (IStorage_unmanaged* pThis = &this)
					((delegate *unmanaged [Stdcall]<IStorage_unmanaged*,winmdroot.Foundation.PCWSTR ,winmdroot.System.Com.STGM ,uint ,uint ,out winmdroot.System.Com.StructuredStorage.IStorage ,winmdroot.Foundation.HRESULT>)lpVtbl[5])(pThis, pwcsName, grfMode, reserved1, reserved2, out ppstg).ThrowOnFailure();
			}

			/// <inheritdoc cref="OpenStorage(winmdroot.Foundation.PCWSTR, winmdroot.System.Com.StructuredStorage.IStorage, winmdroot.System.Com.STGM, ushort**, uint, out winmdroot.System.Com.StructuredStorage.IStorage)"/>
			internal unsafe void OpenStorage(string pwcsName, winmdroot.System.Com.StructuredStorage.IStorage pstgPriority, winmdroot.System.Com.STGM grfMode, in ushort* snbExclude, uint reserved, out winmdroot.System.Com.StructuredStorage.IStorage ppstg)
			{
				fixed (ushort** snbExcludeLocal = &snbExclude)
				{
					fixed (char* pwcsNameLocal = pwcsName)
					{
						this.OpenStorage(pwcsNameLocal, pstgPriority, grfMode, snbExcludeLocal, reserved, out ppstg);
					}
				}
			}

			public unsafe void OpenStorage(winmdroot.Foundation.PCWSTR pwcsName, winmdroot.System.Com.StructuredStorage.IStorage pstgPriority, winmdroot.System.Com.STGM grfMode, ushort** snbExclude, uint reserved, out winmdroot.System.Com.StructuredStorage.IStorage ppstg)
			{
				fixed (IStorage_unmanaged* pThis = &this)
					((delegate *unmanaged [Stdcall]<IStorage_unmanaged*,winmdroot.Foundation.PCWSTR ,winmdroot.System.Com.StructuredStorage.IStorage ,winmdroot.System.Com.STGM ,ushort** ,uint ,out winmdroot.System.Com.StructuredStorage.IStorage ,winmdroot.Foundation.HRESULT>)lpVtbl[6])(pThis, pwcsName, pstgPriority, grfMode, snbExclude, reserved, out ppstg).ThrowOnFailure();
			}

			/// <inheritdoc cref="CopyTo(uint, global::System.Guid*, ushort**, winmdroot.System.Com.StructuredStorage.IStorage)"/>
			internal unsafe void CopyTo(ReadOnlySpan<global::System.Guid> rgiidExclude, ushort** snbExclude, winmdroot.System.Com.StructuredStorage.IStorage pstgDest)
			{
				fixed (global::System.Guid* rgiidExcludeLocal = rgiidExclude)
				{
					this.CopyTo((uint )rgiidExclude.Length, rgiidExcludeLocal, snbExclude, pstgDest);
				}
			}

			public unsafe void CopyTo(uint ciidExclude, [Optional] global::System.Guid* rgiidExclude, [Optional] ushort** snbExclude, winmdroot.System.Com.StructuredStorage.IStorage pstgDest)
			{
				fixed (IStorage_unmanaged* pThis = &this)
					((delegate *unmanaged [Stdcall]<IStorage_unmanaged*,uint ,global::System.Guid* ,ushort** ,winmdroot.System.Com.StructuredStorage.IStorage ,winmdroot.Foundation.HRESULT>)lpVtbl[7])(pThis, ciidExclude, rgiidExclude, snbExclude, pstgDest).ThrowOnFailure();
			}

			/// <inheritdoc cref="MoveElementTo(winmdroot.Foundation.PCWSTR, winmdroot.System.Com.StructuredStorage.IStorage, winmdroot.Foundation.PCWSTR, winmdroot.System.Com.StructuredStorage.STGMOVE)"/>
			internal unsafe void MoveElementTo(string pwcsName, winmdroot.System.Com.StructuredStorage.IStorage pstgDest, string pwcsNewName, winmdroot.System.Com.StructuredStorage.STGMOVE grfFlags)
			{
				fixed (char* pwcsNewNameLocal = pwcsNewName)
				{
					fixed (char* pwcsNameLocal = pwcsName)
					{
						this.MoveElementTo(pwcsNameLocal, pstgDest, pwcsNewNameLocal, grfFlags);
					}
				}
			}

			public void MoveElementTo(winmdroot.Foundation.PCWSTR pwcsName, winmdroot.System.Com.StructuredStorage.IStorage pstgDest, winmdroot.Foundation.PCWSTR pwcsNewName, winmdroot.System.Com.StructuredStorage.STGMOVE grfFlags)
			{
				fixed (IStorage_unmanaged* pThis = &this)
					((delegate *unmanaged [Stdcall]<IStorage_unmanaged*,winmdroot.Foundation.PCWSTR ,winmdroot.System.Com.StructuredStorage.IStorage ,winmdroot.Foundation.PCWSTR ,winmdroot.System.Com.StructuredStorage.STGMOVE ,winmdroot.Foundation.HRESULT>)lpVtbl[8])(pThis, pwcsName, pstgDest, pwcsNewName, grfFlags).ThrowOnFailure();
			}

			public void Commit(winmdroot.System.Com.STGC grfCommitFlags)
			{
				fixed (IStorage_unmanaged* pThis = &this)
					((delegate *unmanaged [Stdcall]<IStorage_unmanaged*,winmdroot.System.Com.STGC ,winmdroot.Foundation.HRESULT>)lpVtbl[9])(pThis, grfCommitFlags).ThrowOnFailure();
			}

			public void Revert()
			{
				fixed (IStorage_unmanaged* pThis = &this)
					((delegate *unmanaged [Stdcall]<IStorage_unmanaged*,winmdroot.Foundation.HRESULT>)lpVtbl[10])(pThis).ThrowOnFailure();
			}

			public unsafe void EnumElements(uint reserved1, void* reserved2, uint reserved3, out winmdroot.System.Com.StructuredStorage.IEnumSTATSTG ppenum)
			{
				fixed (IStorage_unmanaged* pThis = &this)
					((delegate *unmanaged [Stdcall]<IStorage_unmanaged*,uint ,void* ,uint ,out winmdroot.System.Com.StructuredStorage.IEnumSTATSTG ,winmdroot.Foundation.HRESULT>)lpVtbl[11])(pThis, reserved1, reserved2, reserved3, out ppenum).ThrowOnFailure();
			}

			/// <inheritdoc cref="DestroyElement(winmdroot.Foundation.PCWSTR)"/>
			internal unsafe void DestroyElement(string pwcsName)
			{
				fixed (char* pwcsNameLocal = pwcsName)
				{
					this.DestroyElement(pwcsNameLocal);
				}
			}

			public void DestroyElement(winmdroot.Foundation.PCWSTR pwcsName)
			{
				fixed (IStorage_unmanaged* pThis = &this)
					((delegate *unmanaged [Stdcall]<IStorage_unmanaged*,winmdroot.Foundation.PCWSTR ,winmdroot.Foundation.HRESULT>)lpVtbl[12])(pThis, pwcsName).ThrowOnFailure();
			}

			/// <inheritdoc cref="RenameElement(winmdroot.Foundation.PCWSTR, winmdroot.Foundation.PCWSTR)"/>
			internal unsafe void RenameElement(string pwcsOldName, string pwcsNewName)
			{
				fixed (char* pwcsNewNameLocal = pwcsNewName)
				{
					fixed (char* pwcsOldNameLocal = pwcsOldName)
					{
						this.RenameElement(pwcsOldNameLocal, pwcsNewNameLocal);
					}
				}
			}

			public void RenameElement(winmdroot.Foundation.PCWSTR pwcsOldName, winmdroot.Foundation.PCWSTR pwcsNewName)
			{
				fixed (IStorage_unmanaged* pThis = &this)
					((delegate *unmanaged [Stdcall]<IStorage_unmanaged*,winmdroot.Foundation.PCWSTR ,winmdroot.Foundation.PCWSTR ,winmdroot.Foundation.HRESULT>)lpVtbl[13])(pThis, pwcsOldName, pwcsNewName).ThrowOnFailure();
			}

			/// <inheritdoc cref="SetElementTimes(winmdroot.Foundation.PCWSTR, global::System.Runtime.InteropServices.ComTypes.FILETIME*, global::System.Runtime.InteropServices.ComTypes.FILETIME*, global::System.Runtime.InteropServices.ComTypes.FILETIME*)"/>
			internal unsafe void SetElementTimes(string pwcsName, in global::System.Runtime.InteropServices.ComTypes.FILETIME pctime, in global::System.Runtime.InteropServices.ComTypes.FILETIME patime, in global::System.Runtime.InteropServices.ComTypes.FILETIME pmtime)
			{
				fixed (global::System.Runtime.InteropServices.ComTypes.FILETIME* pmtimeLocal = &pmtime)
				{
					fixed (global::System.Runtime.InteropServices.ComTypes.FILETIME* patimeLocal = &patime)
					{
						fixed (global::System.Runtime.InteropServices.ComTypes.FILETIME* pctimeLocal = &pctime)
						{
							fixed (char* pwcsNameLocal = pwcsName)
							{
								this.SetElementTimes(pwcsNameLocal, pctimeLocal, patimeLocal, pmtimeLocal);
							}
						}
					}
				}
			}

			public unsafe void SetElementTimes(winmdroot.Foundation.PCWSTR pwcsName, global::System.Runtime.InteropServices.ComTypes.FILETIME* pctime, global::System.Runtime.InteropServices.ComTypes.FILETIME* patime, global::System.Runtime.InteropServices.ComTypes.FILETIME* pmtime)
			{
				fixed (IStorage_unmanaged* pThis = &this)
					((delegate *unmanaged [Stdcall]<IStorage_unmanaged*,winmdroot.Foundation.PCWSTR ,global::System.Runtime.InteropServices.ComTypes.FILETIME* ,global::System.Runtime.InteropServices.ComTypes.FILETIME* ,global::System.Runtime.InteropServices.ComTypes.FILETIME* ,winmdroot.Foundation.HRESULT>)lpVtbl[14])(pThis, pwcsName, pctime, patime, pmtime).ThrowOnFailure();
			}

			/// <inheritdoc cref="SetClass(global::System.Guid*)"/>
			internal unsafe void SetClass(in global::System.Guid clsid)
			{
				fixed (global::System.Guid* clsidLocal = &clsid)
				{
					this.SetClass(clsidLocal);
				}
			}

			public unsafe void SetClass(global::System.Guid* clsid)
			{
				fixed (IStorage_unmanaged* pThis = &this)
					((delegate *unmanaged [Stdcall]<IStorage_unmanaged*,global::System.Guid* ,winmdroot.Foundation.HRESULT>)lpVtbl[15])(pThis, clsid).ThrowOnFailure();
			}

			public void SetStateBits(uint grfStateBits, uint grfMask)
			{
				fixed (IStorage_unmanaged* pThis = &this)
					((delegate *unmanaged [Stdcall]<IStorage_unmanaged*,uint ,uint ,winmdroot.Foundation.HRESULT>)lpVtbl[16])(pThis, grfStateBits, grfMask).ThrowOnFailure();
			}

			/// <inheritdoc cref="Stat(winmdroot.System.Com.STATSTG*, winmdroot.System.Com.STATFLAG)"/>
			internal unsafe void Stat(out winmdroot.System.Com.STATSTG pstatstg, winmdroot.System.Com.STATFLAG grfStatFlag)
			{
				fixed (winmdroot.System.Com.STATSTG* pstatstgLocal = &pstatstg)
				{
					this.Stat(pstatstgLocal, grfStatFlag);
				}
			}

			public unsafe void Stat(winmdroot.System.Com.STATSTG* pstatstg, winmdroot.System.Com.STATFLAG grfStatFlag)
			{
				fixed (IStorage_unmanaged* pThis = &this)
					((delegate *unmanaged [Stdcall]<IStorage_unmanaged*,winmdroot.System.Com.STATSTG* ,winmdroot.System.Com.STATFLAG ,winmdroot.Foundation.HRESULT>)lpVtbl[17])(pThis, pstatstg, grfStatFlag).ThrowOnFailure();
			}
			private void** lpVtbl;
			/// <summary>The IID guid for this interface.</summary>
			/// <value>{0000000b-0000-0000-c000-000000000046}</value>
			internal static readonly Guid IID_Guid = new Guid(0x0000000B, 0x0000, 0x0000, 0xC0, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x46);

			static ref readonly Guid IComIID.Guid			{
								[MethodImpl(MethodImplOptions.AggressiveInlining)]
get
				{
					ReadOnlySpan<byte> data = new byte[]					{
0x0B,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0xC0,0x00,0x00,0x00,0x00,0x00,0x00,0x46					};
					return ref Unsafe.As<byte,Guid>(ref MemoryMarshal.GetReference(data));
				}
			}
		}
	}
}
