// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

#pragma warning disable CS1591,CS1573,CS0465,CS0649,CS8019,CS1570,CS1584,CS1658,CS0436,CS8981
using global::System;
using global::System.Diagnostics;
using global::System.Diagnostics.CodeAnalysis;
using global::System.Runtime.CompilerServices;
using global::System.Runtime.InteropServices;
using global::System.Runtime.Versioning;
using winmdroot = global::Windows.Win32;
namespace Windows.Win32
{
	namespace System.Com
	{
		/// <summary>Specifies the variant types.</summary>
		/// <remarks>
		/// <para>The following table shows where these values can be used. </para>
		/// <para>This doc was truncated.</para>
		/// <para><see href="https://docs.microsoft.com/windows/win32/api//wtypes/ne-wtypes-varenum#">Read more on docs.microsoft.com</see>.</para>
		/// </remarks>
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.164-beta+187018bf44")]
		internal enum VARENUM : ushort
		{
			/// <summary>Not specified.</summary>
			VT_EMPTY = 0,
			/// <summary>Null.</summary>
			VT_NULL = 1,
			/// <summary>A 2-byte integer.</summary>
			VT_I2 = 2,
			/// <summary>A 4-byte integer.</summary>
			VT_I4 = 3,
			/// <summary>A 4-byte real.</summary>
			VT_R4 = 4,
			/// <summary>An 8-byte real.</summary>
			VT_R8 = 5,
			/// <summary>Currency.</summary>
			VT_CY = 6,
			/// <summary>A date.</summary>
			VT_DATE = 7,
			/// <summary>A string.</summary>
			VT_BSTR = 8,
			/// <summary>An <a href="https://docs.microsoft.com/previous-versions/windows/desktop/api/oaidl/nn-oaidl-idispatch">IDispatch</a> pointer.</summary>
			VT_DISPATCH = 9,
			/// <summary>An SCODE value.</summary>
			VT_ERROR = 10,
			/// <summary>A Boolean value. True is -1 and false is 0.</summary>
			VT_BOOL = 11,
			/// <summary>A variant pointer.</summary>
			VT_VARIANT = 12,
			/// <summary>An <a href="https://docs.microsoft.com/windows/desktop/api/unknwn/nn-unknwn-iunknown">IUnknown</a> pointer.</summary>
			VT_UNKNOWN = 13,
			/// <summary>A 16-byte fixed-pointer value.</summary>
			VT_DECIMAL = 14,
			/// <summary>A character.</summary>
			VT_I1 = 16,
			/// <summary>An unsigned character.</summary>
			VT_UI1 = 17,
			/// <summary>An unsigned short.</summary>
			VT_UI2 = 18,
			/// <summary>An unsigned long.</summary>
			VT_UI4 = 19,
			/// <summary>A 64-bit integer.</summary>
			VT_I8 = 20,
			/// <summary>A 64-bit unsigned integer.</summary>
			VT_UI8 = 21,
			/// <summary>An integer.</summary>
			VT_INT = 22,
			/// <summary>An unsigned integer.</summary>
			VT_UINT = 23,
			/// <summary>A C-style void.</summary>
			VT_VOID = 24,
			/// <summary>An HRESULT value.</summary>
			VT_HRESULT = 25,
			/// <summary>A pointer type.</summary>
			VT_PTR = 26,
			/// <summary>A safe array. Use VT_ARRAY in VARIANT.</summary>
			VT_SAFEARRAY = 27,
			/// <summary>A C-style array.</summary>
			VT_CARRAY = 28,
			/// <summary>A user-defined type.</summary>
			VT_USERDEFINED = 29,
			/// <summary>A null-terminated string.</summary>
			VT_LPSTR = 30,
			/// <summary>A wide null-terminated string.</summary>
			VT_LPWSTR = 31,
			/// <summary>A user-defined type.</summary>
			VT_RECORD = 36,
			/// <summary>A signed machine register size width.</summary>
			VT_INT_PTR = 37,
			/// <summary>An unsigned machine register size width.</summary>
			VT_UINT_PTR = 38,
			/// <summary>A <a href="https://docs.microsoft.com/windows/desktop/api/minwinbase/ns-minwinbase-filetime">FILETIME</a> value.</summary>
			VT_FILETIME = 64,
			/// <summary>Length-prefixed bytes.</summary>
			VT_BLOB = 65,
			/// <summary>The name of the stream follows.</summary>
			VT_STREAM = 66,
			/// <summary>The name of the storage follows.</summary>
			VT_STORAGE = 67,
			/// <summary>The stream contains an object.</summary>
			VT_STREAMED_OBJECT = 68,
			/// <summary>The storage contains an object.</summary>
			VT_STORED_OBJECT = 69,
			/// <summary>The blob contains an object.</summary>
			VT_BLOB_OBJECT = 70,
			/// <summary>A clipboard format.</summary>
			VT_CF = 71,
			/// <summary>A class ID.</summary>
			VT_CLSID = 72,
			/// <summary>A stream with a GUID version.</summary>
			VT_VERSIONED_STREAM = 73,
			/// <summary>Reserved.</summary>
			VT_BSTR_BLOB = 4095,
			/// <summary>A simple counted array.</summary>
			VT_VECTOR = 4096,
			/// <summary>A SAFEARRAY pointer.</summary>
			VT_ARRAY = 8192,
			/// <summary>A void pointer for local use.</summary>
			VT_BYREF = 16384,
			/// <summary></summary>
			VT_RESERVED = 32768,
			/// <summary></summary>
			VT_ILLEGAL = 65535,
			/// <summary></summary>
			VT_ILLEGALMASKED = 4095,
			/// <summary></summary>
			VT_TYPEMASK = 4095,
		}
	}
}
