// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

#pragma warning disable CS1591,CS1573,CS0465,CS0649,CS8019,CS1570,CS1584,CS1658,CS0436,CS8981
using global::System;
using global::System.Diagnostics;
using global::System.Diagnostics.CodeAnalysis;
using global::System.Runtime.CompilerServices;
using global::System.Runtime.InteropServices;
using global::System.Runtime.Versioning;
using winmdroot = global::Windows.Win32;
namespace Windows.Win32
{
	namespace System.Ole
	{
		[Guid("0000002F-0000-0000-C000-000000000046"),InterfaceType(ComInterfaceType.InterfaceIsIUnknown),ComImport()]
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.164-beta+187018bf44")]
		internal interface IRecordInfo
		{
			/// <summary>Initializes a new instance of a record.</summary>
			/// <param name="pvNew">An instance of a record.</param>
			/// <returns>
			/// <para>This method can return one of these values. </para>
			/// <para>This doc was truncated.</para>
			/// </returns>
			/// <remarks>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//oaidl/nf-oaidl-irecordinfo-recordinit">Learn more about this API from docs.microsoft.com</see>.</para>
			/// </remarks>
			unsafe void RecordInit(void* pvNew);

			/// <summary>Releases object references and other values of a record without deallocating the record.</summary>
			/// <param name="pvExisting">The record to be cleared.</param>
			/// <returns>
			/// <para>This method can return one of these values. </para>
			/// <para>This doc was truncated.</para>
			/// </returns>
			/// <remarks>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//oaidl/nf-oaidl-irecordinfo-recordclear">Learn more about this API from docs.microsoft.com</see>.</para>
			/// </remarks>
			unsafe void RecordClear(void* pvExisting);

			/// <summary>Copies an existing record into the passed in buffer.</summary>
			/// <param name="pvExisting">The current record instance.</param>
			/// <param name="pvNew">The destination where the record will be copied.</param>
			/// <returns>
			/// <para>This method can return one of these values. </para>
			/// <para>This doc was truncated.</para>
			/// </returns>
			/// <remarks>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//oaidl/nf-oaidl-irecordinfo-recordcopy">Learn more about this API from docs.microsoft.com</see>.</para>
			/// </remarks>
			unsafe void RecordCopy(void* pvExisting, void* pvNew);

			/// <summary>Gets the GUID of the record type.</summary>
			/// <param name="pguid">The class GUID of the TypeInfo that describes the UDT.</param>
			/// <returns>
			/// <para>This method can return one of these values. </para>
			/// <para>This doc was truncated.</para>
			/// </returns>
			/// <remarks>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//oaidl/nf-oaidl-irecordinfo-getguid">Learn more about this API from docs.microsoft.com</see>.</para>
			/// </remarks>
			unsafe void GetGuid(global::System.Guid* pguid);

			/// <summary>Gets the name of the record type.</summary>
			/// <param name="pbstrName">The name.</param>
			/// <returns>
			/// <para>This method can return one of these values. </para>
			/// <para>This doc was truncated.</para>
			/// </returns>
			/// <remarks>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//oaidl/nf-oaidl-irecordinfo-getname">Learn more about this API from docs.microsoft.com</see>.</para>
			/// </remarks>
			unsafe void GetName(winmdroot.Foundation.BSTR* pbstrName);

			/// <summary>Gets the number of bytes of memory necessary to hold the record instance.</summary>
			/// <param name="pcbSize">The size of a record instance, in bytes.</param>
			/// <returns>
			/// <para>This method can return one of these values. </para>
			/// <para>This doc was truncated.</para>
			/// </returns>
			/// <remarks>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//oaidl/nf-oaidl-irecordinfo-getsize">Learn more about this API from docs.microsoft.com</see>.</para>
			/// </remarks>
			unsafe void GetSize(uint* pcbSize);

			/// <summary>Retrieves the type information that describes a UDT or safearray of UDTs.</summary>
			/// <param name="ppTypeInfo">The information type of the record.</param>
			/// <returns>
			/// <para>This method can return one of these values. </para>
			/// <para>This doc was truncated.</para>
			/// </returns>
			/// <remarks>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//oaidl/nf-oaidl-irecordinfo-gettypeinfo">Learn more about this API from docs.microsoft.com</see>.</para>
			/// </remarks>
			void GetTypeInfo(out winmdroot.System.Com.ITypeInfo ppTypeInfo);

			/// <summary>Returns a pointer to the VARIANT containing the value of a given field name.</summary>
			/// <param name="pvData">The instance of a record.</param>
			/// <param name="szFieldName">The field name.</param>
			/// <param name="pvarField">The VARIANT that you want to hold the value of the field name, <i>szFieldName</i>. On return, places a copy of the field's value in the variant.</param>
			/// <returns>
			/// <para>This method can return one of these values. </para>
			/// <para>This doc was truncated.</para>
			/// </returns>
			/// <remarks>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//oaidl/nf-oaidl-irecordinfo-getfield">Learn more about this API from docs.microsoft.com</see>.</para>
			/// </remarks>
			unsafe void GetField(void* pvData, winmdroot.Foundation.PCWSTR szFieldName, [MarshalAs(UnmanagedType.Struct)] out object pvarField);

			/// <summary>Returns a pointer to the value of a given field name without copying the value and allocating resources.</summary>
			/// <param name="pvData">The instance of a record.</param>
			/// <param name="szFieldName">The name of the field.</param>
			/// <param name="pvarField">The VARIANT that will contain the UDT upon return.</param>
			/// <param name="ppvDataCArray">Receives the value of the field upon return.</param>
			/// <returns>
			/// <para>This method can return one of these values. </para>
			/// <para>This doc was truncated.</para>
			/// </returns>
			/// <remarks>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//oaidl/nf-oaidl-irecordinfo-getfieldnocopy">Learn more about this API from docs.microsoft.com</see>.</para>
			/// </remarks>
			unsafe void GetFieldNoCopy(void* pvData, winmdroot.Foundation.PCWSTR szFieldName, [MarshalAs(UnmanagedType.Struct)] out object pvarField, void** ppvDataCArray);

			/// <summary>Puts a variant into a field.</summary>
			/// <param name="wFlags">
			/// <para>The only legal values for the wFlags parameter is INVOKE_PROPERTYPUT or INVOKE_PROPERTYPUTREF. If INVOKE_PROPERTYPUTREF is passed in then <b>PutField</b> just assigns the value of the variant that is passed in to the field using normal coercion rules. If INVOKE_PROPERTYPUT is passed in then specific rules apply. If the field is declared as a class that derives from <a href="https://docs.microsoft.com/previous-versions/windows/desktop/api/oaidl/nn-oaidl-idispatch">IDispatch</a> and the field's value is NULL then an error will be returned. If the field's value is not NULL then the variant will be passed to the default property supported by the object referenced by the field. If the field is not declared as a class derived from <b>IDispatch</b> then an error will be returned. If the field is declared as a variant of type VT_Dispatch then the default value of the object is assigned to the field. Otherwise, the variant's value is assigned to the field.</para>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//oaidl/nf-oaidl-irecordinfo-putfield#parameters">Read more on docs.microsoft.com</see>.</para>
			/// </param>
			/// <param name="pvData">The pointer to an instance of the record.</param>
			/// <param name="szFieldName">The name of the field of the record.</param>
			/// <param name="pvarField">The pointer to the variant.</param>
			/// <returns>
			/// <para>This method can return one of these values. </para>
			/// <para>This doc was truncated.</para>
			/// </returns>
			/// <remarks>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//oaidl/nf-oaidl-irecordinfo-putfield">Learn more about this API from docs.microsoft.com</see>.</para>
			/// </remarks>
			unsafe void PutField(winmdroot.System.Com.INVOKEKIND wFlags, void* pvData, winmdroot.Foundation.PCWSTR szFieldName, [MarshalAs(UnmanagedType.Struct)] in object pvarField);

			/// <summary>Passes ownership of the data to the assigned field by placing the actual data into the field.</summary>
			/// <param name="wFlags">The only legal values for the wFlags parameter is INVOKE_PROPERTYPUT or INVOKE_PROPERTYPUTREF.</param>
			/// <param name="pvData">An instance of the record described by <a href="https://docs.microsoft.com/previous-versions/windows/desktop/api/oaidl/nn-oaidl-irecordinfo">IRecordInfo</a>.</param>
			/// <param name="szFieldName">The name of the field of the record.</param>
			/// <param name="pvarField">The variant to be put into the field.</param>
			/// <returns>
			/// <para>This method can return one of these values. </para>
			/// <para>This doc was truncated.</para>
			/// </returns>
			/// <remarks>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//oaidl/nf-oaidl-irecordinfo-putfieldnocopy">Learn more about this API from docs.microsoft.com</see>.</para>
			/// </remarks>
			unsafe void PutFieldNoCopy(winmdroot.System.Com.INVOKEKIND wFlags, void* pvData, winmdroot.Foundation.PCWSTR szFieldName, [MarshalAs(UnmanagedType.Struct)] in object pvarField);

			/// <summary>Gets the names of the fields of the record.</summary>
			/// <param name="pcNames">The number of names to return.</param>
			/// <param name="rgBstrNames">
			/// <para>The name of the array of type BSTR. If the <i>rgBstrNames</i> parameter is NULL, then <i>pcNames</i> is returned with the number of field names. It the <i>rgBstrNames</i> parameter is not NULL, then the string names contained in <i>rgBstrNames</i> are returned. If the number of names in <i>pcNames</i> and <i>rgBstrNames</i> are not equal then the lesser number of the two is the number of returned field names. The caller needs to free the BSTRs inside the array returned in <i>rgBstrNames</i>.</para>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//oaidl/nf-oaidl-irecordinfo-getfieldnames#parameters">Read more on docs.microsoft.com</see>.</para>
			/// </param>
			/// <returns>
			/// <para>This method can return one of these values. </para>
			/// <para>This doc was truncated.</para>
			/// </returns>
			/// <remarks>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//oaidl/nf-oaidl-irecordinfo-getfieldnames">Learn more about this API from docs.microsoft.com</see>.</para>
			/// </remarks>
			unsafe void GetFieldNames(uint* pcNames, winmdroot.Foundation.BSTR* rgBstrNames);

			/// <summary>Determines whether the record that is passed in matches that of the current record information.</summary>
			/// <param name="pRecordInfo">The information of the record.</param>
			/// <returns>
			/// <para></para>
			/// <para>This doc was truncated.</para>
			/// </returns>
			/// <remarks>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//oaidl/nf-oaidl-irecordinfo-ismatchingtype">Learn more about this API from docs.microsoft.com</see>.</para>
			/// </remarks>
						[PreserveSig()]
winmdroot.Foundation.BOOL IsMatchingType(winmdroot.System.Ole.IRecordInfo pRecordInfo);

			/// <summary>Allocates memory for a new record, initializes the instance and returns a pointer to the record.</summary>
			/// <returns>This method returns a pointer to the created record.</returns>
			/// <remarks>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//oaidl/nf-oaidl-irecordinfo-recordcreate">Learn more about this API from docs.microsoft.com</see>.</para>
			/// </remarks>
			[PreserveSig()]
			unsafe void* RecordCreate();

			/// <summary>Creates a copy of an instance of a record to the specified location.</summary>
			/// <param name="pvSource">An instance of the record to be copied.</param>
			/// <param name="ppvDest">The new record with data copied from <i>pvSource</i>.</param>
			/// <returns>
			/// <para>This method can return one of these values. </para>
			/// <para>This doc was truncated.</para>
			/// </returns>
			/// <remarks>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//oaidl/nf-oaidl-irecordinfo-recordcreatecopy">Learn more about this API from docs.microsoft.com</see>.</para>
			/// </remarks>
			unsafe void RecordCreateCopy(void* pvSource, void** ppvDest);

			/// <summary>Releases the resources and deallocates the memory of the record.</summary>
			/// <param name="pvRecord">An instance of the record to be destroyed.</param>
			/// <returns>
			/// <para>This method can return one of these values. </para>
			/// <para>This doc was truncated.</para>
			/// </returns>
			/// <remarks>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//oaidl/nf-oaidl-irecordinfo-recorddestroy">Learn more about this API from docs.microsoft.com</see>.</para>
			/// </remarks>
			unsafe void RecordDestroy(void* pvRecord);
		}
	}
}
