// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

#pragma warning disable CS1591,CS1573,CS0465,CS0649,CS8019,CS1570,CS1584,CS1658,CS0436,CS8981
using global::System;
using global::System.Diagnostics;
using global::System.Diagnostics.CodeAnalysis;
using global::System.Runtime.CompilerServices;
using global::System.Runtime.InteropServices;
using global::System.Runtime.Versioning;
using winmdroot = global::Windows.Win32;
namespace Windows.Win32
{
	[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.164-beta+187018bf44")]
	internal static partial class UI_Shell_ITaskbarList3_Extensions
	{
		/// <inheritdoc cref="winmdroot.UI.Shell.ITaskbarList3.ThumbBarAddButtons(winmdroot.Foundation.HWND, uint, winmdroot.UI.Shell.THUMBBUTTON*)"/>
		internal static unsafe void ThumbBarAddButtons(this winmdroot.UI.Shell.ITaskbarList3 @this, winmdroot.Foundation.HWND hwnd, Span<winmdroot.UI.Shell.THUMBBUTTON> pButton)
		{
			fixed (winmdroot.UI.Shell.THUMBBUTTON* pButtonLocal = pButton)
			{
				@this.ThumbBarAddButtons(hwnd, (uint )pButton.Length, pButtonLocal);
			}
		}

		/// <inheritdoc cref="winmdroot.UI.Shell.ITaskbarList3.ThumbBarUpdateButtons(winmdroot.Foundation.HWND, uint, winmdroot.UI.Shell.THUMBBUTTON*)"/>
		internal static unsafe void ThumbBarUpdateButtons(this winmdroot.UI.Shell.ITaskbarList3 @this, winmdroot.Foundation.HWND hwnd, Span<winmdroot.UI.Shell.THUMBBUTTON> pButton)
		{
			fixed (winmdroot.UI.Shell.THUMBBUTTON* pButtonLocal = pButton)
			{
				@this.ThumbBarUpdateButtons(hwnd, (uint )pButton.Length, pButtonLocal);
			}
		}

		/// <inheritdoc cref="winmdroot.UI.Shell.ITaskbarList3.ThumbBarSetImageList(winmdroot.Foundation.HWND, winmdroot.UI.Controls.HIMAGELIST)"/>
		internal static unsafe void ThumbBarSetImageList(this winmdroot.UI.Shell.ITaskbarList3 @this, winmdroot.Foundation.HWND hwnd, SafeHandle himl)
		{
			bool himlAddRef = false;
			try
			{
				winmdroot.UI.Controls.HIMAGELIST himlLocal;
				if (himl is object)
				{
					himl.DangerousAddRef(ref himlAddRef);
					himlLocal = (winmdroot.UI.Controls.HIMAGELIST)himl.DangerousGetHandle();
				}
				else
throw new ArgumentNullException(nameof(himl));
				@this.ThumbBarSetImageList(hwnd, himlLocal);
			}
			finally
			{
				if (himlAddRef)
					himl.DangerousRelease();
			}
		}

		/// <inheritdoc cref="winmdroot.UI.Shell.ITaskbarList3.SetOverlayIcon(winmdroot.Foundation.HWND, winmdroot.UI.WindowsAndMessaging.HICON, winmdroot.Foundation.PCWSTR)"/>
		internal static unsafe void SetOverlayIcon(this winmdroot.UI.Shell.ITaskbarList3 @this, winmdroot.Foundation.HWND hwnd, SafeHandle hIcon, string pszDescription)
		{
			bool hIconAddRef = false;
			try
			{
				fixed (char* pszDescriptionLocal = pszDescription)
				{
					winmdroot.UI.WindowsAndMessaging.HICON hIconLocal;
					if (hIcon is object)
					{
						hIcon.DangerousAddRef(ref hIconAddRef);
						hIconLocal = (winmdroot.UI.WindowsAndMessaging.HICON)hIcon.DangerousGetHandle();
					}
					else
throw new ArgumentNullException(nameof(hIcon));
					@this.SetOverlayIcon(hwnd, hIconLocal, pszDescriptionLocal);
				}
			}
			finally
			{
				if (hIconAddRef)
					hIcon.DangerousRelease();
			}
		}

		/// <inheritdoc cref="winmdroot.UI.Shell.ITaskbarList3.SetThumbnailTooltip(winmdroot.Foundation.HWND, winmdroot.Foundation.PCWSTR)"/>
		internal static unsafe void SetThumbnailTooltip(this winmdroot.UI.Shell.ITaskbarList3 @this, winmdroot.Foundation.HWND hwnd, string pszTip)
		{
			fixed (char* pszTipLocal = pszTip)
			{
				@this.SetThumbnailTooltip(hwnd, pszTipLocal);
			}
		}

		/// <inheritdoc cref="winmdroot.UI.Shell.ITaskbarList3.SetThumbnailClip(winmdroot.Foundation.HWND, winmdroot.Foundation.RECT*)"/>
		internal static unsafe void SetThumbnailClip(this winmdroot.UI.Shell.ITaskbarList3 @this, winmdroot.Foundation.HWND hwnd, in winmdroot.Foundation.RECT prcClip)
		{
			fixed (winmdroot.Foundation.RECT* prcClipLocal = &prcClip)
			{
				@this.SetThumbnailClip(hwnd, prcClipLocal);
			}
		}
	}
}
