// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

#pragma warning disable CS1591,CS1573,CS0465,CS0649,CS8019,CS1570,CS1584,CS1658,CS0436,CS8981
using global::System;
using global::System.Diagnostics;
using global::System.Diagnostics.CodeAnalysis;
using global::System.Runtime.CompilerServices;
using global::System.Runtime.InteropServices;
using global::System.Runtime.Versioning;
using winmdroot = global::Windows.Win32;
namespace Windows.Win32
{
	namespace System.Ole
	{
		/// <summary>Describes an array, its element type, and its dimension.</summary>
		/// <remarks>
		/// <para><see href="https://docs.microsoft.com/windows/win32/api//oaidl/ns-oaidl-arraydesc">Learn more about this API from docs.microsoft.com</see>.</para>
		/// </remarks>
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.164-beta+187018bf44")]
		internal partial struct ARRAYDESC
		{
			/// <summary>The element type.</summary>
			internal winmdroot.System.Com.TYPEDESC tdescElem;
			/// <summary>The dimension count.</summary>
			internal ushort cDims;
			/// <summary>A variable-length array containing one element for each dimension.</summary>
			internal winmdroot.System.Com.__SAFEARRAYBOUND_1 rgbounds;
		}
	}
}
