// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

#pragma warning disable CS1591,CS1573,CS0465,CS0649,CS8019,CS1570,CS1584,CS1658,CS0436,CS8981
using global::System;
using global::System.Diagnostics;
using global::System.Diagnostics.CodeAnalysis;
using global::System.Runtime.CompilerServices;
using global::System.Runtime.InteropServices;
using global::System.Runtime.Versioning;
using winmdroot = global::Windows.Win32;
namespace Windows.Win32
{
	[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.164-beta+187018bf44")]
	internal static partial class System_Com_StructuredStorage_IStorage_Extensions
	{
		/// <inheritdoc cref="winmdroot.System.Com.StructuredStorage.IStorage.CreateStream(winmdroot.Foundation.PCWSTR, winmdroot.System.Com.STGM, uint, uint, out winmdroot.System.Com.IStream)"/>
		internal static unsafe void CreateStream(this winmdroot.System.Com.StructuredStorage.IStorage @this, string pwcsName, winmdroot.System.Com.STGM grfMode, uint reserved1, uint reserved2, out winmdroot.System.Com.IStream ppstm)
		{
			fixed (char* pwcsNameLocal = pwcsName)
			{
				@this.CreateStream(pwcsNameLocal, grfMode, reserved1, reserved2, out ppstm);
			}
		}

		/// <inheritdoc cref="winmdroot.System.Com.StructuredStorage.IStorage.OpenStream(winmdroot.Foundation.PCWSTR, void*, winmdroot.System.Com.STGM, uint, out winmdroot.System.Com.IStream)"/>
		internal static unsafe void OpenStream(this winmdroot.System.Com.StructuredStorage.IStorage @this, string pwcsName, void* reserved1, winmdroot.System.Com.STGM grfMode, uint reserved2, out winmdroot.System.Com.IStream ppstm)
		{
			fixed (char* pwcsNameLocal = pwcsName)
			{
				@this.OpenStream(pwcsNameLocal, reserved1, grfMode, reserved2, out ppstm);
			}
		}

		/// <inheritdoc cref="winmdroot.System.Com.StructuredStorage.IStorage.CreateStorage(winmdroot.Foundation.PCWSTR, winmdroot.System.Com.STGM, uint, uint, out winmdroot.System.Com.StructuredStorage.IStorage)"/>
		internal static unsafe void CreateStorage(this winmdroot.System.Com.StructuredStorage.IStorage @this, string pwcsName, winmdroot.System.Com.STGM grfMode, uint reserved1, uint reserved2, out winmdroot.System.Com.StructuredStorage.IStorage ppstg)
		{
			fixed (char* pwcsNameLocal = pwcsName)
			{
				@this.CreateStorage(pwcsNameLocal, grfMode, reserved1, reserved2, out ppstg);
			}
		}

		/// <inheritdoc cref="winmdroot.System.Com.StructuredStorage.IStorage.OpenStorage(winmdroot.Foundation.PCWSTR, winmdroot.System.Com.StructuredStorage.IStorage, winmdroot.System.Com.STGM, ushort**, uint, out winmdroot.System.Com.StructuredStorage.IStorage)"/>
		internal static unsafe void OpenStorage(this winmdroot.System.Com.StructuredStorage.IStorage @this, string pwcsName, winmdroot.System.Com.StructuredStorage.IStorage pstgPriority, winmdroot.System.Com.STGM grfMode, in ushort* snbExclude, uint reserved, out winmdroot.System.Com.StructuredStorage.IStorage ppstg)
		{
			fixed (ushort** snbExcludeLocal = &snbExclude)
			{
				fixed (char* pwcsNameLocal = pwcsName)
				{
					@this.OpenStorage(pwcsNameLocal, pstgPriority, grfMode, snbExcludeLocal, reserved, out ppstg);
				}
			}
		}

		/// <inheritdoc cref="winmdroot.System.Com.StructuredStorage.IStorage.CopyTo(uint, global::System.Guid*, ushort**, winmdroot.System.Com.StructuredStorage.IStorage)"/>
		internal static unsafe void CopyTo(this winmdroot.System.Com.StructuredStorage.IStorage @this, ReadOnlySpan<global::System.Guid> rgiidExclude, ushort** snbExclude, winmdroot.System.Com.StructuredStorage.IStorage pstgDest)
		{
			fixed (global::System.Guid* rgiidExcludeLocal = rgiidExclude)
			{
				@this.CopyTo((uint )rgiidExclude.Length, rgiidExcludeLocal, snbExclude, pstgDest);
			}
		}

		/// <inheritdoc cref="winmdroot.System.Com.StructuredStorage.IStorage.MoveElementTo(winmdroot.Foundation.PCWSTR, winmdroot.System.Com.StructuredStorage.IStorage, winmdroot.Foundation.PCWSTR, winmdroot.System.Com.StructuredStorage.STGMOVE)"/>
		internal static unsafe void MoveElementTo(this winmdroot.System.Com.StructuredStorage.IStorage @this, string pwcsName, winmdroot.System.Com.StructuredStorage.IStorage pstgDest, string pwcsNewName, winmdroot.System.Com.StructuredStorage.STGMOVE grfFlags)
		{
			fixed (char* pwcsNewNameLocal = pwcsNewName)
			{
				fixed (char* pwcsNameLocal = pwcsName)
				{
					@this.MoveElementTo(pwcsNameLocal, pstgDest, pwcsNewNameLocal, grfFlags);
				}
			}
		}

		/// <inheritdoc cref="winmdroot.System.Com.StructuredStorage.IStorage.DestroyElement(winmdroot.Foundation.PCWSTR)"/>
		internal static unsafe void DestroyElement(this winmdroot.System.Com.StructuredStorage.IStorage @this, string pwcsName)
		{
			fixed (char* pwcsNameLocal = pwcsName)
			{
				@this.DestroyElement(pwcsNameLocal);
			}
		}

		/// <inheritdoc cref="winmdroot.System.Com.StructuredStorage.IStorage.RenameElement(winmdroot.Foundation.PCWSTR, winmdroot.Foundation.PCWSTR)"/>
		internal static unsafe void RenameElement(this winmdroot.System.Com.StructuredStorage.IStorage @this, string pwcsOldName, string pwcsNewName)
		{
			fixed (char* pwcsNewNameLocal = pwcsNewName)
			{
				fixed (char* pwcsOldNameLocal = pwcsOldName)
				{
					@this.RenameElement(pwcsOldNameLocal, pwcsNewNameLocal);
				}
			}
		}

		/// <inheritdoc cref="winmdroot.System.Com.StructuredStorage.IStorage.SetElementTimes(winmdroot.Foundation.PCWSTR, global::System.Runtime.InteropServices.ComTypes.FILETIME*, global::System.Runtime.InteropServices.ComTypes.FILETIME*, global::System.Runtime.InteropServices.ComTypes.FILETIME*)"/>
		internal static unsafe void SetElementTimes(this winmdroot.System.Com.StructuredStorage.IStorage @this, string pwcsName, in global::System.Runtime.InteropServices.ComTypes.FILETIME pctime, in global::System.Runtime.InteropServices.ComTypes.FILETIME patime, in global::System.Runtime.InteropServices.ComTypes.FILETIME pmtime)
		{
			fixed (global::System.Runtime.InteropServices.ComTypes.FILETIME* pmtimeLocal = &pmtime)
			{
				fixed (global::System.Runtime.InteropServices.ComTypes.FILETIME* patimeLocal = &patime)
				{
					fixed (global::System.Runtime.InteropServices.ComTypes.FILETIME* pctimeLocal = &pctime)
					{
						fixed (char* pwcsNameLocal = pwcsName)
						{
							@this.SetElementTimes(pwcsNameLocal, pctimeLocal, patimeLocal, pmtimeLocal);
						}
					}
				}
			}
		}

		/// <inheritdoc cref="winmdroot.System.Com.StructuredStorage.IStorage.SetClass(global::System.Guid*)"/>
		internal static unsafe void SetClass(this winmdroot.System.Com.StructuredStorage.IStorage @this, in global::System.Guid clsid)
		{
			fixed (global::System.Guid* clsidLocal = &clsid)
			{
				@this.SetClass(clsidLocal);
			}
		}

		/// <inheritdoc cref="winmdroot.System.Com.StructuredStorage.IStorage.Stat(winmdroot.System.Com.STATSTG*, winmdroot.System.Com.STATFLAG)"/>
		internal static unsafe void Stat(this winmdroot.System.Com.StructuredStorage.IStorage @this, out winmdroot.System.Com.STATSTG pstatstg, winmdroot.System.Com.STATFLAG grfStatFlag)
		{
			fixed (winmdroot.System.Com.STATSTG* pstatstgLocal = &pstatstg)
			{
				@this.Stat(pstatstgLocal, grfStatFlag);
			}
		}
	}
}
