// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

#pragma warning disable CS1591,CS1573,CS0465,CS0649,CS8019,CS1570,CS1584,CS1658,CS0436,CS8981
using global::System;
using global::System.Diagnostics;
using global::System.Diagnostics.CodeAnalysis;
using global::System.Runtime.CompilerServices;
using global::System.Runtime.InteropServices;
using global::System.Runtime.Versioning;
using winmdroot = global::Windows.Win32;
namespace Windows.Win32
{
	namespace System.Com
	{
		/// <summary>Specifies variable flags.</summary>
		/// <remarks>
		/// <para><see href="https://docs.microsoft.com/windows/win32/api//oaidl/ne-oaidl-varflags">Learn more about this API from docs.microsoft.com</see>.</para>
		/// </remarks>
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.164-beta+187018bf44")]
		internal enum VARFLAGS : ushort
		{
			/// <summary>Assignment to the variable should not be allowed.</summary>
			VARFLAG_FREADONLY = 1,
			/// <summary>The variable returns an object that is a source of events.</summary>
			VARFLAG_FSOURCE = 2,
			/// <summary>The variable supports data binding.</summary>
			VARFLAG_FBINDABLE = 4,
			/// <summary>When set, any attempt to directly change the property results in a call to <b>IPropertyNotifySink::OnRequestEdit</b>. The implementation of <b>OnRequestEdit</b> determines if the change is accepted.</summary>
			VARFLAG_FREQUESTEDIT = 8,
			/// <summary>The variable is displayed to the user as bindable. VARFLAG_FBINDABLE must also be set.</summary>
			VARFLAG_FDISPLAYBIND = 16,
			/// <summary>The variable is the single property that best represents the object. Only one variable in type information can have this attribute.</summary>
			VARFLAG_FDEFAULTBIND = 32,
			/// <summary>The variable should not be displayed to the user in a browser, although it exists and is bindable.</summary>
			VARFLAG_FHIDDEN = 64,
			/// <summary>The variable should not be accessible from macro languages. This flag is intended for system-level variables or variables that you do not want type browsers to display.</summary>
			VARFLAG_FRESTRICTED = 128,
			/// <summary>Permits an optimization in which the compiler looks for a member named "xyz" on the type of abc. If such a member is found and is flagged as an accessor function for an element of the default collection, then a call is generated to that member function. Permitted on members in dispinterfaces and interfaces; not permitted on modules.</summary>
			VARFLAG_FDEFAULTCOLLELEM = 256,
			/// <summary>The variable is the default display in the user interface.</summary>
			VARFLAG_FUIDEFAULT = 512,
			/// <summary>The variable appears in an object browser, but not in a properties browser.</summary>
			VARFLAG_FNONBROWSABLE = 1024,
			/// <summary>Tags the interface as having default behaviors.</summary>
			VARFLAG_FREPLACEABLE = 2048,
			/// <summary>The variable is mapped as individual bindable properties.</summary>
			VARFLAG_FIMMEDIATEBIND = 4096,
		}
	}
}
