// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

#pragma warning disable CS1591,CS1573,CS0465,CS0649,CS8019,CS1570,CS1584,CS1658,CS0436,CS8981
using global::System;
using global::System.Diagnostics;
using global::System.Diagnostics.CodeAnalysis;
using global::System.Runtime.CompilerServices;
using global::System.Runtime.InteropServices;
using global::System.Runtime.Versioning;
using winmdroot = global::Windows.Win32;
namespace Windows.Win32
{
	namespace UI.Shell.Common
	{
		[Guid("92CA9DCD-5622-4BBA-A805-5E9F541BD8C9"),InterfaceType(ComInterfaceType.InterfaceIsIUnknown),ComImport()]
		[SupportedOSPlatform("windows6.1")]
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.164-beta+187018bf44")]
		internal interface IObjectArray
		{
			/// <summary>Provides a count of the objects in the collection.</summary>
			/// <param name="pcObjects">
			/// <para>Type: <b>UINT*</b> The number of objects in the collection.</para>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//objectarray/nf-objectarray-iobjectarray-getcount#parameters">Read more on docs.microsoft.com</see>.</para>
			/// </param>
			/// <returns>
			/// <para>Type: <b>HRESULT</b> If this method succeeds, it returns <b xmlns:loc="http://microsoft.com/wdcml/l10n">S_OK</b>. Otherwise, it returns an <b xmlns:loc="http://microsoft.com/wdcml/l10n">HRESULT</b> error code.</para>
			/// </returns>
			/// <remarks>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//objectarray/nf-objectarray-iobjectarray-getcount">Learn more about this API from docs.microsoft.com</see>.</para>
			/// </remarks>
			unsafe void GetCount(uint* pcObjects);

			/// <summary>Provides a pointer to a specified object's interface. The object and interface are specified by index and interface ID.</summary>
			/// <param name="uiIndex">
			/// <para>Type: <b>UINT</b> The index of the object</para>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//objectarray/nf-objectarray-iobjectarray-getat#parameters">Read more on docs.microsoft.com</see>.</para>
			/// </param>
			/// <param name="riid">
			/// <para>Type: <b>REFIID</b> Reference to the desired interface ID.</para>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//objectarray/nf-objectarray-iobjectarray-getat#parameters">Read more on docs.microsoft.com</see>.</para>
			/// </param>
			/// <param name="ppv">
			/// <para>Type: <b>void**</b> Receives the interface pointer requested in <i>riid</i>.</para>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//objectarray/nf-objectarray-iobjectarray-getat#parameters">Read more on docs.microsoft.com</see>.</para>
			/// </param>
			/// <returns>
			/// <para>Type: <b>HRESULT</b> If this method succeeds, it returns <b xmlns:loc="http://microsoft.com/wdcml/l10n">S_OK</b>. Otherwise, it returns an <b xmlns:loc="http://microsoft.com/wdcml/l10n">HRESULT</b> error code.</para>
			/// </returns>
			/// <remarks>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//objectarray/nf-objectarray-iobjectarray-getat">Learn more about this API from docs.microsoft.com</see>.</para>
			/// </remarks>
			unsafe void GetAt(uint uiIndex, global::System.Guid* riid, [MarshalAs(UnmanagedType.IUnknown)] out object ppv);
		}
	}
}
