// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

#pragma warning disable CS1591,CS1573,CS0465,CS0649,CS8019,CS1570,CS1584,CS1658,CS0436,CS8981
using global::System;
using global::System.Diagnostics;
using global::System.Diagnostics.CodeAnalysis;
using global::System.Runtime.CompilerServices;
using global::System.Runtime.InteropServices;
using global::System.Runtime.Versioning;
using winmdroot = global::Windows.Win32;
namespace Windows.Win32
{
	namespace UI.Shell
	{
		[Guid("602D4995-B13A-429B-A66E-1935E44F4317"),InterfaceType(ComInterfaceType.InterfaceIsIUnknown),ComImport()]
		[SupportedOSPlatform("windows5.1.2600")]
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.164-beta+187018bf44")]
		internal interface ITaskbarList2
			:winmdroot.UI.Shell.ITaskbarList		{
			new void HrInit();

			new void AddTab(winmdroot.Foundation.HWND hwnd);

			new void DeleteTab(winmdroot.Foundation.HWND hwnd);

			new void ActivateTab(winmdroot.Foundation.HWND hwnd);

			new void SetActiveAlt(winmdroot.Foundation.HWND hwnd);

			/// <summary>Marks a window as full-screen.</summary>
			/// <param name="hwnd">
			/// <para>Type: <b>HWND</b> The handle of the window to be marked.</para>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//shobjidl_core/nf-shobjidl_core-itaskbarlist2-markfullscreenwindow#parameters">Read more on docs.microsoft.com</see>.</para>
			/// </param>
			/// <param name="fFullscreen">
			/// <para>Type: <b>BOOL</b> A Boolean value marking the desired full-screen status of the window.</para>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//shobjidl_core/nf-shobjidl_core-itaskbarlist2-markfullscreenwindow#parameters">Read more on docs.microsoft.com</see>.</para>
			/// </param>
			/// <returns>
			/// <para>Type: <b>HRESULT</b> If this method succeeds, it returns <b xmlns:loc="http://microsoft.com/wdcml/l10n">S_OK</b>. Otherwise, it returns an <b xmlns:loc="http://microsoft.com/wdcml/l10n">HRESULT</b> error code.</para>
			/// </returns>
			/// <remarks>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//shobjidl_core/nf-shobjidl_core-itaskbarlist2-markfullscreenwindow">Learn more about this API from docs.microsoft.com</see>.</para>
			/// </remarks>
			void MarkFullscreenWindow(winmdroot.Foundation.HWND hwnd, winmdroot.Foundation.BOOL fFullscreen);
		}
	}
}
