// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

#pragma warning disable CS1591,CS1573,CS0465,CS0649,CS8019,CS1570,CS1584,CS1658,CS0436,CS8981
using global::System;
using global::System.Diagnostics;
using global::System.Diagnostics.CodeAnalysis;
using global::System.Runtime.CompilerServices;
using global::System.Runtime.InteropServices;
using global::System.Runtime.Versioning;
using winmdroot = global::Windows.Win32;
namespace Windows.Win32
{

	/// <summary>
	/// Represents a Win32 handle that can be closed with <see cref="PInvoke.SysFreeString"/>.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.164-beta+187018bf44")]
	internal class SysFreeStringSafeHandle
		:SafeHandle	{
		private static readonly IntPtr INVALID_HANDLE_VALUE = new IntPtr(0L);
		internal SysFreeStringSafeHandle():base(INVALID_HANDLE_VALUE, true)
		{
		}
		internal SysFreeStringSafeHandle(IntPtr preexistingHandle, bool ownsHandle = true):base(INVALID_HANDLE_VALUE, ownsHandle)
		{
			this.SetHandle(preexistingHandle);
		}

		public override bool IsInvalid => false;

		protected override bool ReleaseHandle()
		{
			PInvoke.SysFreeString((winmdroot.Foundation.BSTR)this.handle);
			return true;
		}
	}
}
