// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

#pragma warning disable CS1591,CS1573,CS0465,CS0649,CS8019,CS1570,CS1584,CS1658,CS0436,CS8981
using global::System;
using global::System.Diagnostics;
using global::System.Diagnostics.CodeAnalysis;
using global::System.Runtime.CompilerServices;
using global::System.Runtime.InteropServices;
using global::System.Runtime.Versioning;
using winmdroot = global::Windows.Win32;
namespace Windows.Win32
{
	namespace UI.Shell
	{
		/// <summary>Used by the ITaskbarList4::SetTabProperties method to specify tab properties.</summary>
		/// <remarks>
		/// <para><see href="https://docs.microsoft.com/windows/win32/api//shobjidl_core/ne-shobjidl_core-stpflag">Learn more about this API from docs.microsoft.com</see>.</para>
		/// </remarks>
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.164-beta+187018bf44")]
		internal enum STPFLAG
		{
			/// <summary>No specific property values are specified. The default behavior is used: the tab window provides a thumbnail and peek image, either live or static as appropriate.</summary>
			STPF_NONE = 0,
			/// <summary>Always use the thumbnail provided by the main application frame window rather than a thumbnail provided by the individual tab window. Do not combine this value with STPF_USEAPPTHUMBNAILWHENACTIVE; doing so will result in an error.</summary>
			STPF_USEAPPTHUMBNAILALWAYS = 1,
			/// <summary>When the application tab is active and a live representation of its window is available, use the main application's frame window thumbnail. At other times, use the tab window thumbnail. Do not combine this value with STPF_USEAPPTHUMBNAILALWAYS; doing so will result in an error.</summary>
			STPF_USEAPPTHUMBNAILWHENACTIVE = 2,
			/// <summary>Always use the peek image provided by the main application frame window rather than a peek image provided by the individual tab window. Do not combine this value with STPF_USEAPPPEEKWHENACTIVE; doing so will result in an error.</summary>
			STPF_USEAPPPEEKALWAYS = 4,
			/// <summary>When the application tab is active and a live representation of its window is available, show the main application frame in the peek feature. At other times, use the tab window. Do not combine this value with STPF_USEAPPPEEKALWAYS; doing so will result in an error.</summary>
			STPF_USEAPPPEEKWHENACTIVE = 8,
		}
	}
}
