// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

#pragma warning disable CS1591,CS1573,CS0465,CS0649,CS8019,CS1570,CS1584,CS1658,CS0436,CS8981
using global::System;
using global::System.Diagnostics;
using global::System.Diagnostics.CodeAnalysis;
using global::System.Runtime.CompilerServices;
using global::System.Runtime.InteropServices;
using global::System.Runtime.Versioning;
using winmdroot = global::Windows.Win32;
namespace Windows.Win32
{
	namespace UI.Shell
	{
		[Guid("000214F9-0000-0000-C000-000000000046"),InterfaceType(ComInterfaceType.InterfaceIsIUnknown),ComImport()]
		[SupportedOSPlatform("windows5.1.2600")]
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.164-beta+187018bf44")]
		internal interface IShellLinkW
		{
			/// <summary>Gets the path and file name of the target of a Shell link object.</summary>
			/// <param name="pszFile">
			/// <para>Type: <b>LPTSTR</b> The address of a buffer that receives the path and file name of the target of the Shell link object.</para>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//shobjidl_core/nf-shobjidl_core-ishelllinkw-getpath#parameters">Read more on docs.microsoft.com</see>.</para>
			/// </param>
			/// <param name="cch">
			/// <para>Type: <b>int</b> The size, in characters, of the buffer pointed to by the <i>pszFile</i> parameter, including the terminating null character. The maximum path size that can be returned is MAX_PATH. This parameter is commonly set by calling ARRAYSIZE(pszFile). The ARRAYSIZE macro is defined in Winnt.h.</para>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//shobjidl_core/nf-shobjidl_core-ishelllinkw-getpath#parameters">Read more on docs.microsoft.com</see>.</para>
			/// </param>
			/// <param name="pfd">
			/// <para>Type: <b><a href="https://docs.microsoft.com/windows/desktop/api/minwinbase/ns-minwinbase-win32_find_dataa">WIN32_FIND_DATA</a>*</b> A pointer to a <a href="https://docs.microsoft.com/windows/desktop/api/minwinbase/ns-minwinbase-win32_find_dataa">WIN32_FIND_DATA</a> structure that receives information about the target of the Shell link object. If this parameter is <b>NULL</b>, then no additional information is returned.</para>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//shobjidl_core/nf-shobjidl_core-ishelllinkw-getpath#parameters">Read more on docs.microsoft.com</see>.</para>
			/// </param>
			/// <param name="fFlags">Type: <b>DWORD</b></param>
			/// <returns>
			/// <para>Type: <b>HRESULT</b> Returns <b>S_OK</b> if the operation is successful and a valid path is retrieved. If the operation is successful but no path is retrieved, it returns <b>S_FALSE</b> and <i>pszFile</i> will be empty. Otherwise, it returns one of the standard HRESULT error values.</para>
			/// </returns>
			/// <remarks>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//shobjidl_core/nf-shobjidl_core-ishelllinkw-getpath">Learn more about this API from docs.microsoft.com</see>.</para>
			/// </remarks>
			unsafe void GetPath(winmdroot.Foundation.PWSTR pszFile, int cch, winmdroot.Storage.FileSystem.WIN32_FIND_DATAW* pfd, uint fFlags);

			/// <summary>Gets the list of item identifiers for the target of a Shell link object.</summary>
			/// <param name="ppidl">
			/// <para>Type: <b>PIDLIST_ABSOLUTE*</b> When this method returns, contains the address of a PIDL.</para>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//shobjidl_core/nf-shobjidl_core-ishelllinkw-getidlist#parameters">Read more on docs.microsoft.com</see>.</para>
			/// </param>
			/// <returns>
			/// <para>Type: <b>HRESULT</b> Returns S_OK if the operation is successful and one or more valid PIDLs is retrieved. If the operation is successful but no PIDLs are retrieved, it returns S_FALSE with <i>ppidl</i> set to <b>NULL</b>. Otherwise, it returns a standard error value.</para>
			/// </returns>
			/// <remarks>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//shobjidl_core/nf-shobjidl_core-ishelllinkw-getidlist">Learn more about this API from docs.microsoft.com</see>.</para>
			/// </remarks>
			unsafe void GetIDList(winmdroot.UI.Shell.Common.ITEMIDLIST** ppidl);

			/// <summary>Sets the pointer to an item identifier list (PIDL) for a Shell link object.</summary>
			/// <param name="pidl">
			/// <para>Type: <b>PCIDLIST_ABSOLUTE</b> The object's fully qualified PIDL.</para>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//shobjidl_core/nf-shobjidl_core-ishelllinkw-setidlist#parameters">Read more on docs.microsoft.com</see>.</para>
			/// </param>
			/// <returns>
			/// <para>Type: <b>HRESULT</b> If this method succeeds, it returns <b xmlns:loc="http://microsoft.com/wdcml/l10n">S_OK</b>. Otherwise, it returns an <b xmlns:loc="http://microsoft.com/wdcml/l10n">HRESULT</b> error code.</para>
			/// </returns>
			/// <remarks>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//shobjidl_core/nf-shobjidl_core-ishelllinkw-setidlist">Learn more about this API from docs.microsoft.com</see>.</para>
			/// </remarks>
			unsafe void SetIDList(winmdroot.UI.Shell.Common.ITEMIDLIST* pidl);

			/// <summary>Gets the description string for a Shell link object.</summary>
			/// <param name="pszName">
			/// <para>Type: <b>LPTSTR</b> A pointer to the buffer that receives the description string.</para>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//shobjidl_core/nf-shobjidl_core-ishelllinkw-getdescription#parameters">Read more on docs.microsoft.com</see>.</para>
			/// </param>
			/// <param name="cch">
			/// <para>Type: <b>int</b> The maximum number of characters to copy to the buffer pointed to by the <i>pszName</i> parameter.</para>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//shobjidl_core/nf-shobjidl_core-ishelllinkw-getdescription#parameters">Read more on docs.microsoft.com</see>.</para>
			/// </param>
			/// <returns>
			/// <para>Type: <b>HRESULT</b> If this method succeeds, it returns <b xmlns:loc="http://microsoft.com/wdcml/l10n">S_OK</b>. Otherwise, it returns an <b xmlns:loc="http://microsoft.com/wdcml/l10n">HRESULT</b> error code.</para>
			/// </returns>
			/// <remarks>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//shobjidl_core/nf-shobjidl_core-ishelllinkw-getdescription">Learn more about this API from docs.microsoft.com</see>.</para>
			/// </remarks>
			void GetDescription(winmdroot.Foundation.PWSTR pszName, int cch);

			/// <summary>Sets the description for a Shell link object. The description can be any application-defined string.</summary>
			/// <param name="pszName">
			/// <para>Type: <b>LPCTSTR</b> A pointer to a buffer containing the new description string.</para>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//shobjidl_core/nf-shobjidl_core-ishelllinkw-setdescription#parameters">Read more on docs.microsoft.com</see>.</para>
			/// </param>
			/// <returns>
			/// <para>Type: <b>HRESULT</b> If this method succeeds, it returns <b xmlns:loc="http://microsoft.com/wdcml/l10n">S_OK</b>. Otherwise, it returns an <b xmlns:loc="http://microsoft.com/wdcml/l10n">HRESULT</b> error code.</para>
			/// </returns>
			/// <remarks>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//shobjidl_core/nf-shobjidl_core-ishelllinkw-setdescription">Learn more about this API from docs.microsoft.com</see>.</para>
			/// </remarks>
			void SetDescription(winmdroot.Foundation.PCWSTR pszName);

			/// <summary>Gets the name of the working directory for a Shell link object.</summary>
			/// <param name="pszDir">
			/// <para>Type: <b>LPTSTR</b> The address of a buffer that receives the name of the working directory.</para>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//shobjidl_core/nf-shobjidl_core-ishelllinkw-getworkingdirectory#parameters">Read more on docs.microsoft.com</see>.</para>
			/// </param>
			/// <param name="cch">
			/// <para>Type: <b>int</b> The maximum number of characters to copy to the buffer pointed to by the <i>pszDir</i> parameter. The name of the working directory is truncated if it is longer than the maximum specified by this parameter.</para>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//shobjidl_core/nf-shobjidl_core-ishelllinkw-getworkingdirectory#parameters">Read more on docs.microsoft.com</see>.</para>
			/// </param>
			/// <returns>
			/// <para>Type: <b>HRESULT</b> If this method succeeds, it returns <b xmlns:loc="http://microsoft.com/wdcml/l10n">S_OK</b>. Otherwise, it returns an <b xmlns:loc="http://microsoft.com/wdcml/l10n">HRESULT</b> error code.</para>
			/// </returns>
			/// <remarks>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//shobjidl_core/nf-shobjidl_core-ishelllinkw-getworkingdirectory">Learn more about this API from docs.microsoft.com</see>.</para>
			/// </remarks>
			void GetWorkingDirectory(winmdroot.Foundation.PWSTR pszDir, int cch);

			/// <summary>Sets the name of the working directory for a Shell link object.</summary>
			/// <param name="pszDir">
			/// <para>Type: <b>LPCTSTR</b> The address of a buffer that contains the name of the new working directory.</para>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//shobjidl_core/nf-shobjidl_core-ishelllinkw-setworkingdirectory#parameters">Read more on docs.microsoft.com</see>.</para>
			/// </param>
			/// <returns>
			/// <para>Type: <b>HRESULT</b> If this method succeeds, it returns <b xmlns:loc="http://microsoft.com/wdcml/l10n">S_OK</b>. Otherwise, it returns an <b xmlns:loc="http://microsoft.com/wdcml/l10n">HRESULT</b> error code.</para>
			/// </returns>
			/// <remarks>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//shobjidl_core/nf-shobjidl_core-ishelllinkw-setworkingdirectory">Learn more about this API from docs.microsoft.com</see>.</para>
			/// </remarks>
			void SetWorkingDirectory(winmdroot.Foundation.PCWSTR pszDir);

			/// <summary>Gets the command-line arguments associated with a Shell link object.</summary>
			/// <param name="pszArgs">
			/// <para>Type: <b>LPTSTR</b> A pointer to the buffer that, when this method returns successfully, receives the command-line arguments.</para>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//shobjidl_core/nf-shobjidl_core-ishelllinkw-getarguments#parameters">Read more on docs.microsoft.com</see>.</para>
			/// </param>
			/// <param name="cch">
			/// <para>Type: <b>int</b> The maximum number of characters that can be copied to the buffer supplied by the <i>pszArgs</i> parameter. In the case of a Unicode string, there is no limitation on maximum string length. In the case of an ANSI string, the maximum length of the returned string varies depending on the version of Windows—MAX_PATH prior to Windows 2000 and INFOTIPSIZE (defined in Commctrl.h) in Windows 2000 and later.</para>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//shobjidl_core/nf-shobjidl_core-ishelllinkw-getarguments#parameters">Read more on docs.microsoft.com</see>.</para>
			/// </param>
			/// <returns>
			/// <para>Type: <b>HRESULT</b> If this method succeeds, it returns <b xmlns:loc="http://microsoft.com/wdcml/l10n">S_OK</b>. Otherwise, it returns an <b xmlns:loc="http://microsoft.com/wdcml/l10n">HRESULT</b> error code.</para>
			/// </returns>
			/// <remarks>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//shobjidl_core/nf-shobjidl_core-ishelllinkw-getarguments">Learn more about this API from docs.microsoft.com</see>.</para>
			/// </remarks>
			void GetArguments(winmdroot.Foundation.PWSTR pszArgs, int cch);

			/// <summary>Sets the command-line arguments for a Shell link object.</summary>
			/// <param name="pszArgs">
			/// <para>Type: <b>LPCTSTR</b> A pointer to a buffer that contains the new command-line arguments. In the case of a Unicode string, there is no limitation on maximum string length. In the case of an ANSI string, the maximum length of the returned string varies depending on the version of Windows—MAX_PATH prior to Windows 2000 and INFOTIPSIZE (defined in Commctrl.h) in Windows 2000 and later.</para>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//shobjidl_core/nf-shobjidl_core-ishelllinkw-setarguments#parameters">Read more on docs.microsoft.com</see>.</para>
			/// </param>
			/// <returns>
			/// <para>Type: <b>HRESULT</b> If this method succeeds, it returns <b xmlns:loc="http://microsoft.com/wdcml/l10n">S_OK</b>. Otherwise, it returns an <b xmlns:loc="http://microsoft.com/wdcml/l10n">HRESULT</b> error code.</para>
			/// </returns>
			/// <remarks>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//shobjidl_core/nf-shobjidl_core-ishelllinkw-setarguments">Learn more about this API from docs.microsoft.com</see>.</para>
			/// </remarks>
			void SetArguments(winmdroot.Foundation.PCWSTR pszArgs);

			/// <summary>Gets the keyboard shortcut (hot key) for a Shell link object.</summary>
			/// <param name="pwHotkey">Type: <b>WORD*</b></param>
			/// <returns>
			/// <para>Type: <b>HRESULT</b> If this method succeeds, it returns <b xmlns:loc="http://microsoft.com/wdcml/l10n">S_OK</b>. Otherwise, it returns an <b xmlns:loc="http://microsoft.com/wdcml/l10n">HRESULT</b> error code.</para>
			/// </returns>
			/// <remarks>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//shobjidl_core/nf-shobjidl_core-ishelllinkw-gethotkey">Learn more about this API from docs.microsoft.com</see>.</para>
			/// </remarks>
			unsafe void GetHotkey(ushort* pwHotkey);

			/// <summary>Sets a keyboard shortcut (hot key) for a Shell link object.</summary>
			/// <param name="wHotkey">
			/// <para>Type: <b>WORD</b> The new keyboard shortcut. The virtual key code is in the low-order byte, and the modifier flags are in the high-order byte. The modifier flags can be a combination of the values specified in the description of the <a href="https://docs.microsoft.com/windows/desktop/api/shobjidl_core/nf-shobjidl_core-ishelllinka-gethotkey">IShellLink::GetHotkey</a> method.</para>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//shobjidl_core/nf-shobjidl_core-ishelllinkw-sethotkey#parameters">Read more on docs.microsoft.com</see>.</para>
			/// </param>
			/// <returns>
			/// <para>Type: <b>HRESULT</b> If this method succeeds, it returns <b xmlns:loc="http://microsoft.com/wdcml/l10n">S_OK</b>. Otherwise, it returns an <b xmlns:loc="http://microsoft.com/wdcml/l10n">HRESULT</b> error code.</para>
			/// </returns>
			/// <remarks>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//shobjidl_core/nf-shobjidl_core-ishelllinkw-sethotkey">Learn more about this API from docs.microsoft.com</see>.</para>
			/// </remarks>
			void SetHotkey(ushort wHotkey);

			/// <summary>Gets the show command for a Shell link object.</summary>
			/// <param name="piShowCmd">
			/// <para>Type: <b>int*</b> A pointer to the command. The following commands are supported.</para>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//shobjidl_core/nf-shobjidl_core-ishelllinkw-getshowcmd#parameters">Read more on docs.microsoft.com</see>.</para>
			/// </param>
			/// <returns>
			/// <para>Type: <b>HRESULT</b> If this method succeeds, it returns <b xmlns:loc="http://microsoft.com/wdcml/l10n">S_OK</b>. Otherwise, it returns an <b xmlns:loc="http://microsoft.com/wdcml/l10n">HRESULT</b> error code.</para>
			/// </returns>
			/// <remarks>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//shobjidl_core/nf-shobjidl_core-ishelllinkw-getshowcmd">Learn more about this API from docs.microsoft.com</see>.</para>
			/// </remarks>
			unsafe void GetShowCmd(int* piShowCmd);

			/// <summary>Sets the show command for a Shell link object. The show command sets the initial show state of the window.</summary>
			/// <param name="iShowCmd">
			/// <para>Type: <b>int</b> Command. <b>SetShowCmd</b> accepts one of the following <a href="https://docs.microsoft.com/windows/desktop/api/winuser/nf-winuser-showwindow">ShowWindow</a> commands.</para>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//shobjidl_core/nf-shobjidl_core-ishelllinkw-setshowcmd#parameters">Read more on docs.microsoft.com</see>.</para>
			/// </param>
			/// <returns>
			/// <para>Type: <b>HRESULT</b> If this method succeeds, it returns <b xmlns:loc="http://microsoft.com/wdcml/l10n">S_OK</b>. Otherwise, it returns an <b xmlns:loc="http://microsoft.com/wdcml/l10n">HRESULT</b> error code.</para>
			/// </returns>
			/// <remarks>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//shobjidl_core/nf-shobjidl_core-ishelllinkw-setshowcmd">Learn more about this API from docs.microsoft.com</see>.</para>
			/// </remarks>
			void SetShowCmd(int iShowCmd);

			/// <summary>Gets the location (path and index) of the icon for a Shell link object.</summary>
			/// <param name="pszIconPath">
			/// <para>Type: <b>LPTSTR</b> The address of a buffer that receives the path of the file containing the icon.</para>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//shobjidl_core/nf-shobjidl_core-ishelllinkw-geticonlocation#parameters">Read more on docs.microsoft.com</see>.</para>
			/// </param>
			/// <param name="cch">
			/// <para>Type: <b>int</b> The maximum number of characters to copy to the buffer pointed to by the <i>pszIconPath</i> parameter.</para>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//shobjidl_core/nf-shobjidl_core-ishelllinkw-geticonlocation#parameters">Read more on docs.microsoft.com</see>.</para>
			/// </param>
			/// <param name="piIcon">
			/// <para>Type: <b>int*</b> The address of a value that receives the index of the icon.</para>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//shobjidl_core/nf-shobjidl_core-ishelllinkw-geticonlocation#parameters">Read more on docs.microsoft.com</see>.</para>
			/// </param>
			/// <returns>
			/// <para>Type: <b>HRESULT</b> If this method succeeds, it returns <b xmlns:loc="http://microsoft.com/wdcml/l10n">S_OK</b>. Otherwise, it returns an <b xmlns:loc="http://microsoft.com/wdcml/l10n">HRESULT</b> error code.</para>
			/// </returns>
			/// <remarks>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//shobjidl_core/nf-shobjidl_core-ishelllinkw-geticonlocation">Learn more about this API from docs.microsoft.com</see>.</para>
			/// </remarks>
			unsafe void GetIconLocation(winmdroot.Foundation.PWSTR pszIconPath, int cch, int* piIcon);

			/// <summary>Sets the location (path and index) of the icon for a Shell link object.</summary>
			/// <param name="pszIconPath">
			/// <para>Type: <b>LPCTSTR</b> The address of a buffer to contain the path of the file containing the icon.</para>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//shobjidl_core/nf-shobjidl_core-ishelllinkw-seticonlocation#parameters">Read more on docs.microsoft.com</see>.</para>
			/// </param>
			/// <param name="iIcon">
			/// <para>Type: <b>int</b> The index of the icon.</para>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//shobjidl_core/nf-shobjidl_core-ishelllinkw-seticonlocation#parameters">Read more on docs.microsoft.com</see>.</para>
			/// </param>
			/// <returns>
			/// <para>Type: <b>HRESULT</b> If this method succeeds, it returns <b xmlns:loc="http://microsoft.com/wdcml/l10n">S_OK</b>. Otherwise, it returns an <b xmlns:loc="http://microsoft.com/wdcml/l10n">HRESULT</b> error code.</para>
			/// </returns>
			/// <remarks>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//shobjidl_core/nf-shobjidl_core-ishelllinkw-seticonlocation">Learn more about this API from docs.microsoft.com</see>.</para>
			/// </remarks>
			void SetIconLocation(winmdroot.Foundation.PCWSTR pszIconPath, int iIcon);

			/// <summary>Sets the relative path to the Shell link object.</summary>
			/// <param name="pszPathRel">
			/// <para>Type: <b>LPCTSTR</b> The address of a buffer that contains the fully-qualified path of the shortcut file, relative to which the shortcut resolution should be performed. It should be a file name, not a folder name.</para>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//shobjidl_core/nf-shobjidl_core-ishelllinkw-setrelativepath#parameters">Read more on docs.microsoft.com</see>.</para>
			/// </param>
			/// <param name="dwReserved">
			/// <para>Type: <b>DWORD</b> Reserved. Set this parameter to zero.</para>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//shobjidl_core/nf-shobjidl_core-ishelllinkw-setrelativepath#parameters">Read more on docs.microsoft.com</see>.</para>
			/// </param>
			/// <returns>
			/// <para>Type: <b>HRESULT</b> If this method succeeds, it returns <b xmlns:loc="http://microsoft.com/wdcml/l10n">S_OK</b>. Otherwise, it returns an <b xmlns:loc="http://microsoft.com/wdcml/l10n">HRESULT</b> error code.</para>
			/// </returns>
			/// <remarks>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//shobjidl_core/nf-shobjidl_core-ishelllinkw-setrelativepath">Learn more about this API from docs.microsoft.com</see>.</para>
			/// </remarks>
			void SetRelativePath(winmdroot.Foundation.PCWSTR pszPathRel, uint dwReserved);

			/// <summary>Attempts to find the target of a Shell link, even if it has been moved or renamed.</summary>
			/// <param name="hwnd">
			/// <para>Type: <b>HWND</b> A handle to the window that the Shell will use as the parent for a dialog box. The Shell displays the dialog box if it needs to prompt the user for more information while resolving a Shell link.</para>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//shobjidl_core/nf-shobjidl_core-ishelllinkw-resolve#parameters">Read more on docs.microsoft.com</see>.</para>
			/// </param>
			/// <param name="fFlags">Type: <b>DWORD</b></param>
			/// <returns>
			/// <para>Type: <b>HRESULT</b> If this method succeeds, it returns <b xmlns:loc="http://microsoft.com/wdcml/l10n">S_OK</b>. Otherwise, it returns an <b xmlns:loc="http://microsoft.com/wdcml/l10n">HRESULT</b> error code.</para>
			/// </returns>
			/// <remarks>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//shobjidl_core/nf-shobjidl_core-ishelllinkw-resolve">Learn more about this API from docs.microsoft.com</see>.</para>
			/// </remarks>
			void Resolve(winmdroot.Foundation.HWND hwnd, uint fFlags);

			/// <summary>Sets the path and file name for the target of a Shell link object.</summary>
			/// <param name="pszFile">
			/// <para>Type: <b>LPCTSTR</b> The address of a buffer that contains the new path.</para>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//shobjidl_core/nf-shobjidl_core-ishelllinkw-setpath#parameters">Read more on docs.microsoft.com</see>.</para>
			/// </param>
			/// <returns>
			/// <para>Type: <b>HRESULT</b> If this method succeeds, it returns <b xmlns:loc="http://microsoft.com/wdcml/l10n">S_OK</b>. Otherwise, it returns an <b xmlns:loc="http://microsoft.com/wdcml/l10n">HRESULT</b> error code.</para>
			/// </returns>
			/// <remarks>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//shobjidl_core/nf-shobjidl_core-ishelllinkw-setpath">Learn more about this API from docs.microsoft.com</see>.</para>
			/// </remarks>
			void SetPath(winmdroot.Foundation.PCWSTR pszFile);
		}
	}
}
