// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

#pragma warning disable CS1591,CS1573,CS0465,CS0649,CS8019,CS1570,CS1584,CS1658,CS0436,CS8981
using global::System;
using global::System.Diagnostics;
using global::System.Diagnostics.CodeAnalysis;
using global::System.Runtime.CompilerServices;
using global::System.Runtime.InteropServices;
using global::System.Runtime.Versioning;
using winmdroot = global::Windows.Win32;
namespace Windows.Win32
{
	namespace System.Com
	{
		[Flags]
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.164-beta+187018bf44")]
		internal enum ADVANCED_FEATURE_FLAGS : ushort
		{
			FADF_AUTO = 0x0001,
			FADF_STATIC = 0x0002,
			FADF_EMBEDDED = 0x0004,
			FADF_FIXEDSIZE = 0x0010,
			FADF_RECORD = 0x0020,
			FADF_HAVEIID = 0x0040,
			FADF_HAVEVARTYPE = 0x0080,
			FADF_BSTR = 0x0100,
			FADF_UNKNOWN = 0x0200,
			FADF_DISPATCH = 0x0400,
			FADF_VARIANT = 0x0800,
			FADF_RESERVED = 0xF008,
		}
	}
}
