// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

#pragma warning disable CS1591,CS1573,CS0465,CS0649,CS8019,CS1570,CS1584,CS1658,CS0436,CS8981
using global::System;
using global::System.Diagnostics;
using global::System.Diagnostics.CodeAnalysis;
using global::System.Runtime.CompilerServices;
using global::System.Runtime.InteropServices;
using global::System.Runtime.Versioning;
using winmdroot = global::Windows.Win32;
namespace Windows.Win32
{
	[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.164-beta+187018bf44")]
	internal static partial class System_Com_IStream_Extensions
	{
		/// <inheritdoc cref="winmdroot.System.Com.IStream.Stat(winmdroot.System.Com.STATSTG*, winmdroot.System.Com.STATFLAG)"/>
		internal static unsafe void Stat(this winmdroot.System.Com.IStream @this, out winmdroot.System.Com.STATSTG pstatstg, winmdroot.System.Com.STATFLAG grfStatFlag)
		{
			fixed (winmdroot.System.Com.STATSTG* pstatstgLocal = &pstatstg)
			{
				@this.Stat(pstatstgLocal, grfStatFlag);
			}
		}
	}
}
