// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

#pragma warning disable CS1591,CS1573,CS0465,CS0649,CS8019,CS1570,CS1584,CS1658,CS0436,CS8981
using global::System;
using global::System.Diagnostics;
using global::System.Diagnostics.CodeAnalysis;
using global::System.Runtime.CompilerServices;
using global::System.Runtime.InteropServices;
using global::System.Runtime.Versioning;
using winmdroot = global::Windows.Win32;
namespace Windows.Win32
{
	namespace System.Com
	{
		[Guid("00020400-0000-0000-C000-000000000046")]
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.164-beta+187018bf44")]
		internal unsafe partial struct IDispatch_unmanaged
			:IComIID		{
			/// <inheritdoc cref="QueryInterface(global::System.Guid*, out object)"/>
			internal unsafe winmdroot.Foundation.HRESULT QueryInterface(in global::System.Guid riid, out object ppvObject)
			{
				fixed (global::System.Guid* riidLocal = &riid)
				{
					winmdroot.Foundation.HRESULT __result = this.QueryInterface(riidLocal, out ppvObject);
					return __result;
				}
			}

			public unsafe winmdroot.Foundation.HRESULT QueryInterface(global::System.Guid* riid, [MarshalAs(UnmanagedType.IUnknown)] out object ppvObject)
			{
				fixed (IDispatch_unmanaged* pThis = &this)
					return ((delegate *unmanaged [Stdcall]<IDispatch_unmanaged*,global::System.Guid* ,out object ,winmdroot.Foundation.HRESULT>)lpVtbl[0])(pThis, riid, out ppvObject);
			}

			public uint AddRef()
			{
				fixed (IDispatch_unmanaged* pThis = &this)
					return ((delegate *unmanaged [Stdcall]<IDispatch_unmanaged*,uint>)lpVtbl[1])(pThis);
			}

			public uint Release()
			{
				fixed (IDispatch_unmanaged* pThis = &this)
					return ((delegate *unmanaged [Stdcall]<IDispatch_unmanaged*,uint>)lpVtbl[2])(pThis);
			}

			/// <inheritdoc cref="GetTypeInfoCount(uint*)"/>
			internal unsafe void GetTypeInfoCount(out uint pctinfo)
			{
				fixed (uint* pctinfoLocal = &pctinfo)
				{
					this.GetTypeInfoCount(pctinfoLocal);
				}
			}

			public unsafe void GetTypeInfoCount(uint* pctinfo)
			{
				fixed (IDispatch_unmanaged* pThis = &this)
					((delegate *unmanaged [Stdcall]<IDispatch_unmanaged*,uint* ,winmdroot.Foundation.HRESULT>)lpVtbl[3])(pThis, pctinfo).ThrowOnFailure();
			}

			public void GetTypeInfo(uint iTInfo, uint lcid, out winmdroot.System.Com.ITypeInfo ppTInfo)
			{
				fixed (IDispatch_unmanaged* pThis = &this)
					((delegate *unmanaged [Stdcall]<IDispatch_unmanaged*,uint ,uint ,out winmdroot.System.Com.ITypeInfo ,winmdroot.Foundation.HRESULT>)lpVtbl[4])(pThis, iTInfo, lcid, out ppTInfo).ThrowOnFailure();
			}

			/// <inheritdoc cref="GetIDsOfNames(global::System.Guid*, winmdroot.Foundation.PWSTR*, uint, uint, int*)"/>
			internal unsafe void GetIDsOfNames(in global::System.Guid riid, Span<winmdroot.Foundation.PWSTR> rgszNames, uint lcid, Span<int> rgDispId)
			{
				fixed (int* rgDispIdLocal = rgDispId)
				{
					fixed (winmdroot.Foundation.PWSTR* rgszNamesLocal = rgszNames)
					{
						fixed (global::System.Guid* riidLocal = &riid)
						{
							if (rgszNames.Length != rgDispId.Length)throw new ArgumentException();
							this.GetIDsOfNames(riidLocal, rgszNamesLocal, (uint )rgDispId.Length, lcid, rgDispIdLocal);
						}
					}
				}
			}

			public unsafe void GetIDsOfNames(global::System.Guid* riid, winmdroot.Foundation.PWSTR* rgszNames, uint cNames, uint lcid, int* rgDispId)
			{
				fixed (IDispatch_unmanaged* pThis = &this)
					((delegate *unmanaged [Stdcall]<IDispatch_unmanaged*,global::System.Guid* ,winmdroot.Foundation.PWSTR* ,uint ,uint ,int* ,winmdroot.Foundation.HRESULT>)lpVtbl[5])(pThis, riid, rgszNames, cNames, lcid, rgDispId).ThrowOnFailure();
			}

			/// <inheritdoc cref="Invoke(int, global::System.Guid*, uint, winmdroot.System.Com.DISPATCH_FLAGS, in winmdroot.System.Com.DISPPARAMS, out object, out winmdroot.System.Com.EXCEPINFO, uint*)"/>
			internal unsafe void Invoke(int dispIdMember, in global::System.Guid riid, uint lcid, winmdroot.System.Com.DISPATCH_FLAGS wFlags, in winmdroot.System.Com.DISPPARAMS pDispParams, out object pVarResult, out winmdroot.System.Com.EXCEPINFO pExcepInfo, uint* puArgErr)
			{
				fixed (global::System.Guid* riidLocal = &riid)
				{
					this.Invoke(dispIdMember, riidLocal, lcid, wFlags, in pDispParams, out pVarResult, out pExcepInfo, puArgErr);
				}
			}

			public unsafe void Invoke(int dispIdMember, global::System.Guid* riid, uint lcid, winmdroot.System.Com.DISPATCH_FLAGS wFlags, in winmdroot.System.Com.DISPPARAMS pDispParams, [MarshalAs(UnmanagedType.Struct)] out object pVarResult, out winmdroot.System.Com.EXCEPINFO pExcepInfo, [Optional] uint* puArgErr)
			{
				fixed (IDispatch_unmanaged* pThis = &this)
					((delegate *unmanaged [Stdcall]<IDispatch_unmanaged*,int ,global::System.Guid* ,uint ,winmdroot.System.Com.DISPATCH_FLAGS ,in winmdroot.System.Com.DISPPARAMS ,out object ,out winmdroot.System.Com.EXCEPINFO ,uint* ,winmdroot.Foundation.HRESULT>)lpVtbl[6])(pThis, dispIdMember, riid, lcid, wFlags, in pDispParams, out pVarResult, out pExcepInfo, puArgErr).ThrowOnFailure();
			}
			private void** lpVtbl;
			/// <summary>The IID guid for this interface.</summary>
			/// <value>{00020400-0000-0000-c000-000000000046}</value>
			internal static readonly Guid IID_Guid = new Guid(0x00020400, 0x0000, 0x0000, 0xC0, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x46);

			static ref readonly Guid IComIID.Guid			{
								[MethodImpl(MethodImplOptions.AggressiveInlining)]
get
				{
					ReadOnlySpan<byte> data = new byte[]					{
0x00,0x04,0x02,0x00,0x00,0x00,0x00,0x00,0xC0,0x00,0x00,0x00,0x00,0x00,0x00,0x46					};
					return ref Unsafe.As<byte,Guid>(ref MemoryMarshal.GetReference(data));
				}
			}
		}
	}
}
