// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

#pragma warning disable CS1591,CS1573,CS0465,CS0649,CS8019,CS1570,CS1584,CS1658,CS0436,CS8981
using global::System;
using global::System.Diagnostics;
using global::System.Diagnostics.CodeAnalysis;
using global::System.Runtime.CompilerServices;
using global::System.Runtime.InteropServices;
using global::System.Runtime.Versioning;
using winmdroot = global::Windows.Win32;
namespace Windows.Win32
{
	namespace System.Com
	{
		/// <summary>Specifies function flags.</summary>
		/// <remarks>
		/// <para>FUNCFLAG_FHIDDEN means that the property should never be shown in object browsers, property browsers, and so on. This function is useful for removing items from an object model. Code can bind to the member, but the user will never know that the member exists. FUNCFLAG_FNONBROWSABLE means that the property should not be displayed in a properties browser. It is used in circumstances in which an error would occur if the property were shown in a properties browser. FUNCFLAG_FRESRICTED means that macro-oriented programmers should not be allowed to access this member. These members are usually treated as _FHIDDEN by tools such as Visual Basic, with the main difference being that code cannot bind to those members.</para>
		/// <para><see href="https://docs.microsoft.com/windows/win32/api//oaidl/ne-oaidl-funcflags#">Read more on docs.microsoft.com</see>.</para>
		/// </remarks>
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.164-beta+187018bf44")]
		internal enum FUNCFLAGS : ushort
		{
			/// <summary>The function should not be accessible from macro languages. This flag is intended for system-level functions or functions that type browsers should not display.</summary>
			FUNCFLAG_FRESTRICTED = 1,
			/// <summary>The function returns an object that is a source of events.</summary>
			FUNCFLAG_FSOURCE = 2,
			/// <summary>The function that supports data binding.</summary>
			FUNCFLAG_FBINDABLE = 4,
			/// <summary>When set, any call to a method that sets the property results first in a call to <b>IPropertyNotifySink::OnRequestEdit</b>. The implementation of <b>OnRequestEdit</b> determines if the call is allowed to set the property.</summary>
			FUNCFLAG_FREQUESTEDIT = 8,
			/// <summary>The function that is displayed to the user as bindable. FUNC_FBINDABLE must also be set.</summary>
			FUNCFLAG_FDISPLAYBIND = 16,
			/// <summary>The function that best represents the object. Only one function in a type information can have this attribute.</summary>
			FUNCFLAG_FDEFAULTBIND = 32,
			/// <summary>The function should not be displayed to the user, although it exists and is bindable.</summary>
			FUNCFLAG_FHIDDEN = 64,
			/// <summary>The function supports <b>GetLastError</b>. If an error occurs during the function, the caller can call <b>GetLastError</b> to retrieve the error code.</summary>
			FUNCFLAG_FUSESGETLASTERROR = 128,
			/// <summary>Permits an optimization in which the compiler looks for a member named xyz on the type of abc. If such a member is found and is flagged as an accessor function for an element of the default collection, then a call is generated to that member function. Permitted on members in dispinterfaces and interfaces; not permitted on modules. For more information, refer to defaultcollelem in Type Libraries and the Object Description Language.</summary>
			FUNCFLAG_FDEFAULTCOLLELEM = 256,
			/// <summary>The type information member is the default member for display in the user interface.</summary>
			FUNCFLAG_FUIDEFAULT = 512,
			/// <summary>The property appears in an object browser, but not in a properties browser.</summary>
			FUNCFLAG_FNONBROWSABLE = 1024,
			/// <summary>Tags the interface as having default behaviors.</summary>
			FUNCFLAG_FREPLACEABLE = 2048,
			/// <summary>Mapped as individual bindable properties.</summary>
			FUNCFLAG_FIMMEDIATEBIND = 4096,
		}
	}
}
