// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

#pragma warning disable CS1591,CS1573,CS0465,CS0649,CS8019,CS1570,CS1584,CS1658,CS0436,CS8981
using global::System;
using global::System.Diagnostics;
using global::System.Diagnostics.CodeAnalysis;
using global::System.Runtime.CompilerServices;
using global::System.Runtime.InteropServices;
using global::System.Runtime.Versioning;
using winmdroot = global::Windows.Win32;
namespace Windows.Win32
{
	namespace System.Ole
	{
		[Flags]
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.164-beta+187018bf44")]
		internal enum PARAMFLAGS : ushort
		{
			PARAMFLAG_NONE = 0x0000,
			PARAMFLAG_FIN = 0x0001,
			PARAMFLAG_FOUT = 0x0002,
			PARAMFLAG_FLCID = 0x0004,
			PARAMFLAG_FRETVAL = 0x0008,
			PARAMFLAG_FOPT = 0x0010,
			PARAMFLAG_FHASDEFAULT = 0x0020,
			PARAMFLAG_FHASCUSTDATA = 0x0040,
		}
	}
}
