// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

#pragma warning disable CS1591,CS1573,CS0465,CS0649,CS8019,CS1570,CS1584,CS1658,CS0436,CS8981
using global::System;
using global::System.Diagnostics;
using global::System.Diagnostics.CodeAnalysis;
using global::System.Runtime.CompilerServices;
using global::System.Runtime.InteropServices;
using global::System.Runtime.Versioning;
using winmdroot = global::Windows.Win32;
namespace Windows.Win32
{
	namespace System.Com
	{
		/// <summary>Describes a pointer.</summary>
		/// <remarks>
		/// <para><see href="https://docs.microsoft.com/windows/win32/api//oaidl/ns-oaidl-bindptr">Learn more about this API from docs.microsoft.com</see>.</para>
		/// </remarks>
		[StructLayout(LayoutKind.Explicit)]
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.164-beta+187018bf44")]
		internal partial struct BINDPTR
		{
			/// <summary>Pointer to a function.</summary>
			[FieldOffset(0)]
			internal unsafe winmdroot.System.Com.FUNCDESC_unmanaged* lpfuncdesc;
			/// <summary>Pointer to a variable, constant, or data member.</summary>
			[FieldOffset(0)]
			internal unsafe winmdroot.System.Com.VARDESC_unmanaged* lpvardesc;
			/// <summary>The <a href="https://docs.microsoft.com/previous-versions/windows/desktop/api/oaidl/nn-oaidl-itypecomp">ITypeComp</a> that binds the pointer.</summary>
			[FieldOffset(0)]
			internal unsafe winmdroot.System.Com.ITypeComp_unmanaged* lptcomp;
		}
	}
}
