// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

#pragma warning disable CS1591,CS1573,CS0465,CS0649,CS8019,CS1570,CS1584,CS1658,CS0436,CS8981
using global::System;
using global::System.Diagnostics;
using global::System.Diagnostics.CodeAnalysis;
using global::System.Runtime.CompilerServices;
using global::System.Runtime.InteropServices;
using global::System.Runtime.Versioning;
using winmdroot = global::Windows.Win32;
namespace Windows.Win32
{

	/// <content>
	/// Contains extern methods from "COMCTL32.dll".
	/// </content>
	internal static partial class PInvoke
	{
		/// <summary>Destroys an image list.</summary>
		/// <param name="himl">
		/// <para>Type: <b>HIMAGELIST</b> A handle to the image list to destroy.</para>
		/// <para><see href="https://docs.microsoft.com/windows/win32/api//commctrl/nf-commctrl-imagelist_destroy#parameters">Read more on docs.microsoft.com</see>.</para>
		/// </param>
		/// <returns>
		/// <para>Type: <b><a href="/windows/desktop/WinProg/windows-data-types">BOOL</a></b> Returns nonzero if successful, or zero otherwise.</para>
		/// </returns>
		/// <remarks>
		/// <para><see href="https://docs.microsoft.com/windows/win32/api//commctrl/nf-commctrl-imagelist_destroy">Learn more about this API from docs.microsoft.com</see>.</para>
		/// </remarks>
		[DllImport("COMCTL32.dll", ExactSpelling = true)]
		[DefaultDllImportSearchPaths(DllImportSearchPath.System32)]
		[SupportedOSPlatform("windows6.0.6000")]
		internal static extern winmdroot.Foundation.BOOL ImageList_Destroy(winmdroot.UI.Controls.HIMAGELIST himl);
	}
}
