// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

#pragma warning disable CS1591,CS1573,CS0465,CS0649,CS8019,CS1570,CS1584,CS1658,CS0436,CS8981
using global::System;
using global::System.Diagnostics;
using global::System.Diagnostics.CodeAnalysis;
using global::System.Runtime.CompilerServices;
using global::System.Runtime.InteropServices;
using global::System.Runtime.Versioning;
using winmdroot = global::Windows.Win32;
namespace Windows.Win32
{
	namespace System.Com
	{
		[Guid("00020402-0000-0000-C000-000000000046"),InterfaceType(ComInterfaceType.InterfaceIsIUnknown),ComImport()]
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.164-beta+187018bf44")]
		internal interface ITypeLib
		{
			/// <summary>Provides the number of type descriptions that are in a type library.</summary>
			/// <returns>The number of type descriptions in the type library.</returns>
			/// <remarks>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//oaidl/nf-oaidl-itypelib-gettypeinfocount">Learn more about this API from docs.microsoft.com</see>.</para>
			/// </remarks>
						[PreserveSig()]
uint GetTypeInfoCount();

			/// <summary>Retrieves the specified type description in the library.</summary>
			/// <param name="index">The index of the interface to be returned.</param>
			/// <param name="ppTInfo">If successful, returns a pointer to the pointer to the <a href="https://docs.microsoft.com/previous-versions/windows/desktop/api/oaidl/nn-oaidl-itypeinfo">ITypeInfo</a> interface.</param>
			/// <returns>
			/// <para>This method can return one of these values. </para>
			/// <para>This doc was truncated.</para>
			/// </returns>
			/// <remarks>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//oaidl/nf-oaidl-itypelib-gettypeinfo">Learn more about this API from docs.microsoft.com</see>.</para>
			/// </remarks>
			void GetTypeInfo(uint index, out winmdroot.System.Com.ITypeInfo ppTInfo);

			/// <summary>Retrieves the type of a type description.</summary>
			/// <param name="index">The index of the type description within the type library.</param>
			/// <param name="pTKind">The <a href="https://docs.microsoft.com/windows/desktop/api/oaidl/ne-oaidl-typekind">TYPEKIND</a> enumeration value for the type description.</param>
			/// <returns>
			/// <para>This method can return one of these values. </para>
			/// <para>This doc was truncated.</para>
			/// </returns>
			/// <remarks>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//oaidl/nf-oaidl-itypelib-gettypeinfotype">Learn more about this API from docs.microsoft.com</see>.</para>
			/// </remarks>
			unsafe void GetTypeInfoType(uint index, winmdroot.System.Com.TYPEKIND* pTKind);

			/// <summary>Retrieves the type description that corresponds to the specified GUID.</summary>
			/// <param name="guid">The GUID of the type description.</param>
			/// <param name="ppTinfo">The <a href="https://docs.microsoft.com/previous-versions/windows/desktop/api/oaidl/nn-oaidl-itypeinfo">ITypeInfo</a> interface.</param>
			/// <returns>
			/// <para>This method can return one of these values. </para>
			/// <para>This doc was truncated.</para>
			/// </returns>
			/// <remarks>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//oaidl/nf-oaidl-itypelib-gettypeinfoofguid">Learn more about this API from docs.microsoft.com</see>.</para>
			/// </remarks>
			unsafe void GetTypeInfoOfGuid(global::System.Guid* guid, out winmdroot.System.Com.ITypeInfo ppTinfo);

			/// <summary>Retrieves the structure that contains the library's attributes.</summary>
			/// <param name="ppTLibAttr">The library's attributes.</param>
			/// <returns>
			/// <para>This method can return one of these values. </para>
			/// <para>This doc was truncated.</para>
			/// </returns>
			/// <remarks>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//oaidl/nf-oaidl-itypelib-getlibattr">Learn more about this API from docs.microsoft.com</see>.</para>
			/// </remarks>
			unsafe void GetLibAttr(winmdroot.System.Com.TLIBATTR** ppTLibAttr);

			/// <summary>Enables a client compiler to bind to the types, variables, constants, and global functions for a library.</summary>
			/// <param name="ppTComp">The <a href="https://docs.microsoft.com/previous-versions/windows/desktop/api/oaidl/nn-oaidl-itypecomp">ITypeComp</a> instance for this <a href="https://docs.microsoft.com/previous-versions/windows/desktop/api/oaidl/nn-oaidl-itypelib">ITypeLib</a>. A client compiler uses the methods in the <b>ITypeComp</b> interface to bind to types in <b>ITypeLib</b>, as well as to the global functions, variables, and constants defined in <b>ITypeLib</b></param>
			/// <returns>
			/// <para>This method can return one of these values. </para>
			/// <para>This doc was truncated.</para>
			/// </returns>
			/// <remarks>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//oaidl/nf-oaidl-itypelib-gettypecomp">Learn more about this API from docs.microsoft.com</see>.</para>
			/// </remarks>
			void GetTypeComp(out winmdroot.System.Com.ITypeComp ppTComp);

			/// <summary>Retrieves the documentation string for the library, the complete Help file name and path, and the context identifier for the library Help topic in the Help file.</summary>
			/// <param name="index">The index of the type description whose documentation is to be returned. If <i>index</i> is -1, then the documentation for the library itself is returned.</param>
			/// <param name="pBstrName">The name of the specified item. If the caller does not need the item name, then <i>pBstrName</i> can be null.</param>
			/// <param name="pBstrDocString">The documentation string for the specified item. If the caller does not need the documentation string, then <i>pBstrDocString</i> can be null..</param>
			/// <param name="pdwHelpContext">The Help context identifier (ID) associated with the specified item. If the caller does not need the Help context ID, then <i>pdwHelpContext</i> can be null.</param>
			/// <param name="pBstrHelpFile">The fully qualified name of the Help file. If the caller does not need the Help file name, then <i>pBstrHelpFile</i> can be null.</param>
			/// <returns>
			/// <para>This method can return one of these values. </para>
			/// <para>This doc was truncated.</para>
			/// </returns>
			/// <remarks>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//oaidl/nf-oaidl-itypelib-getdocumentation">Learn more about this API from docs.microsoft.com</see>.</para>
			/// </remarks>
			unsafe void GetDocumentation(int index, [Optional] winmdroot.Foundation.BSTR* pBstrName, [Optional] winmdroot.Foundation.BSTR* pBstrDocString, uint* pdwHelpContext, [Optional] winmdroot.Foundation.BSTR* pBstrHelpFile);

			/// <summary>Indicates whether a passed-in string contains the name of a type or member described in the library.</summary>
			/// <param name="szNameBuf">The string to test. If this method is successful, <i>szNameBuf</i> is modified to match the case (capitalization) found in the type library.</param>
			/// <param name="lHashVal">The hash value of <i>szNameBuf</i>.</param>
			/// <param name="pfName">True if <i>szNameBuf</i> was found in the type library; otherwise false.</param>
			/// <returns>
			/// <para>This method can return one of these values. </para>
			/// <para>This doc was truncated.</para>
			/// </returns>
			/// <remarks>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//oaidl/nf-oaidl-itypelib-isname">Learn more about this API from docs.microsoft.com</see>.</para>
			/// </remarks>
			unsafe void IsName(winmdroot.Foundation.PWSTR szNameBuf, uint lHashVal, winmdroot.Foundation.BOOL* pfName);

			/// <summary>Finds occurrences of a type description in a type library. This may be used to quickly verify that a name exists in a type library.</summary>
			/// <param name="szNameBuf">The name to search for.</param>
			/// <param name="lHashVal">A hash value to speed up the search, computed by the <a href="https://docs.microsoft.com/previous-versions/windows/desktop/api/oleauto/nf-oleauto-lhashvalofnamesys">LHashValOfNameSys</a> function. If <i>lHashVal</i> = 0, a value is computed.</param>
			/// <param name="ppTInfo">An array of pointers to the type descriptions that contain the name specified in <i>szNameBuf</i>. This parameter cannot be null.</param>
			/// <param name="rgMemId">An array of the found items; <i>rgMemId</i>[<i>i</i>] is the MEMBERID that indexes into the type description specified by <i>ppTInfo</i>[<i>i</i>]. This parameter cannot be null.</param>
			/// <param name="pcFound">
			/// <para>On entry, indicates how many instances to look for. For example, *<i>pcFound</i> = 1 can be called to find the first occurrence. The search stops when one is found. On exit, indicates the number of instances that were found. If the in and out values of *<i>pcFound</i> are identical, there may be more type descriptions that contain the name.</para>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//oaidl/nf-oaidl-itypelib-findname#parameters">Read more on docs.microsoft.com</see>.</para>
			/// </param>
			/// <returns>
			/// <para>This method can return one of these values. </para>
			/// <para>This doc was truncated.</para>
			/// </returns>
			/// <remarks>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//oaidl/nf-oaidl-itypelib-findname">Learn more about this API from docs.microsoft.com</see>.</para>
			/// </remarks>
			unsafe void FindName(winmdroot.Foundation.PWSTR szNameBuf, uint lHashVal, [Out] [MarshalAs(UnmanagedType.LPArray,SizeParamIndex = 4)] winmdroot.System.Com.ITypeInfo[] ppTInfo, int* rgMemId, ushort* pcFound);

			/// <summary>Releases the TLIBATTR originally obtained from GetLibAttr.</summary>
			/// <param name="pTLibAttr">The TLIBATTR to be freed.</param>
			/// <remarks>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//oaidl/nf-oaidl-itypelib-releasetlibattr">Learn more about this API from docs.microsoft.com</see>.</para>
			/// </remarks>
			[PreserveSig()]
			unsafe void ReleaseTLibAttr(winmdroot.System.Com.TLIBATTR* pTLibAttr);
		}
	}
}
