// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

#pragma warning disable CS1591,CS1573,CS0465,CS0649,CS8019,CS1570,CS1584,CS1658,CS0436,CS8981
using global::System;
using global::System.Diagnostics;
using global::System.Diagnostics.CodeAnalysis;
using global::System.Runtime.CompilerServices;
using global::System.Runtime.InteropServices;
using global::System.Runtime.Versioning;
using winmdroot = global::Windows.Win32;
namespace Windows.Win32
{
	namespace System.Ole
	{
		[Guid("0000002F-0000-0000-C000-000000000046")]
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.164-beta+187018bf44")]
		internal unsafe partial struct IRecordInfo_unmanaged
			:IComIID		{
			/// <inheritdoc cref="QueryInterface(global::System.Guid*, out object)"/>
			internal unsafe winmdroot.Foundation.HRESULT QueryInterface(in global::System.Guid riid, out object ppvObject)
			{
				fixed (global::System.Guid* riidLocal = &riid)
				{
					winmdroot.Foundation.HRESULT __result = this.QueryInterface(riidLocal, out ppvObject);
					return __result;
				}
			}

			public unsafe winmdroot.Foundation.HRESULT QueryInterface(global::System.Guid* riid, [MarshalAs(UnmanagedType.IUnknown)] out object ppvObject)
			{
				fixed (IRecordInfo_unmanaged* pThis = &this)
					return ((delegate *unmanaged [Stdcall]<IRecordInfo_unmanaged*,global::System.Guid* ,out object ,winmdroot.Foundation.HRESULT>)lpVtbl[0])(pThis, riid, out ppvObject);
			}

			public uint AddRef()
			{
				fixed (IRecordInfo_unmanaged* pThis = &this)
					return ((delegate *unmanaged [Stdcall]<IRecordInfo_unmanaged*,uint>)lpVtbl[1])(pThis);
			}

			public uint Release()
			{
				fixed (IRecordInfo_unmanaged* pThis = &this)
					return ((delegate *unmanaged [Stdcall]<IRecordInfo_unmanaged*,uint>)lpVtbl[2])(pThis);
			}

			public unsafe void RecordInit(void* pvNew)
			{
				fixed (IRecordInfo_unmanaged* pThis = &this)
					((delegate *unmanaged [Stdcall]<IRecordInfo_unmanaged*,void* ,winmdroot.Foundation.HRESULT>)lpVtbl[3])(pThis, pvNew).ThrowOnFailure();
			}

			public unsafe void RecordClear(void* pvExisting)
			{
				fixed (IRecordInfo_unmanaged* pThis = &this)
					((delegate *unmanaged [Stdcall]<IRecordInfo_unmanaged*,void* ,winmdroot.Foundation.HRESULT>)lpVtbl[4])(pThis, pvExisting).ThrowOnFailure();
			}

			public unsafe void RecordCopy(void* pvExisting, void* pvNew)
			{
				fixed (IRecordInfo_unmanaged* pThis = &this)
					((delegate *unmanaged [Stdcall]<IRecordInfo_unmanaged*,void* ,void* ,winmdroot.Foundation.HRESULT>)lpVtbl[5])(pThis, pvExisting, pvNew).ThrowOnFailure();
			}

			/// <inheritdoc cref="GetGuid(global::System.Guid*)"/>
			internal unsafe void GetGuid(out global::System.Guid pguid)
			{
				fixed (global::System.Guid* pguidLocal = &pguid)
				{
					this.GetGuid(pguidLocal);
				}
			}

			public unsafe void GetGuid(global::System.Guid* pguid)
			{
				fixed (IRecordInfo_unmanaged* pThis = &this)
					((delegate *unmanaged [Stdcall]<IRecordInfo_unmanaged*,global::System.Guid* ,winmdroot.Foundation.HRESULT>)lpVtbl[6])(pThis, pguid).ThrowOnFailure();
			}

			/// <inheritdoc cref="GetName(winmdroot.Foundation.BSTR*)"/>
			internal unsafe void GetName(out SysFreeStringSafeHandle pbstrName)
			{
				winmdroot.Foundation.BSTR pbstrNameLocal;
				this.GetName(&pbstrNameLocal);
				pbstrName = new SysFreeStringSafeHandle(pbstrNameLocal, ownsHandle: true);
			}

			public unsafe void GetName(winmdroot.Foundation.BSTR* pbstrName)
			{
				fixed (IRecordInfo_unmanaged* pThis = &this)
					((delegate *unmanaged [Stdcall]<IRecordInfo_unmanaged*,winmdroot.Foundation.BSTR* ,winmdroot.Foundation.HRESULT>)lpVtbl[7])(pThis, pbstrName).ThrowOnFailure();
			}

			/// <inheritdoc cref="GetSize(uint*)"/>
			internal unsafe void GetSize(out uint pcbSize)
			{
				fixed (uint* pcbSizeLocal = &pcbSize)
				{
					this.GetSize(pcbSizeLocal);
				}
			}

			public unsafe void GetSize(uint* pcbSize)
			{
				fixed (IRecordInfo_unmanaged* pThis = &this)
					((delegate *unmanaged [Stdcall]<IRecordInfo_unmanaged*,uint* ,winmdroot.Foundation.HRESULT>)lpVtbl[8])(pThis, pcbSize).ThrowOnFailure();
			}

			public void GetTypeInfo(out winmdroot.System.Com.ITypeInfo ppTypeInfo)
			{
				fixed (IRecordInfo_unmanaged* pThis = &this)
					((delegate *unmanaged [Stdcall]<IRecordInfo_unmanaged*,out winmdroot.System.Com.ITypeInfo ,winmdroot.Foundation.HRESULT>)lpVtbl[9])(pThis, out ppTypeInfo).ThrowOnFailure();
			}

			/// <inheritdoc cref="GetField(void*, winmdroot.Foundation.PCWSTR, out object)"/>
			internal unsafe void GetField(void* pvData, string szFieldName, out object pvarField)
			{
				fixed (char* szFieldNameLocal = szFieldName)
				{
					this.GetField(pvData, szFieldNameLocal, out pvarField);
				}
			}

			public unsafe void GetField(void* pvData, winmdroot.Foundation.PCWSTR szFieldName, [MarshalAs(UnmanagedType.Struct)] out object pvarField)
			{
				fixed (IRecordInfo_unmanaged* pThis = &this)
					((delegate *unmanaged [Stdcall]<IRecordInfo_unmanaged*,void* ,winmdroot.Foundation.PCWSTR ,out object ,winmdroot.Foundation.HRESULT>)lpVtbl[10])(pThis, pvData, szFieldName, out pvarField).ThrowOnFailure();
			}

			/// <inheritdoc cref="GetFieldNoCopy(void*, winmdroot.Foundation.PCWSTR, out object, void**)"/>
			internal unsafe void GetFieldNoCopy(void* pvData, string szFieldName, out object pvarField, out void* ppvDataCArray)
			{
				fixed (void** ppvDataCArrayLocal = &ppvDataCArray)
				{
					fixed (char* szFieldNameLocal = szFieldName)
					{
						this.GetFieldNoCopy(pvData, szFieldNameLocal, out pvarField, ppvDataCArrayLocal);
					}
				}
			}

			public unsafe void GetFieldNoCopy(void* pvData, winmdroot.Foundation.PCWSTR szFieldName, [MarshalAs(UnmanagedType.Struct)] out object pvarField, void** ppvDataCArray)
			{
				fixed (IRecordInfo_unmanaged* pThis = &this)
					((delegate *unmanaged [Stdcall]<IRecordInfo_unmanaged*,void* ,winmdroot.Foundation.PCWSTR ,out object ,void** ,winmdroot.Foundation.HRESULT>)lpVtbl[11])(pThis, pvData, szFieldName, out pvarField, ppvDataCArray).ThrowOnFailure();
			}

			/// <inheritdoc cref="PutField(winmdroot.System.Com.INVOKEKIND, void*, winmdroot.Foundation.PCWSTR, in object)"/>
			internal unsafe void PutField(winmdroot.System.Com.INVOKEKIND wFlags, void* pvData, string szFieldName, in object pvarField)
			{
				fixed (char* szFieldNameLocal = szFieldName)
				{
					this.PutField(wFlags, pvData, szFieldNameLocal, in pvarField);
				}
			}

			public unsafe void PutField(winmdroot.System.Com.INVOKEKIND wFlags, void* pvData, winmdroot.Foundation.PCWSTR szFieldName, [MarshalAs(UnmanagedType.Struct)] in object pvarField)
			{
				fixed (IRecordInfo_unmanaged* pThis = &this)
					((delegate *unmanaged [Stdcall]<IRecordInfo_unmanaged*,winmdroot.System.Com.INVOKEKIND ,void* ,winmdroot.Foundation.PCWSTR ,in object ,winmdroot.Foundation.HRESULT>)lpVtbl[12])(pThis, wFlags, pvData, szFieldName, in pvarField).ThrowOnFailure();
			}

			/// <inheritdoc cref="PutFieldNoCopy(winmdroot.System.Com.INVOKEKIND, void*, winmdroot.Foundation.PCWSTR, in object)"/>
			internal unsafe void PutFieldNoCopy(winmdroot.System.Com.INVOKEKIND wFlags, void* pvData, string szFieldName, in object pvarField)
			{
				fixed (char* szFieldNameLocal = szFieldName)
				{
					this.PutFieldNoCopy(wFlags, pvData, szFieldNameLocal, in pvarField);
				}
			}

			public unsafe void PutFieldNoCopy(winmdroot.System.Com.INVOKEKIND wFlags, void* pvData, winmdroot.Foundation.PCWSTR szFieldName, [MarshalAs(UnmanagedType.Struct)] in object pvarField)
			{
				fixed (IRecordInfo_unmanaged* pThis = &this)
					((delegate *unmanaged [Stdcall]<IRecordInfo_unmanaged*,winmdroot.System.Com.INVOKEKIND ,void* ,winmdroot.Foundation.PCWSTR ,in object ,winmdroot.Foundation.HRESULT>)lpVtbl[13])(pThis, wFlags, pvData, szFieldName, in pvarField).ThrowOnFailure();
			}

			/// <inheritdoc cref="GetFieldNames(uint*, winmdroot.Foundation.BSTR*)"/>
			internal unsafe void GetFieldNames(ref uint pcNames, out SysFreeStringSafeHandle rgBstrNames)
			{
				fixed (uint* pcNamesLocal = &pcNames)
				{
					winmdroot.Foundation.BSTR rgBstrNamesLocal;
					this.GetFieldNames(pcNamesLocal, &rgBstrNamesLocal);
					rgBstrNames = new SysFreeStringSafeHandle(rgBstrNamesLocal, ownsHandle: true);
				}
			}

			public unsafe void GetFieldNames(uint* pcNames, winmdroot.Foundation.BSTR* rgBstrNames)
			{
				fixed (IRecordInfo_unmanaged* pThis = &this)
					((delegate *unmanaged [Stdcall]<IRecordInfo_unmanaged*,uint* ,winmdroot.Foundation.BSTR* ,winmdroot.Foundation.HRESULT>)lpVtbl[14])(pThis, pcNames, rgBstrNames).ThrowOnFailure();
			}

			public winmdroot.Foundation.BOOL IsMatchingType(winmdroot.System.Ole.IRecordInfo pRecordInfo)
			{
				fixed (IRecordInfo_unmanaged* pThis = &this)
					return ((delegate *unmanaged [Stdcall]<IRecordInfo_unmanaged*,winmdroot.System.Ole.IRecordInfo ,winmdroot.Foundation.BOOL>)lpVtbl[15])(pThis, pRecordInfo);
			}

			public unsafe void* RecordCreate()
			{
				fixed (IRecordInfo_unmanaged* pThis = &this)
					return ((delegate *unmanaged [Stdcall]<IRecordInfo_unmanaged*,void*>)lpVtbl[16])(pThis);
			}

			/// <inheritdoc cref="RecordCreateCopy(void*, void**)"/>
			internal unsafe void RecordCreateCopy(void* pvSource, out void* ppvDest)
			{
				fixed (void** ppvDestLocal = &ppvDest)
				{
					this.RecordCreateCopy(pvSource, ppvDestLocal);
				}
			}

			public unsafe void RecordCreateCopy(void* pvSource, void** ppvDest)
			{
				fixed (IRecordInfo_unmanaged* pThis = &this)
					((delegate *unmanaged [Stdcall]<IRecordInfo_unmanaged*,void* ,void** ,winmdroot.Foundation.HRESULT>)lpVtbl[17])(pThis, pvSource, ppvDest).ThrowOnFailure();
			}

			public unsafe void RecordDestroy(void* pvRecord)
			{
				fixed (IRecordInfo_unmanaged* pThis = &this)
					((delegate *unmanaged [Stdcall]<IRecordInfo_unmanaged*,void* ,winmdroot.Foundation.HRESULT>)lpVtbl[18])(pThis, pvRecord).ThrowOnFailure();
			}
			private void** lpVtbl;
			/// <summary>The IID guid for this interface.</summary>
			/// <value>{0000002f-0000-0000-c000-000000000046}</value>
			internal static readonly Guid IID_Guid = new Guid(0x0000002F, 0x0000, 0x0000, 0xC0, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x46);

			static ref readonly Guid IComIID.Guid			{
								[MethodImpl(MethodImplOptions.AggressiveInlining)]
get
				{
					ReadOnlySpan<byte> data = new byte[]					{
0x2F,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0xC0,0x00,0x00,0x00,0x00,0x00,0x00,0x46					};
					return ref Unsafe.As<byte,Guid>(ref MemoryMarshal.GetReference(data));
				}
			}
		}
	}
}
