// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

#pragma warning disable CS1591,CS1573,CS0465,CS0649,CS8019,CS1570,CS1584,CS1658,CS0436,CS8981
using global::System;
using global::System.Diagnostics;
using global::System.Diagnostics.CodeAnalysis;
using global::System.Runtime.CompilerServices;
using global::System.Runtime.InteropServices;
using global::System.Runtime.Versioning;
using winmdroot = global::Windows.Win32;
namespace Windows.Win32
{
	namespace UI.Shell.PropertiesSystem
	{
		/// <summary>Specifies the FMTID/PID identifier that programmatically identifies a property. Replaces SHCOLUMNID.</summary>
		/// <remarks>
		/// <para>As of Windows Vista, the <a href="https://docs.microsoft.com/windows/desktop/shell/objects">SHCOLUMNID</a> structure is simply an alias for <a href="https://docs.microsoft.com/windows/desktop/api/wtypes/ns-wtypes-propertykey">PROPERTYKEY</a>, as shown in this declaration from Shobjidl.h.</para>
		/// <para></para>
		/// <para>This doc was truncated.</para>
		/// <para><see href="https://docs.microsoft.com/windows/win32/api//wtypes/ns-wtypes-propertykey#">Read more on docs.microsoft.com</see>.</para>
		/// </remarks>
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.164-beta+187018bf44")]
		internal partial struct PROPERTYKEY
		{
			/// <summary>
			/// <para>Type: <b>GUID</b> A unique GUID for the property.</para>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//wtypes/ns-wtypes-propertykey#members">Read more on docs.microsoft.com</see>.</para>
			/// </summary>
			internal global::System.Guid fmtid;
			/// <summary>
			/// <para>Type: <b>DWORD</b> A property identifier (PID). This parameter is not used as in <a href="https://docs.microsoft.com/windows/desktop/shell/objects">SHCOLUMNID</a>. It is recommended that you set this value to PID_FIRST_USABLE. Any value greater than or equal to 2 is acceptable. <div class="alert"><b>Note</b>  Values of 0 and 1 are reserved and should not be used.</div> <div> </div></para>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//wtypes/ns-wtypes-propertykey#members">Read more on docs.microsoft.com</see>.</para>
			/// </summary>
			internal uint pid;
		}
	}
}
