// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

#pragma warning disable CS1591,CS1573,CS0465,CS0649,CS8019,CS1570,CS1584,CS1658,CS0436,CS8981
using global::System;
using global::System.Diagnostics;
using global::System.Diagnostics.CodeAnalysis;
using global::System.Runtime.CompilerServices;
using global::System.Runtime.InteropServices;
using global::System.Runtime.Versioning;
using winmdroot = global::Windows.Win32;
namespace Windows.Win32
{
	namespace System.Com
	{
		/// <summary>Specifies the variable type.</summary>
		/// <remarks>
		/// <para><see href="https://docs.microsoft.com/windows/win32/api//oaidl/ne-oaidl-varkind">Learn more about this API from docs.microsoft.com</see>.</para>
		/// </remarks>
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.164-beta+187018bf44")]
		internal enum VARKIND
		{
			/// <summary>The variable is a field or member of the type. It exists at a fixed offset within each instance of the type.</summary>
			VAR_PERINSTANCE = 0,
			/// <summary>There is only one instance of the variable.</summary>
			VAR_STATIC = 1,
			/// <summary>The VARDESC describes a symbolic constant. There is no memory associated with it.</summary>
			VAR_CONST = 2,
			/// <summary>The variable can only be accessed through <a href="https://docs.microsoft.com/previous-versions/windows/desktop/api/oaidl/nf-oaidl-idispatch-invoke">IDispatch::Invoke</a>.</summary>
			VAR_DISPATCH = 3,
		}
	}
}
