// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

#pragma warning disable CS1591,CS1573,CS0465,CS0649,CS8019,CS1570,CS1584,CS1658,CS0436,CS8981
using global::System;
using global::System.Diagnostics;
using global::System.Diagnostics.CodeAnalysis;
using global::System.Runtime.CompilerServices;
using global::System.Runtime.InteropServices;
using global::System.Runtime.Versioning;
using winmdroot = global::Windows.Win32;
namespace Windows.Win32
{
	namespace System.Com.StructuredStorage
	{
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.164-beta+187018bf44")]
		internal partial struct PROPVARIANT_unmanaged
		{
			internal winmdroot.System.Com.StructuredStorage.PROPVARIANT_unmanaged._Anonymous_e__Union_unmanaged Anonymous;

			[StructLayout(LayoutKind.Explicit)]
			[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.164-beta+187018bf44")]
			internal partial struct _Anonymous_e__Union_unmanaged
			{
				[FieldOffset(0)]
				internal winmdroot.System.Com.StructuredStorage.PROPVARIANT_unmanaged._Anonymous_e__Union_unmanaged._Anonymous_e__Struct_unmanaged Anonymous;
				[FieldOffset(0)]
				internal winmdroot.Foundation.DECIMAL decVal;

				[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.164-beta+187018bf44")]
				internal partial struct _Anonymous_e__Struct_unmanaged
				{
					internal winmdroot.System.Com.VARENUM vt;
					internal ushort wReserved1;
					internal ushort wReserved2;
					internal ushort wReserved3;
					internal winmdroot.System.Com.StructuredStorage.PROPVARIANT_unmanaged._Anonymous_e__Union_unmanaged._Anonymous_e__Struct_unmanaged._Anonymous_e__Union_unmanaged Anonymous;

					[StructLayout(LayoutKind.Explicit)]
					[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.164-beta+187018bf44")]
					internal partial struct _Anonymous_e__Union_unmanaged
					{
						[FieldOffset(0)]
						internal winmdroot.Foundation.CHAR cVal;
						[FieldOffset(0)]
						internal byte bVal;
						[FieldOffset(0)]
						internal short iVal;
						[FieldOffset(0)]
						internal ushort uiVal;
						[FieldOffset(0)]
						internal int lVal;
						[FieldOffset(0)]
						internal uint ulVal;
						[FieldOffset(0)]
						internal int intVal;
						[FieldOffset(0)]
						internal uint uintVal;
						[FieldOffset(0)]
						internal long hVal;
						[FieldOffset(0)]
						internal ulong uhVal;
						[FieldOffset(0)]
						internal float fltVal;
						[FieldOffset(0)]
						internal double dblVal;
						[FieldOffset(0)]
						internal winmdroot.Foundation.VARIANT_BOOL boolVal;
						[FieldOffset(0)]
						internal winmdroot.Foundation.VARIANT_BOOL __OBSOLETE__VARIANT_BOOL;
						[FieldOffset(0)]
						internal int scode;
						[FieldOffset(0)]
						internal winmdroot.System.Com.CY cyVal;
						[FieldOffset(0)]
						internal double date;
						[FieldOffset(0)]
						internal global::System.Runtime.InteropServices.ComTypes.FILETIME filetime;
						[FieldOffset(0)]
						internal unsafe global::System.Guid* puuid;
						[FieldOffset(0)]
						internal unsafe winmdroot.System.Com.StructuredStorage.CLIPDATA* pclipdata;
						[FieldOffset(0)]
						internal winmdroot.Foundation.BSTR bstrVal;
						[FieldOffset(0)]
						internal winmdroot.System.Com.StructuredStorage.BSTRBLOB bstrblobVal;
						[FieldOffset(0)]
						internal winmdroot.System.Com.BLOB blob;
						[FieldOffset(0)]
						internal winmdroot.Foundation.PSTR pszVal;
						[FieldOffset(0)]
						internal winmdroot.Foundation.PWSTR pwszVal;
						[FieldOffset(0)]
						internal unsafe winmdroot.System.Com.IUnknown_unmanaged* punkVal;
						[FieldOffset(0)]
						internal unsafe winmdroot.System.Com.IDispatch_unmanaged* pdispVal;
						[FieldOffset(0)]
						internal unsafe winmdroot.System.Com.IStream_unmanaged* pStream;
						[FieldOffset(0)]
						internal unsafe winmdroot.System.Com.StructuredStorage.IStorage_unmanaged* pStorage;
						[FieldOffset(0)]
						internal unsafe winmdroot.System.Com.StructuredStorage.VERSIONEDSTREAM_unmanaged* pVersionedStream;
						[FieldOffset(0)]
						internal unsafe winmdroot.System.Com.SAFEARRAY* parray;
						[FieldOffset(0)]
						internal winmdroot.System.Com.StructuredStorage.CAC cac;
						[FieldOffset(0)]
						internal winmdroot.System.Com.StructuredStorage.CAUB caub;
						[FieldOffset(0)]
						internal winmdroot.System.Com.StructuredStorage.CAI cai;
						[FieldOffset(0)]
						internal winmdroot.System.Com.StructuredStorage.CAUI caui;
						[FieldOffset(0)]
						internal winmdroot.System.Com.StructuredStorage.CAL cal;
						[FieldOffset(0)]
						internal winmdroot.System.Com.StructuredStorage.CAUL caul;
						[FieldOffset(0)]
						internal winmdroot.System.Com.StructuredStorage.CAH cah;
						[FieldOffset(0)]
						internal winmdroot.System.Com.StructuredStorage.CAUH cauh;
						[FieldOffset(0)]
						internal winmdroot.System.Com.StructuredStorage.CAFLT caflt;
						[FieldOffset(0)]
						internal winmdroot.System.Com.StructuredStorage.CADBL cadbl;
						[FieldOffset(0)]
						internal winmdroot.System.Com.StructuredStorage.CABOOL cabool;
						[FieldOffset(0)]
						internal winmdroot.System.Com.StructuredStorage.CASCODE cascode;
						[FieldOffset(0)]
						internal winmdroot.System.Com.StructuredStorage.CACY cacy;
						[FieldOffset(0)]
						internal winmdroot.System.Com.StructuredStorage.CADATE cadate;
						[FieldOffset(0)]
						internal winmdroot.System.Com.StructuredStorage.CAFILETIME cafiletime;
						[FieldOffset(0)]
						internal winmdroot.System.Com.StructuredStorage.CACLSID cauuid;
						[FieldOffset(0)]
						internal winmdroot.System.Com.StructuredStorage.CACLIPDATA caclipdata;
						[FieldOffset(0)]
						internal winmdroot.System.Com.StructuredStorage.CABSTR cabstr;
						[FieldOffset(0)]
						internal winmdroot.System.Com.StructuredStorage.CABSTRBLOB cabstrblob;
						[FieldOffset(0)]
						internal winmdroot.System.Com.StructuredStorage.CALPSTR calpstr;
						[FieldOffset(0)]
						internal winmdroot.System.Com.StructuredStorage.CALPWSTR calpwstr;
						[FieldOffset(0)]
						internal winmdroot.System.Com.StructuredStorage.CAPROPVARIANT_unmanaged capropvar;
						[FieldOffset(0)]
						internal winmdroot.Foundation.PSTR pcVal;
						[FieldOffset(0)]
						internal unsafe byte* pbVal;
						[FieldOffset(0)]
						internal unsafe short* piVal;
						[FieldOffset(0)]
						internal unsafe ushort* puiVal;
						[FieldOffset(0)]
						internal unsafe int* plVal;
						[FieldOffset(0)]
						internal unsafe uint* pulVal;
						[FieldOffset(0)]
						internal unsafe int* pintVal;
						[FieldOffset(0)]
						internal unsafe uint* puintVal;
						[FieldOffset(0)]
						internal unsafe float* pfltVal;
						[FieldOffset(0)]
						internal unsafe double* pdblVal;
						[FieldOffset(0)]
						internal unsafe winmdroot.Foundation.VARIANT_BOOL* pboolVal;
						[FieldOffset(0)]
						internal unsafe winmdroot.Foundation.DECIMAL* pdecVal;
						[FieldOffset(0)]
						internal unsafe int* pscode;
						[FieldOffset(0)]
						internal unsafe winmdroot.System.Com.CY* pcyVal;
						[FieldOffset(0)]
						internal unsafe double* pdate;
						[FieldOffset(0)]
						internal unsafe winmdroot.Foundation.BSTR* pbstrVal;
						[FieldOffset(0)]
						internal unsafe winmdroot.System.Com.IUnknown_unmanaged** ppunkVal;
						[FieldOffset(0)]
						internal unsafe winmdroot.System.Com.IDispatch_unmanaged** ppdispVal;
						[FieldOffset(0)]
						internal unsafe winmdroot.System.Com.SAFEARRAY** pparray;
						[FieldOffset(0)]
						internal unsafe winmdroot.System.Com.StructuredStorage.PROPVARIANT_unmanaged* pvarVal;
					}
				}
			}
		}
	}
}
