// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

#pragma warning disable CS1591,CS1573,CS0465,CS0649,CS8019,CS1570,CS1584,CS1658,CS0436,CS8981
using global::System;
using global::System.Diagnostics;
using global::System.Diagnostics.CodeAnalysis;
using global::System.Runtime.CompilerServices;
using global::System.Runtime.InteropServices;
using global::System.Runtime.Versioning;
using winmdroot = global::Windows.Win32;
namespace Windows.Win32
{
	namespace UI.Shell.PropertiesSystem
	{
		[Guid("886D8EEB-8CF2-4446-8D02-CDBA1DBDCF99"),InterfaceType(ComInterfaceType.InterfaceIsIUnknown),ComImport()]
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.164-beta+187018bf44")]
		internal interface IPropertyStore
		{
			/// <summary>This method returns a count of the number of properties that are attached to the file.</summary>
			/// <param name="cProps">A pointer to a value that indicates the property count.</param>
			/// <returns>The <code>IpropertyStore::GetCount</code> method returns a value of S_OK when the call is successful, even if the file has no properties attached. Any other code returned is an error code.</returns>
			/// <remarks>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//propsys/nf-propsys-ipropertystore-getcount">Learn more about this API from docs.microsoft.com</see>.</para>
			/// </remarks>
			unsafe void GetCount(uint* cProps);

			/// <summary>Gets a property key from the property array of an item.</summary>
			/// <param name="iProp">The index of the property key in the array of PROPERTYKEY structures. This is a zero-based index.</param>
			/// <param name="pkey">TBD</param>
			/// <returns>The <code>IPropertyStore::GetAt</code> method returns a value of S_OK if successful. Otherwise, any other code it returns must be considered to be an error code.</returns>
			/// <remarks>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//propsys/nf-propsys-ipropertystore-getat">Learn more about this API from docs.microsoft.com</see>.</para>
			/// </remarks>
			unsafe void GetAt(uint iProp, winmdroot.UI.Shell.PropertiesSystem.PROPERTYKEY* pkey);

			/// <summary>This method retrieves the data for a specific property.</summary>
			/// <param name="key">TBD</param>
			/// <param name="pv">After the <c>IPropertyStore::GetValue</c> method returns successfully, this parameter points to a <a href="https://docs.microsoft.com/previous-versions/aa912007(v=msdn.10)">PROPVARIANT </a> structure that contains data about the property.</param>
			/// <returns>
			/// <para>Returns S_OK or INPLACE_S_TRUNCATED if successful, or an error value otherwise. INPLACE_S_TRUNCATED is returned to indicate that the returned PROPVARIANT was converted into a more canonical form. For example, this would be done to trim leading or trailing spaces from a string value. You must use the SUCCEEDED macro to check the return value, which treats INPLACE_S_TRUNCATED as a success code. The SUCCEEDED macro is defined in the Winerror.h file.</para>
			/// </returns>
			/// <remarks>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//propsys/nf-propsys-ipropertystore-getvalue">Learn more about this API from docs.microsoft.com</see>.</para>
			/// </remarks>
			unsafe void GetValue(winmdroot.UI.Shell.PropertiesSystem.PROPERTYKEY* key, out winmdroot.System.Com.StructuredStorage.PROPVARIANT pv);

			/// <summary>This method sets a property value or replaces or removes an existing value.</summary>
			/// <param name="key">TBD</param>
			/// <param name="propvar">TBD</param>
			/// <returns>
			/// <para>The <code>IPropertyStore::SetValue</code> method can return any one of the following: </para>
			/// <para>This doc was truncated.</para>
			/// </returns>
			/// <remarks>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//propsys/nf-propsys-ipropertystore-setvalue">Learn more about this API from docs.microsoft.com</see>.</para>
			/// </remarks>
			unsafe void SetValue(winmdroot.UI.Shell.PropertiesSystem.PROPERTYKEY* key, in winmdroot.System.Com.StructuredStorage.PROPVARIANT propvar);

			/// <summary>After a change has been made, this method saves the changes.</summary>
			/// <returns>
			/// <para>The <code>IPropertyStore::Commit</code> method returns any one of the following: </para>
			/// <para>This doc was truncated.</para>
			/// </returns>
			/// <remarks>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//propsys/nf-propsys-ipropertystore-commit">Learn more about this API from docs.microsoft.com</see>.</para>
			/// </remarks>
			void Commit();
		}
	}
}
