// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

#pragma warning disable CS1591,CS1573,CS0465,CS0649,CS8019,CS1570,CS1584,CS1658,CS0436,CS8981
using global::System;
using global::System.Diagnostics;
using global::System.Diagnostics.CodeAnalysis;
using global::System.Runtime.CompilerServices;
using global::System.Runtime.InteropServices;
using global::System.Runtime.Versioning;
using winmdroot = global::Windows.Win32;
namespace Windows.Win32
{
	[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.164-beta+187018bf44")]
	internal static partial class System_Ole_IRecordInfo_Extensions
	{
		/// <inheritdoc cref="winmdroot.System.Ole.IRecordInfo.GetGuid(global::System.Guid*)"/>
		internal static unsafe void GetGuid(this winmdroot.System.Ole.IRecordInfo @this, out global::System.Guid pguid)
		{
			fixed (global::System.Guid* pguidLocal = &pguid)
			{
				@this.GetGuid(pguidLocal);
			}
		}

		/// <inheritdoc cref="winmdroot.System.Ole.IRecordInfo.GetName(winmdroot.Foundation.BSTR*)"/>
		internal static unsafe void GetName(this winmdroot.System.Ole.IRecordInfo @this, out SysFreeStringSafeHandle pbstrName)
		{
			winmdroot.Foundation.BSTR pbstrNameLocal;
			@this.GetName(&pbstrNameLocal);
			pbstrName = new SysFreeStringSafeHandle(pbstrNameLocal, ownsHandle: true);
		}

		/// <inheritdoc cref="winmdroot.System.Ole.IRecordInfo.GetSize(uint*)"/>
		internal static unsafe void GetSize(this winmdroot.System.Ole.IRecordInfo @this, out uint pcbSize)
		{
			fixed (uint* pcbSizeLocal = &pcbSize)
			{
				@this.GetSize(pcbSizeLocal);
			}
		}

		/// <inheritdoc cref="winmdroot.System.Ole.IRecordInfo.GetField(void*, winmdroot.Foundation.PCWSTR, out object)"/>
		internal static unsafe void GetField(this winmdroot.System.Ole.IRecordInfo @this, void* pvData, string szFieldName, out object pvarField)
		{
			fixed (char* szFieldNameLocal = szFieldName)
			{
				@this.GetField(pvData, szFieldNameLocal, out pvarField);
			}
		}

		/// <inheritdoc cref="winmdroot.System.Ole.IRecordInfo.GetFieldNoCopy(void*, winmdroot.Foundation.PCWSTR, out object, void**)"/>
		internal static unsafe void GetFieldNoCopy(this winmdroot.System.Ole.IRecordInfo @this, void* pvData, string szFieldName, out object pvarField, out void* ppvDataCArray)
		{
			fixed (void** ppvDataCArrayLocal = &ppvDataCArray)
			{
				fixed (char* szFieldNameLocal = szFieldName)
				{
					@this.GetFieldNoCopy(pvData, szFieldNameLocal, out pvarField, ppvDataCArrayLocal);
				}
			}
		}

		/// <inheritdoc cref="winmdroot.System.Ole.IRecordInfo.PutField(winmdroot.System.Com.INVOKEKIND, void*, winmdroot.Foundation.PCWSTR, in object)"/>
		internal static unsafe void PutField(this winmdroot.System.Ole.IRecordInfo @this, winmdroot.System.Com.INVOKEKIND wFlags, void* pvData, string szFieldName, in object pvarField)
		{
			fixed (char* szFieldNameLocal = szFieldName)
			{
				@this.PutField(wFlags, pvData, szFieldNameLocal, in pvarField);
			}
		}

		/// <inheritdoc cref="winmdroot.System.Ole.IRecordInfo.PutFieldNoCopy(winmdroot.System.Com.INVOKEKIND, void*, winmdroot.Foundation.PCWSTR, in object)"/>
		internal static unsafe void PutFieldNoCopy(this winmdroot.System.Ole.IRecordInfo @this, winmdroot.System.Com.INVOKEKIND wFlags, void* pvData, string szFieldName, in object pvarField)
		{
			fixed (char* szFieldNameLocal = szFieldName)
			{
				@this.PutFieldNoCopy(wFlags, pvData, szFieldNameLocal, in pvarField);
			}
		}

		/// <inheritdoc cref="winmdroot.System.Ole.IRecordInfo.GetFieldNames(uint*, winmdroot.Foundation.BSTR*)"/>
		internal static unsafe void GetFieldNames(this winmdroot.System.Ole.IRecordInfo @this, ref uint pcNames, out SysFreeStringSafeHandle rgBstrNames)
		{
			fixed (uint* pcNamesLocal = &pcNames)
			{
				winmdroot.Foundation.BSTR rgBstrNamesLocal;
				@this.GetFieldNames(pcNamesLocal, &rgBstrNamesLocal);
				rgBstrNames = new SysFreeStringSafeHandle(rgBstrNamesLocal, ownsHandle: true);
			}
		}

		/// <inheritdoc cref="winmdroot.System.Ole.IRecordInfo.RecordCreateCopy(void*, void**)"/>
		internal static unsafe void RecordCreateCopy(this winmdroot.System.Ole.IRecordInfo @this, void* pvSource, out void* ppvDest)
		{
			fixed (void** ppvDestLocal = &ppvDest)
			{
				@this.RecordCreateCopy(pvSource, ppvDestLocal);
			}
		}
	}
}
