// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

#pragma warning disable CS1591,CS1573,CS0465,CS0649,CS8019,CS1570,CS1584,CS1658,CS0436,CS8981
using global::System;
using global::System.Diagnostics;
using global::System.Diagnostics.CodeAnalysis;
using global::System.Runtime.CompilerServices;
using global::System.Runtime.InteropServices;
using global::System.Runtime.Versioning;
using winmdroot = global::Windows.Win32;
namespace Windows.Win32
{
	namespace UI.Shell
	{
		[Guid("EA1AFB91-9E28-4B86-90E9-9E9F8A5EEFAF"),InterfaceType(ComInterfaceType.InterfaceIsIUnknown),ComImport()]
		[SupportedOSPlatform("windows6.1")]
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.164-beta+187018bf44")]
		internal interface ITaskbarList3
			:winmdroot.UI.Shell.ITaskbarList,winmdroot.UI.Shell.ITaskbarList2		{
			new void HrInit();

			new void AddTab(winmdroot.Foundation.HWND hwnd);

			new void DeleteTab(winmdroot.Foundation.HWND hwnd);

			new void ActivateTab(winmdroot.Foundation.HWND hwnd);

			new void SetActiveAlt(winmdroot.Foundation.HWND hwnd);

			new void MarkFullscreenWindow(winmdroot.Foundation.HWND hwnd, winmdroot.Foundation.BOOL fFullscreen);

			/// <summary>Displays or updates a progress bar hosted in a taskbar button to show the specific percentage completed of the full operation.</summary>
			/// <param name="hwnd">
			/// <para>Type: <b>HWND</b> The handle of the window whose associated taskbar button is being used as a progress indicator.</para>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//shobjidl_core/nf-shobjidl_core-itaskbarlist3-setprogressvalue#parameters">Read more on docs.microsoft.com</see>.</para>
			/// </param>
			/// <param name="ullCompleted">
			/// <para>Type: <b>ULONGLONG</b> An application-defined value that indicates the proportion of the operation that has been completed at the time the method is called.</para>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//shobjidl_core/nf-shobjidl_core-itaskbarlist3-setprogressvalue#parameters">Read more on docs.microsoft.com</see>.</para>
			/// </param>
			/// <param name="ullTotal">
			/// <para>Type: <b>ULONGLONG</b> An application-defined value that specifies the value <i>ullCompleted</i> will have when the operation is complete.</para>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//shobjidl_core/nf-shobjidl_core-itaskbarlist3-setprogressvalue#parameters">Read more on docs.microsoft.com</see>.</para>
			/// </param>
			/// <returns>
			/// <para>Type: <b>HRESULT</b> If this method succeeds, it returns <b xmlns:loc="http://microsoft.com/wdcml/l10n">S_OK</b>. Otherwise, it returns an <b xmlns:loc="http://microsoft.com/wdcml/l10n">HRESULT</b> error code.</para>
			/// </returns>
			/// <remarks>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//shobjidl_core/nf-shobjidl_core-itaskbarlist3-setprogressvalue">Learn more about this API from docs.microsoft.com</see>.</para>
			/// </remarks>
			void SetProgressValue(winmdroot.Foundation.HWND hwnd, ulong ullCompleted, ulong ullTotal);

			/// <summary>Sets the type and state of the progress indicator displayed on a taskbar button.</summary>
			/// <param name="hwnd">
			/// <para>Type: <b>HWND</b> The handle of the window in which the progress of an operation is being shown. This window's associated taskbar button will display the progress bar.</para>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//shobjidl_core/nf-shobjidl_core-itaskbarlist3-setprogressstate#parameters">Read more on docs.microsoft.com</see>.</para>
			/// </param>
			/// <param name="tbpFlags">
			/// <para>Type: <b>TBPFLAG</b> Flags that control the current state of the progress button. Specify only one of the following flags; all states are mutually exclusive of all others.</para>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//shobjidl_core/nf-shobjidl_core-itaskbarlist3-setprogressstate#parameters">Read more on docs.microsoft.com</see>.</para>
			/// </param>
			/// <returns>
			/// <para>Type: <b>HRESULT</b> If this method succeeds, it returns <b xmlns:loc="http://microsoft.com/wdcml/l10n">S_OK</b>. Otherwise, it returns an <b xmlns:loc="http://microsoft.com/wdcml/l10n">HRESULT</b> error code.</para>
			/// </returns>
			/// <remarks>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//shobjidl_core/nf-shobjidl_core-itaskbarlist3-setprogressstate">Learn more about this API from docs.microsoft.com</see>.</para>
			/// </remarks>
			void SetProgressState(winmdroot.Foundation.HWND hwnd, winmdroot.UI.Shell.TBPFLAG tbpFlags);

			/// <summary>Informs the taskbar that a new tab or document thumbnail has been provided for display in an application's taskbar group flyout.</summary>
			/// <param name="hwndTab">
			/// <para>Type: <b>HWND</b> Handle of the tab or document window. This value is required and cannot be <b>NULL</b>.</para>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//shobjidl_core/nf-shobjidl_core-itaskbarlist3-registertab#parameters">Read more on docs.microsoft.com</see>.</para>
			/// </param>
			/// <param name="hwndMDI">
			/// <para>Type: <b>HWND</b> Handle of the application's main window. This value tells the taskbar which application's preview group to attach the new thumbnail to. This value is required and cannot be <b>NULL</b>.</para>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//shobjidl_core/nf-shobjidl_core-itaskbarlist3-registertab#parameters">Read more on docs.microsoft.com</see>.</para>
			/// </param>
			/// <returns>
			/// <para>Type: <b>HRESULT</b> Returns S_OK if successful, or an error value otherwise. If either parameter is <b>NULL</b>, this method returns an error.</para>
			/// </returns>
			/// <remarks>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//shobjidl_core/nf-shobjidl_core-itaskbarlist3-registertab">Learn more about this API from docs.microsoft.com</see>.</para>
			/// </remarks>
			void RegisterTab(winmdroot.Foundation.HWND hwndTab, winmdroot.Foundation.HWND hwndMDI);

			/// <summary>Removes a thumbnail from an application's preview group when that tab or document is closed in the application.</summary>
			/// <param name="hwndTab">
			/// <para>Type: <b>HWND</b> The handle of the tab window whose thumbnail is being removed. This is the same value with which the thumbnail was registered as part the group through <a href="https://docs.microsoft.com/windows/desktop/api/shobjidl_core/nf-shobjidl_core-itaskbarlist3-registertab">ITaskbarList3::RegisterTab</a>. This value is required and cannot be <b>NULL</b>.</para>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//shobjidl_core/nf-shobjidl_core-itaskbarlist3-unregistertab#parameters">Read more on docs.microsoft.com</see>.</para>
			/// </param>
			/// <returns>
			/// <para>Type: <b>HRESULT</b> Returns <b>S_OK</b> if successful, or an error value otherwise. If <i>hwndTab</i> is <b>NULL</b>, this method returns an error.</para>
			/// </returns>
			/// <remarks>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//shobjidl_core/nf-shobjidl_core-itaskbarlist3-unregistertab">Learn more about this API from docs.microsoft.com</see>.</para>
			/// </remarks>
			void UnregisterTab(winmdroot.Foundation.HWND hwndTab);

			/// <summary>Inserts a new thumbnail into a tabbed-document interface (TDI) or multiple-document interface (MDI) application's group flyout or moves an existing thumbnail to a new position in the application's group.</summary>
			/// <param name="hwndTab">
			/// <para>Type: <b>HWND</b> The handle of the tab window whose thumbnail is being placed. This value is required, must already be registered through <a href="https://docs.microsoft.com/windows/desktop/api/shobjidl_core/nf-shobjidl_core-itaskbarlist3-registertab">ITaskbarList3::RegisterTab</a>, and cannot be <b>NULL</b>.</para>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//shobjidl_core/nf-shobjidl_core-itaskbarlist3-settaborder#parameters">Read more on docs.microsoft.com</see>.</para>
			/// </param>
			/// <param name="hwndInsertBefore">
			/// <para>Type: <b>HWND</b> The handle of the tab window whose thumbnail that <i>hwndTab</i> is inserted to the left of. This handle must already be registered through <a href="https://docs.microsoft.com/windows/desktop/api/shobjidl_core/nf-shobjidl_core-itaskbarlist3-registertab">ITaskbarList3::RegisterTab</a>. If this value is <b>NULL</b>, the new thumbnail is added to the end of the list.</para>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//shobjidl_core/nf-shobjidl_core-itaskbarlist3-settaborder#parameters">Read more on docs.microsoft.com</see>.</para>
			/// </param>
			/// <returns>
			/// <para>Type: <b>HRESULT</b> If this method succeeds, it returns <b xmlns:loc="http://microsoft.com/wdcml/l10n">S_OK</b>. Otherwise, it returns an <b xmlns:loc="http://microsoft.com/wdcml/l10n">HRESULT</b> error code.</para>
			/// </returns>
			/// <remarks>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//shobjidl_core/nf-shobjidl_core-itaskbarlist3-settaborder">Learn more about this API from docs.microsoft.com</see>.</para>
			/// </remarks>
			void SetTabOrder(winmdroot.Foundation.HWND hwndTab, winmdroot.Foundation.HWND hwndInsertBefore);

			/// <summary>Informs the taskbar that a tab or document window has been made the active window.</summary>
			/// <param name="hwndTab">
			/// <para>Type: <b>HWND</b> Handle of the active tab window. This handle must already be registered through <a href="https://docs.microsoft.com/windows/desktop/api/shobjidl_core/nf-shobjidl_core-itaskbarlist3-registertab">ITaskbarList3::RegisterTab</a>. This value can be <b>NULL</b> if no tab is active.</para>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//shobjidl_core/nf-shobjidl_core-itaskbarlist3-settabactive#parameters">Read more on docs.microsoft.com</see>.</para>
			/// </param>
			/// <param name="hwndMDI">
			/// <para>Type: <b>HWND</b> Handle of the application's main window. This value tells the taskbar which group the thumbnail is a member of. This value is required and cannot be <b>NULL</b>.</para>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//shobjidl_core/nf-shobjidl_core-itaskbarlist3-settabactive#parameters">Read more on docs.microsoft.com</see>.</para>
			/// </param>
			/// <param name="dwReserved">
			/// <para>Type: <b>DWORD</b> Reserved; set to 0.</para>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//shobjidl_core/nf-shobjidl_core-itaskbarlist3-settabactive#parameters">Read more on docs.microsoft.com</see>.</para>
			/// </param>
			/// <returns>
			/// <para>Type: <b>HRESULT</b> If this method succeeds, it returns <b xmlns:loc="http://microsoft.com/wdcml/l10n">S_OK</b>. Otherwise, it returns an <b xmlns:loc="http://microsoft.com/wdcml/l10n">HRESULT</b> error code.</para>
			/// </returns>
			/// <remarks>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//shobjidl_core/nf-shobjidl_core-itaskbarlist3-settabactive">Learn more about this API from docs.microsoft.com</see>.</para>
			/// </remarks>
			void SetTabActive(winmdroot.Foundation.HWND hwndTab, winmdroot.Foundation.HWND hwndMDI, uint dwReserved);

			/// <summary>Adds a thumbnail toolbar with a specified set of buttons to the thumbnail image of a window in a taskbar button flyout.</summary>
			/// <param name="hwnd">
			/// <para>Type: <b>HWND</b> The handle of the window whose thumbnail representation will receive the toolbar. This handle must belong to the calling process.</para>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//shobjidl_core/nf-shobjidl_core-itaskbarlist3-thumbbaraddbuttons#parameters">Read more on docs.microsoft.com</see>.</para>
			/// </param>
			/// <param name="cButtons">
			/// <para>Type: <b>UINT</b> The number of buttons defined in the array pointed to by <i>pButton</i>. The maximum number of buttons allowed is 7.</para>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//shobjidl_core/nf-shobjidl_core-itaskbarlist3-thumbbaraddbuttons#parameters">Read more on docs.microsoft.com</see>.</para>
			/// </param>
			/// <param name="pButton">
			/// <para>Type: <b>LPTHUMBBUTTON</b> A pointer to an array of <a href="https://docs.microsoft.com/windows/desktop/api/shobjidl_core/ns-shobjidl_core-thumbbutton">THUMBBUTTON</a> structures. Each <b>THUMBBUTTON</b> defines an individual button to be added to the toolbar. Buttons cannot be added or deleted later, so this must be the full defined set. Buttons also cannot be reordered, so their order in the array, which is the order in which they are displayed left to right, will be their permanent order.</para>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//shobjidl_core/nf-shobjidl_core-itaskbarlist3-thumbbaraddbuttons#parameters">Read more on docs.microsoft.com</see>.</para>
			/// </param>
			/// <returns>
			/// <para>Type: <b>HRESULT</b> Returns <b>S_OK</b> if successful, or an error value otherwise, including the following: </para>
			/// <para>This doc was truncated.</para>
			/// </returns>
			/// <remarks>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//shobjidl_core/nf-shobjidl_core-itaskbarlist3-thumbbaraddbuttons">Learn more about this API from docs.microsoft.com</see>.</para>
			/// </remarks>
			unsafe void ThumbBarAddButtons(winmdroot.Foundation.HWND hwnd, uint cButtons, winmdroot.UI.Shell.THUMBBUTTON* pButton);

			/// <summary>Shows, enables, disables, or hides buttons in a thumbnail toolbar as required by the window's current state. A thumbnail toolbar is a toolbar embedded in a thumbnail image of a window in a taskbar button flyout.</summary>
			/// <param name="hwnd">
			/// <para>Type: <b>HWND</b> The handle of the window whose thumbnail representation contains the toolbar.</para>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//shobjidl_core/nf-shobjidl_core-itaskbarlist3-thumbbarupdatebuttons#parameters">Read more on docs.microsoft.com</see>.</para>
			/// </param>
			/// <param name="cButtons">
			/// <para>Type: <b>UINT</b> The number of buttons defined in the array pointed to by <i>pButton</i>. The maximum number of buttons allowed is 7. This array contains only structures that represent existing buttons that are being updated.</para>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//shobjidl_core/nf-shobjidl_core-itaskbarlist3-thumbbarupdatebuttons#parameters">Read more on docs.microsoft.com</see>.</para>
			/// </param>
			/// <param name="pButton">
			/// <para>Type: <b>LPTHUMBBUTTON</b> A pointer to an array of <a href="https://docs.microsoft.com/windows/desktop/api/shobjidl_core/ns-shobjidl_core-thumbbutton">THUMBBUTTON</a> structures. Each <b>THUMBBUTTON</b> defines an individual button. If the button already exists (the <b>iId</b> value is already defined), then that existing button is updated with the information provided in the structure.</para>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//shobjidl_core/nf-shobjidl_core-itaskbarlist3-thumbbarupdatebuttons#parameters">Read more on docs.microsoft.com</see>.</para>
			/// </param>
			/// <returns>
			/// <para>Type: <b>HRESULT</b> If this method succeeds, it returns <b xmlns:loc="http://microsoft.com/wdcml/l10n">S_OK</b>. Otherwise, it returns an <b xmlns:loc="http://microsoft.com/wdcml/l10n">HRESULT</b> error code.</para>
			/// </returns>
			/// <remarks>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//shobjidl_core/nf-shobjidl_core-itaskbarlist3-thumbbarupdatebuttons">Learn more about this API from docs.microsoft.com</see>.</para>
			/// </remarks>
			unsafe void ThumbBarUpdateButtons(winmdroot.Foundation.HWND hwnd, uint cButtons, winmdroot.UI.Shell.THUMBBUTTON* pButton);

			/// <summary>Specifies an image list that contains button images for a toolbar embedded in a thumbnail image of a window in a taskbar button flyout.</summary>
			/// <param name="hwnd">
			/// <para>Type: <b>HWND</b> The handle of the window whose thumbnail representation contains the toolbar to be updated. This handle must belong to the calling process.</para>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//shobjidl_core/nf-shobjidl_core-itaskbarlist3-thumbbarsetimagelist#parameters">Read more on docs.microsoft.com</see>.</para>
			/// </param>
			/// <param name="himl">
			/// <para>Type: <b>HIMAGELIST</b> The handle of the image list that contains all button images to be used in the toolbar.</para>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//shobjidl_core/nf-shobjidl_core-itaskbarlist3-thumbbarsetimagelist#parameters">Read more on docs.microsoft.com</see>.</para>
			/// </param>
			/// <returns>
			/// <para>Type: <b>HRESULT</b> If this method succeeds, it returns <b xmlns:loc="http://microsoft.com/wdcml/l10n">S_OK</b>. Otherwise, it returns an <b xmlns:loc="http://microsoft.com/wdcml/l10n">HRESULT</b> error code.</para>
			/// </returns>
			/// <remarks>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//shobjidl_core/nf-shobjidl_core-itaskbarlist3-thumbbarsetimagelist">Learn more about this API from docs.microsoft.com</see>.</para>
			/// </remarks>
			void ThumbBarSetImageList(winmdroot.Foundation.HWND hwnd, winmdroot.UI.Controls.HIMAGELIST himl);

			/// <summary>Applies an overlay to a taskbar button to indicate application status or a notification to the user.</summary>
			/// <param name="hwnd">
			/// <para>Type: <b>HWND</b> The handle of the window whose associated taskbar button receives the overlay. This handle must belong to a calling process associated with the button's application and must be a valid <b>HWND</b> or the call is ignored.</para>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//shobjidl_core/nf-shobjidl_core-itaskbarlist3-setoverlayicon#parameters">Read more on docs.microsoft.com</see>.</para>
			/// </param>
			/// <param name="hIcon">
			/// <para>Type: <b>HICON</b> The handle of an icon to use as the overlay. This should be a small icon, measuring 16x16 pixels at 96 dpi. If an overlay icon is already applied to the taskbar button, that existing overlay is replaced.</para>
			/// <para>This value can be <b>NULL</b>. How a <b>NULL</b> value is handled depends on whether the taskbar button represents a single window or a group of windows. </para>
			/// <para>This doc was truncated.</para>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//shobjidl_core/nf-shobjidl_core-itaskbarlist3-setoverlayicon#parameters">Read more on docs.microsoft.com</see>.</para>
			/// </param>
			/// <param name="pszDescription">
			/// <para>Type: <b>LPCWSTR</b> A pointer to a string that provides an alt text version of the information conveyed by the overlay, for accessibility purposes.</para>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//shobjidl_core/nf-shobjidl_core-itaskbarlist3-setoverlayicon#parameters">Read more on docs.microsoft.com</see>.</para>
			/// </param>
			/// <returns>
			/// <para>Type: <b>HRESULT</b> If this method succeeds, it returns <b xmlns:loc="http://microsoft.com/wdcml/l10n">S_OK</b>. Otherwise, it returns an <b xmlns:loc="http://microsoft.com/wdcml/l10n">HRESULT</b> error code.</para>
			/// </returns>
			/// <remarks>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//shobjidl_core/nf-shobjidl_core-itaskbarlist3-setoverlayicon">Learn more about this API from docs.microsoft.com</see>.</para>
			/// </remarks>
			void SetOverlayIcon(winmdroot.Foundation.HWND hwnd, winmdroot.UI.WindowsAndMessaging.HICON hIcon, winmdroot.Foundation.PCWSTR pszDescription);

			/// <summary>Specifies or updates the text of the tooltip that is displayed when the mouse pointer rests on an individual preview thumbnail in a taskbar button flyout.</summary>
			/// <param name="hwnd">
			/// <para>Type: <b>HWND</b> The handle to the window whose thumbnail displays the tooltip. This handle must belong to the calling process.</para>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//shobjidl_core/nf-shobjidl_core-itaskbarlist3-setthumbnailtooltip#parameters">Read more on docs.microsoft.com</see>.</para>
			/// </param>
			/// <param name="pszTip">
			/// <para>Type: <b>LPCWSTR</b> The pointer to the text to be displayed in the tooltip. This value can be <b>NULL</b>, in which case the title of the window specified by <i>hwnd</i> is used as the tooltip.</para>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//shobjidl_core/nf-shobjidl_core-itaskbarlist3-setthumbnailtooltip#parameters">Read more on docs.microsoft.com</see>.</para>
			/// </param>
			/// <returns>
			/// <para>Type: <b>HRESULT</b> If this method succeeds, it returns <b xmlns:loc="http://microsoft.com/wdcml/l10n">S_OK</b>. Otherwise, it returns an <b xmlns:loc="http://microsoft.com/wdcml/l10n">HRESULT</b> error code.</para>
			/// </returns>
			/// <remarks>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//shobjidl_core/nf-shobjidl_core-itaskbarlist3-setthumbnailtooltip">Learn more about this API from docs.microsoft.com</see>.</para>
			/// </remarks>
			void SetThumbnailTooltip(winmdroot.Foundation.HWND hwnd, winmdroot.Foundation.PCWSTR pszTip);

			/// <summary>Selects a portion of a window's client area to display as that window's thumbnail in the taskbar.</summary>
			/// <param name="hwnd">
			/// <para>Type: <b>HWND</b> The handle to a window represented in the taskbar.</para>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//shobjidl_core/nf-shobjidl_core-itaskbarlist3-setthumbnailclip#parameters">Read more on docs.microsoft.com</see>.</para>
			/// </param>
			/// <param name="prcClip">
			/// <para>Type: <b><a href="https://docs.microsoft.com/windows/desktop/api/windef/ns-windef-rect">RECT</a>*</b> A pointer to a <a href="https://docs.microsoft.com/windows/desktop/api/windef/ns-windef-rect">RECT</a> structure that specifies a selection within the window's client area, relative to the upper-left corner of that client area. To clear a clip that is already in place and return to the default display of the thumbnail, set this parameter to <b>NULL</b>.</para>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//shobjidl_core/nf-shobjidl_core-itaskbarlist3-setthumbnailclip#parameters">Read more on docs.microsoft.com</see>.</para>
			/// </param>
			/// <returns>
			/// <para>Type: <b>HRESULT</b> If this method succeeds, it returns <b xmlns:loc="http://microsoft.com/wdcml/l10n">S_OK</b>. Otherwise, it returns an <b xmlns:loc="http://microsoft.com/wdcml/l10n">HRESULT</b> error code.</para>
			/// </returns>
			/// <remarks>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//shobjidl_core/nf-shobjidl_core-itaskbarlist3-setthumbnailclip">Learn more about this API from docs.microsoft.com</see>.</para>
			/// </remarks>
			unsafe void SetThumbnailClip(winmdroot.Foundation.HWND hwnd, winmdroot.Foundation.RECT* prcClip);
		}
	}
}
