// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

#pragma warning disable CS1591,CS1573,CS0465,CS0649,CS8019,CS1570,CS1584,CS1658,CS0436,CS8981
using global::System;
using global::System.Diagnostics;
using global::System.Diagnostics.CodeAnalysis;
using global::System.Runtime.CompilerServices;
using global::System.Runtime.InteropServices;
using global::System.Runtime.Versioning;
using winmdroot = global::Windows.Win32;
namespace Windows.Win32
{
	namespace System.Com
	{
		[Guid("00020403-0000-0000-C000-000000000046")]
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.164-beta+187018bf44")]
		internal unsafe partial struct ITypeComp_unmanaged
			:IComIID		{
			/// <inheritdoc cref="QueryInterface(global::System.Guid*, out object)"/>
			internal unsafe winmdroot.Foundation.HRESULT QueryInterface(in global::System.Guid riid, out object ppvObject)
			{
				fixed (global::System.Guid* riidLocal = &riid)
				{
					winmdroot.Foundation.HRESULT __result = this.QueryInterface(riidLocal, out ppvObject);
					return __result;
				}
			}

			public unsafe winmdroot.Foundation.HRESULT QueryInterface(global::System.Guid* riid, [MarshalAs(UnmanagedType.IUnknown)] out object ppvObject)
			{
				fixed (ITypeComp_unmanaged* pThis = &this)
					return ((delegate *unmanaged [Stdcall]<ITypeComp_unmanaged*,global::System.Guid* ,out object ,winmdroot.Foundation.HRESULT>)lpVtbl[0])(pThis, riid, out ppvObject);
			}

			public uint AddRef()
			{
				fixed (ITypeComp_unmanaged* pThis = &this)
					return ((delegate *unmanaged [Stdcall]<ITypeComp_unmanaged*,uint>)lpVtbl[1])(pThis);
			}

			public uint Release()
			{
				fixed (ITypeComp_unmanaged* pThis = &this)
					return ((delegate *unmanaged [Stdcall]<ITypeComp_unmanaged*,uint>)lpVtbl[2])(pThis);
			}

			/// <inheritdoc cref="Bind(winmdroot.Foundation.PWSTR, uint, ushort, out winmdroot.System.Com.ITypeInfo, winmdroot.System.Com.DESCKIND*, out winmdroot.System.Com.BINDPTR)"/>
			internal unsafe void Bind(winmdroot.Foundation.PWSTR szName, uint lHashVal, ushort wFlags, out winmdroot.System.Com.ITypeInfo ppTInfo, out winmdroot.System.Com.DESCKIND pDescKind, out winmdroot.System.Com.BINDPTR pBindPtr)
			{
				fixed (winmdroot.System.Com.DESCKIND* pDescKindLocal = &pDescKind)
				{
					this.Bind(szName, lHashVal, wFlags, out ppTInfo, pDescKindLocal, out pBindPtr);
				}
			}

			public unsafe void Bind(winmdroot.Foundation.PWSTR szName, uint lHashVal, ushort wFlags, out winmdroot.System.Com.ITypeInfo ppTInfo, winmdroot.System.Com.DESCKIND* pDescKind, out winmdroot.System.Com.BINDPTR pBindPtr)
			{
				fixed (ITypeComp_unmanaged* pThis = &this)
					((delegate *unmanaged [Stdcall]<ITypeComp_unmanaged*,winmdroot.Foundation.PWSTR ,uint ,ushort ,out winmdroot.System.Com.ITypeInfo ,winmdroot.System.Com.DESCKIND* ,out winmdroot.System.Com.BINDPTR ,winmdroot.Foundation.HRESULT>)lpVtbl[3])(pThis, szName, lHashVal, wFlags, out ppTInfo, pDescKind, out pBindPtr).ThrowOnFailure();
			}

			public void BindType(winmdroot.Foundation.PWSTR szName, uint lHashVal, out winmdroot.System.Com.ITypeInfo ppTInfo, out winmdroot.System.Com.ITypeComp ppTComp)
			{
				fixed (ITypeComp_unmanaged* pThis = &this)
					((delegate *unmanaged [Stdcall]<ITypeComp_unmanaged*,winmdroot.Foundation.PWSTR ,uint ,out winmdroot.System.Com.ITypeInfo ,out winmdroot.System.Com.ITypeComp ,winmdroot.Foundation.HRESULT>)lpVtbl[4])(pThis, szName, lHashVal, out ppTInfo, out ppTComp).ThrowOnFailure();
			}
			private void** lpVtbl;
			/// <summary>The IID guid for this interface.</summary>
			/// <value>{00020403-0000-0000-c000-000000000046}</value>
			internal static readonly Guid IID_Guid = new Guid(0x00020403, 0x0000, 0x0000, 0xC0, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x46);

			static ref readonly Guid IComIID.Guid			{
								[MethodImpl(MethodImplOptions.AggressiveInlining)]
get
				{
					ReadOnlySpan<byte> data = new byte[]					{
0x03,0x04,0x02,0x00,0x00,0x00,0x00,0x00,0xC0,0x00,0x00,0x00,0x00,0x00,0x00,0x46					};
					return ref Unsafe.As<byte,Guid>(ref MemoryMarshal.GetReference(data));
				}
			}
		}
	}
}
