// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

#pragma warning disable CS1591,CS1573,CS0465,CS0649,CS8019,CS1570,CS1584,CS1658,CS0436,CS8981
using global::System;
using global::System.Diagnostics;
using global::System.Diagnostics.CodeAnalysis;
using global::System.Runtime.CompilerServices;
using global::System.Runtime.InteropServices;
using global::System.Runtime.Versioning;
using winmdroot = global::Windows.Win32;
namespace Windows.Win32
{
	namespace UI.Shell
	{
		/// <summary>Used by methods of the ITaskbarList3 interface to define buttons used in a toolbar embedded in a window's thumbnail representation.</summary>
		/// <remarks>
		/// <para>When a button is clicked, a <a href="https://docs.microsoft.com/windows/desktop/menurc/wm-command">WM_COMMAND</a> message that contains the button ID is sent to the associated application window. The application handles whatever action it has assigned to the button. <h3><a id="Button_Images"></a><a id="button_images"></a><a id="BUTTON_IMAGES"></a>Button Images</h3> When using an icon, specified through the <b>hIcon</b> member, the taskbar makes its own copy of the icon. It is the caller's responsibility to free the handle it passed in <b>hIcon</b> when it is no longer needed.</para>
		/// <para>If both an icon and an image list are specified for a button's image, the icon is used if possible. If for some reason the attempt to retrieve the icon fails, the image from the image list is used. Applications must provide these button images: </para>
		/// <para>This doc was truncated.</para>
		/// <para><see href="https://docs.microsoft.com/windows/win32/api//shobjidl_core/ns-shobjidl_core-thumbbutton#">Read more on docs.microsoft.com</see>.</para>
		/// </remarks>
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.164-beta+187018bf44")]
		internal partial struct THUMBBUTTON
		{
			/// <summary>
			/// <para>Type: <b><a href="https://docs.microsoft.com/windows/desktop/api/shobjidl_core/ne-shobjidl_core-thumbbuttonmask">THUMBBUTTONMASK</a></b> A combination of <a href="https://docs.microsoft.com/windows/desktop/api/shobjidl_core/ne-shobjidl_core-thumbbuttonmask">THUMBBUTTONMASK</a> values that specify which members of this structure contain valid data; other members are ignored, with the exception of <b>iId</b>, which is always required.</para>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//shobjidl_core/ns-shobjidl_core-thumbbutton#members">Read more on docs.microsoft.com</see>.</para>
			/// </summary>
			internal winmdroot.UI.Shell.THUMBBUTTONMASK dwMask;
			/// <summary>
			/// <para>Type: <b>UINT</b> The application-defined identifier of the button, unique within the toolbar.</para>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//shobjidl_core/ns-shobjidl_core-thumbbutton#members">Read more on docs.microsoft.com</see>.</para>
			/// </summary>
			internal uint iId;
			/// <summary>
			/// <para>Type: <b>UINT</b> The zero-based index of the button image within the image list set through <a href="https://docs.microsoft.com/windows/desktop/api/shobjidl_core/nf-shobjidl_core-itaskbarlist3-thumbbarsetimagelist">ITaskbarList3::ThumbBarSetImageList</a>.</para>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//shobjidl_core/ns-shobjidl_core-thumbbutton#members">Read more on docs.microsoft.com</see>.</para>
			/// </summary>
			internal uint iBitmap;
			/// <summary>
			/// <para>Type: <b>HICON</b> The handle of an icon to use as the button image.</para>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//shobjidl_core/ns-shobjidl_core-thumbbutton#members">Read more on docs.microsoft.com</see>.</para>
			/// </summary>
			internal winmdroot.UI.WindowsAndMessaging.HICON hIcon;
			/// <summary>
			/// <para>Type: <b>WCHAR[260]</b> A wide character array that contains the text of the button's tooltip, displayed when the mouse pointer hovers over the button.</para>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//shobjidl_core/ns-shobjidl_core-thumbbutton#members">Read more on docs.microsoft.com</see>.</para>
			/// </summary>
			internal winmdroot.__char_260 szTip;
			/// <summary>
			/// <para>Type: <b><a href="https://docs.microsoft.com/windows/desktop/api/shobjidl_core/ne-shobjidl_core-thumbbuttonflags">THUMBBUTTONFLAGS</a></b> A combination of <a href="https://docs.microsoft.com/windows/desktop/api/shobjidl_core/ne-shobjidl_core-thumbbuttonflags">THUMBBUTTONFLAGS</a> values that control specific states and behaviors of the button.</para>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//shobjidl_core/ns-shobjidl_core-thumbbutton#members">Read more on docs.microsoft.com</see>.</para>
			/// </summary>
			internal winmdroot.UI.Shell.THUMBBUTTONFLAGS dwFlags;
		}
	}
}
