// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

#pragma warning disable CS1591,CS1573,CS0465,CS0649,CS8019,CS1570,CS1584,CS1658,CS0436,CS8981
using global::System;
using global::System.Diagnostics;
using global::System.Diagnostics.CodeAnalysis;
using global::System.Runtime.CompilerServices;
using global::System.Runtime.InteropServices;
using global::System.Runtime.Versioning;
using winmdroot = global::Windows.Win32;
namespace Windows.Win32
{
	namespace System.Com
	{
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.164-beta+187018bf44")]
		internal partial struct VARDESC_unmanaged
		{
			internal int memid;
			internal winmdroot.Foundation.PWSTR lpstrSchema;
			internal winmdroot.System.Com.VARDESC_unmanaged._Anonymous_e__Union_unmanaged Anonymous;
			internal winmdroot.System.Com.ELEMDESC_unmanaged elemdescVar;
			internal winmdroot.System.Com.VARFLAGS wVarFlags;
			internal winmdroot.System.Com.VARKIND varkind;

			[StructLayout(LayoutKind.Explicit)]
			[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.164-beta+187018bf44")]
			internal partial struct _Anonymous_e__Union_unmanaged
			{
				[FieldOffset(0)]
				internal uint oInst;
				[FieldOffset(0)]
				internal unsafe winmdroot.System.Com.VARIANT_unmanaged* lpvarValue;
			}
		}
	}
}
