// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

#pragma warning disable CS1591,CS1573,CS0465,CS0649,CS8019,CS1570,CS1584,CS1658,CS0436,CS8981
using global::System;
using global::System.Diagnostics;
using global::System.Diagnostics.CodeAnalysis;
using global::System.Runtime.CompilerServices;
using global::System.Runtime.InteropServices;
using global::System.Runtime.Versioning;
using winmdroot = global::Windows.Win32;
namespace Windows.Win32
{
	[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.164-beta+187018bf44")]
	internal static partial class UI_Shell_ICustomDestinationList_Extensions
	{
		/// <inheritdoc cref="winmdroot.UI.Shell.ICustomDestinationList.SetAppID(winmdroot.Foundation.PCWSTR)"/>
		internal static unsafe void SetAppID(this winmdroot.UI.Shell.ICustomDestinationList @this, string pszAppID)
		{
			fixed (char* pszAppIDLocal = pszAppID)
			{
				@this.SetAppID(pszAppIDLocal);
			}
		}

		/// <inheritdoc cref="winmdroot.UI.Shell.ICustomDestinationList.BeginList(uint*, global::System.Guid*, out object)"/>
		internal static unsafe void BeginList(this winmdroot.UI.Shell.ICustomDestinationList @this, out uint pcMinSlots, in global::System.Guid riid, out object ppv)
		{
			fixed (global::System.Guid* riidLocal = &riid)
			{
				fixed (uint* pcMinSlotsLocal = &pcMinSlots)
				{
					@this.BeginList(pcMinSlotsLocal, riidLocal, out ppv);
				}
			}
		}

		/// <inheritdoc cref="winmdroot.UI.Shell.ICustomDestinationList.AppendCategory(winmdroot.Foundation.PCWSTR, winmdroot.UI.Shell.Common.IObjectArray)"/>
		internal static unsafe void AppendCategory(this winmdroot.UI.Shell.ICustomDestinationList @this, string pszCategory, winmdroot.UI.Shell.Common.IObjectArray poa)
		{
			fixed (char* pszCategoryLocal = pszCategory)
			{
				@this.AppendCategory(pszCategoryLocal, poa);
			}
		}

		/// <inheritdoc cref="winmdroot.UI.Shell.ICustomDestinationList.GetRemovedDestinations(global::System.Guid*, out object)"/>
		internal static unsafe void GetRemovedDestinations(this winmdroot.UI.Shell.ICustomDestinationList @this, in global::System.Guid riid, out object ppv)
		{
			fixed (global::System.Guid* riidLocal = &riid)
			{
				@this.GetRemovedDestinations(riidLocal, out ppv);
			}
		}

		/// <inheritdoc cref="winmdroot.UI.Shell.ICustomDestinationList.DeleteList(winmdroot.Foundation.PCWSTR)"/>
		internal static unsafe void DeleteList(this winmdroot.UI.Shell.ICustomDestinationList @this, string pszAppID)
		{
			fixed (char* pszAppIDLocal = pszAppID)
			{
				@this.DeleteList(pszAppIDLocal);
			}
		}
	}
}
