// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

#pragma warning disable CS1591,CS1573,CS0465,CS0649,CS8019,CS1570,CS1584,CS1658,CS0436,CS8981
using global::System;
using global::System.Diagnostics;
using global::System.Diagnostics.CodeAnalysis;
using global::System.Runtime.CompilerServices;
using global::System.Runtime.InteropServices;
using global::System.Runtime.Versioning;
using winmdroot = global::Windows.Win32;
namespace Windows.Win32
{
	namespace UI.Shell
	{
		/// <summary>Used by the THUMBBUTTON structure to specify which members of that structure contain valid data.</summary>
		/// <remarks>
		/// <para><see href="https://docs.microsoft.com/windows/win32/api//shobjidl_core/ne-shobjidl_core-thumbbuttonmask">Learn more about this API from docs.microsoft.com</see>.</para>
		/// </remarks>
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.164-beta+187018bf44")]
		internal enum THUMBBUTTONMASK
		{
			/// <summary>The <b>iBitmap</b> member contains valid information.</summary>
			THB_BITMAP = 1,
			/// <summary>The <b>hIcon</b> member contains valid information.</summary>
			THB_ICON = 2,
			/// <summary>The <b>szTip</b> member contains valid information.</summary>
			THB_TOOLTIP = 4,
			/// <summary>The <b>dwFlags</b> member contains valid information.</summary>
			THB_FLAGS = 8,
		}
	}
}
