// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

#pragma warning disable CS1591,CS1573,CS0465,CS0649,CS8019,CS1570,CS1584,CS1658,CS0436,CS8981
using global::System;
using global::System.Diagnostics;
using global::System.Diagnostics.CodeAnalysis;
using global::System.Runtime.CompilerServices;
using global::System.Runtime.InteropServices;
using global::System.Runtime.Versioning;
using winmdroot = global::Windows.Win32;
namespace Windows.Win32
{
	[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.164-beta+187018bf44")]
	internal static partial class UI_Shell_PropertiesSystem_IPropertyStore_Extensions
	{
		/// <inheritdoc cref="winmdroot.UI.Shell.PropertiesSystem.IPropertyStore.GetCount(uint*)"/>
		internal static unsafe void GetCount(this winmdroot.UI.Shell.PropertiesSystem.IPropertyStore @this, out uint cProps)
		{
			fixed (uint* cPropsLocal = &cProps)
			{
				@this.GetCount(cPropsLocal);
			}
		}

		/// <inheritdoc cref="winmdroot.UI.Shell.PropertiesSystem.IPropertyStore.GetAt(uint, winmdroot.UI.Shell.PropertiesSystem.PROPERTYKEY*)"/>
		internal static unsafe void GetAt(this winmdroot.UI.Shell.PropertiesSystem.IPropertyStore @this, uint iProp, out winmdroot.UI.Shell.PropertiesSystem.PROPERTYKEY pkey)
		{
			fixed (winmdroot.UI.Shell.PropertiesSystem.PROPERTYKEY* pkeyLocal = &pkey)
			{
				@this.GetAt(iProp, pkeyLocal);
			}
		}

		/// <inheritdoc cref="winmdroot.UI.Shell.PropertiesSystem.IPropertyStore.GetValue(winmdroot.UI.Shell.PropertiesSystem.PROPERTYKEY*, out winmdroot.System.Com.StructuredStorage.PROPVARIANT)"/>
		internal static unsafe void GetValue(this winmdroot.UI.Shell.PropertiesSystem.IPropertyStore @this, in winmdroot.UI.Shell.PropertiesSystem.PROPERTYKEY key, out winmdroot.System.Com.StructuredStorage.PROPVARIANT pv)
		{
			fixed (winmdroot.UI.Shell.PropertiesSystem.PROPERTYKEY* keyLocal = &key)
			{
				@this.GetValue(keyLocal, out pv);
			}
		}

		/// <inheritdoc cref="winmdroot.UI.Shell.PropertiesSystem.IPropertyStore.SetValue(winmdroot.UI.Shell.PropertiesSystem.PROPERTYKEY*, in winmdroot.System.Com.StructuredStorage.PROPVARIANT)"/>
		internal static unsafe void SetValue(this winmdroot.UI.Shell.PropertiesSystem.IPropertyStore @this, in winmdroot.UI.Shell.PropertiesSystem.PROPERTYKEY key, in winmdroot.System.Com.StructuredStorage.PROPVARIANT propvar)
		{
			fixed (winmdroot.UI.Shell.PropertiesSystem.PROPERTYKEY* keyLocal = &key)
			{
				@this.SetValue(keyLocal, in propvar);
			}
		}
	}
}
